docs/src/docs/pages/examples.mdx

Fix use-use typo

---

configuration/storybook/main.js

Fixes the story import issues on different OS including windows, mac etc.

[Core] Fix storybook configuration

---

scripts/docgen/prepare-declaration.ts

[Docs] Sort the props in alphabetical order

---

docs/src/docs/core/Checkbox.mdx
docs/src/docs/demos/core/Checkbox/checkbox-indeterminate.demo.tsx
docs/src/docs/demos/core/Checkbox/checkbox.configurator.tsx
docs/src/docs/hooks/use-list-state.mdx
docs/src/docs/pages/examples.mdx
src/mantine-core/src/Checkbox/Checkbox.story.tsx
src/mantine-core/src/Checkbox/Checkbox.test.tsx
src/mantine-core/src/Checkbox/Checkbox.tsx
src/mantine-core/src/Checkbox/CheckboxIcon.tsx
src/mantine-demos/src/IndeterminateCheckbox/IndeterminateCheckbox.tsx
src/mantine-demos/src/IndeterminateCheckbox/indeterminateCheckbox.story.tsx
src/mantine-demos/src/index.ts

[Core, Docs] fix checkbox indeterminate prop

---

src/mantine-hooks/src/use-media-query/use-media-query.ts

[@mantine/hooks] use-media-query: Set initial state based on query

---

docs/src/components/Layout/Footer/Footer.tsx

Typo on the abbreviation of Advertising.

Update Footer.tsx - typo

---

package.json
src/mantine-core/package.json
src/mantine-hooks/package.json
src/mantine-notifications/package.json
src/mantine-tag-picker/package.json

I noticed that the `repository` field of the package.json files were not always set and thought that it would spare you some time by making a PR.
Cheers!

update repository field in package.json files

---

docs/src/docs/core/Badge.mdx
src/mantine-core/src/components/Badge/Badge.story.tsx
src/mantine-core/src/components/Badge/Badge.styles.ts
src/mantine-core/src/components/Badge/Badge.tsx
src/mantine-core/src/components/Badge/demos/dots.tsx
src/mantine-core/src/components/Badge/demos/index.ts

This PR adds a new variant `dot` to the badge. 
I have updated the docs and make sure the tests are running well before creating the PR.
Local Testing could be done using storybooks.

[Core, Docs] Add variant Dot to Badge

---

docs/src/docs/core/ThemeIcon.mdx

This PR fixes some small grammar and spelling mistakes in the ThemeIcon docs

Fixes grammar and spelling mistakes in ThemeIcon docs

---

docs/src/demos/hooks/use-intersection.tsx
docs/src/demos/hooks/use-intersection/contained.tsx
docs/src/demos/hooks/use-intersection/index.ts
docs/src/demos/hooks/use-intersection/simple.tsx
docs/src/demos/index.ts
docs/src/docs/hooks/use-intersection.mdx
src/mantine-hooks/src/index.ts
src/mantine-hooks/src/use-intersection/use-intersection.ts

This PR adds the `use-intersection` hook.
[Trello link.](https://trello.com/c/q3ad148i/22-mantine-hooks-use-intersection)

[@mantine/hooks, Contribution] Add use-intersection

---

docs/src/demos/hooks/use-hotkey.tsx
docs/src/demos/index.ts
docs/src/docs/hooks/use-hotkey.mdx
src/mantine-hooks/src/index.ts
src/mantine-hooks/src/use-hotkey/parse-hotkey.ts
src/mantine-hooks/src/use-hotkey/use-hotkey.test.tsx
src/mantine-hooks/src/use-hotkey/use-hotkey.ts

`use-hotkey` hook from Backlog item https://trello.com/c/jyyVZq0A

[@mantine/hooks]: use-hotkey

---

docs/src/components/MdxPage/MdxPageTabs/MdxPageTabs.tsx
docs/src/components/MdxPage/MdxPageTabs/PropsTable/PropsTable.tsx

Adding Search Feature for component props. Which completes the requirement as in here https://trello.com/c/obo7dTPn

Search Feature for Component Props

---

docs/src/demos/hooks/use-logger.tsx
docs/src/demos/index.ts
docs/src/docs/hooks/use-logger.mdx
src/mantine-hooks/src/index.ts
src/mantine-hooks/src/use-logger/use-logger.ts

[@mantine/hooks] use-logger: add hook

---

docs/src/demos/hooks/use-idle.tsx
docs/src/demos/index.ts
docs/src/docs/hooks/use-idle.mdx
src/mantine-hooks/README.md
src/mantine-hooks/src/index.ts
src/mantine-hooks/src/use-idle/use-idle.test.tsx
src/mantine-hooks/src/use-idle/use-idle.ts

Hi @rtivital, 
Implementaion for useIdle hook following the signature :
```function useIdle(timeout: number, cb?: () => void): boolean;```
1. added an additional optional callback argument to access the event.
Let me know if it is fine or needs any tweaks, thereafter shall proceed with the documentation.
Thanks.

useIdle hook implementation

---

docs/src/docs/hooks/use-shallow-effect.mdx
src/mantine-hooks/src/index.ts
src/mantine-hooks/src/use-shallow-effect/use-shallow-effect.test.ts
src/mantine-hooks/src/use-shallow-effect/use-shallow-effect.ts
src/mantine-hooks/src/utils/shallow-compare/shallow-compare.test.ts
src/mantine-hooks/src/utils/shallow-compare/shallow-compare.ts

Hi @rtivital,
Implemented the useShallowEffect hook, shall write the tests and docs once you review this as I am not really clear about shallow comparison for other types and the scope of this hook.
Hope I am not being a hassle 😄 😓.  
Thanks

useShallowEffect hook implementation.

---

docs/src/components/Layout/Header/Search/Search.tsx
docs/src/components/Layout/Header/Search/SearchItem.tsx
src/mantine-core/src/components/Autocomplete/Autocomplete.styles.ts
src/mantine-core/src/components/Autocomplete/Autocomplete.test.tsx
src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
src/mantine-core/src/components/Autocomplete/styles.api.ts

This PR fixes -
- Nothing Label on zero results for autocomplete.
- Migration to Autocomplete in Navbar for search functionality.

Autocomplete migration

---

src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
src/mantine-core/src/components/Select/Select.tsx

Fixes Issue 203

---

src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts

This PR implements re-factoring in use-focus-trap

Clean use-focus-trap

---

docs/src/docs/core/SegmentedControl.mdx
src/mantine-core/src/components/SegmentedControl/SegmentedControl.story.tsx
src/mantine-core/src/components/SegmentedControl/SegmentedControl.tsx

Update `SegmentedControl` to allow for a simple `data` prop.

Update SegmentedControl component, story and docs

---

src/mantine-core/src/components/NumberInput/NumberInput.tsx
src/mantine-core/src/components/Tabs/Tabs.tsx

Using clamp util

---

src/mantine-hooks/src/use-logger/use-logger.test.ts
src/mantine-hooks/src/use-logger/use-logger.ts

Added test for the `useLogger` hook
~~This PR depends on #355~~

[@mantine/hooks] use-logger: Add tests

---

docs/src/docs/core/Input.mdx

Fix a small grammar mistake in the description of the Input component.

[docs] Fix a small grammar mistake in the description of the Input component

---

src/mantine-hooks/src/use-pagination/use-pagination.ts

fixes this [discord issue](https://discord.com/channels/854810300876062770/854810300876062773/907676555982024765) requested by milanjain2189

[mantine/hooks] usePaginatino: remove memoization

---

docs/src/docs/theming/create-styles.mdx
src/mantine-styles/src/theme/GlobalStyles.tsx

Updates GlobalStyles to also set fontSize on body using the size md from theme.

@mantine/core GlobalStyles - set fontSize

---

src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
src/mantine-core/src/components/NumberInput/NumberInput.tsx

[@mantine/core] NumberInput: Add the ability for the field to be empty

---

docs/src/docs/dates/date-range-picker.mdx
docs/src/docs/dates/range-calendar.mdx
src/mantine-dates/src/components/Calendar/CalendarHeader/CalendarHeader.test.tsx
src/mantine-dates/src/components/Calendar/CalendarHeader/CalendarHeader.tsx
src/mantine-dates/src/components/Calendar/CalendarWrapper/CalendarWrapper.test.tsx
src/mantine-dates/src/components/Calendar/CalendarWrapper/CalendarWrapper.tsx
src/mantine-dates/src/components/Calendar/get-disabled-state/get-disabled-state.test.ts
src/mantine-dates/src/components/Calendar/get-disabled-state/get-disabled-state.ts
src/mantine-dates/src/components/DateRangePicker/DateRangePicker.story.tsx
src/mantine-dates/src/components/DateRangePicker/DateRangePicker.tsx
src/mantine-dates/src/components/DateRangePicker/demos/index.ts
src/mantine-dates/src/components/DateRangePicker/demos/multiMonth.tsx
src/mantine-dates/src/components/Month/Month.tsx
src/mantine-dates/src/components/RangeCalendar/RangeCalendar.story.tsx
src/mantine-dates/src/components/RangeCalendar/RangeCalendar.test.tsx
src/mantine-dates/src/components/RangeCalendar/RangeCalendar.tsx
src/mantine-dates/src/components/RangeCalendar/demos/index.ts
src/mantine-dates/src/components/RangeCalendar/demos/multiMonth.tsx

Had some issues with the other pr (#404), bud did implement the feedback. This pr fixes #396

[@mantine-dates] RangeCalendar & DateRangePicker: multiple months

---

src/mantine-hooks/src/use-local-storage-value/use-local-storage-value.ts

This fixes #424 
Let me know if this is sufficient enough.

Fixed return of null in first render in useLocalStorageValue

---

src/mantine-core/src/components/Select/Select.tsx

Fixes clear when creatable prop is set.

---

docs/src/docs/core/AppShell.mdx
docs/src/docs/theming/responsive.mdx

updating the docs to include theme definition
related discussion: [https://github.com/mantinedev/mantine/discussions/436](https://github.com/mantinedev/mantine/discussions/436)

[docs] update the missing theme var

---

src/mantine-core/src/components/Select/Select.tsx

fixes #454 
I didn't see any opportunity for similar logic in`MultiSelect` and `Autocomplete` since they work a bit differently

[@mantine/core] Select: improve keyboard navigation

---

src/mantine-core/src/components/Modal/Modal.tsx

Hi 
This is my first PR ever, please let me know if I need to make any more changes.

[core] Add radius prop to Modal component

---

src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
src/mantine-core/src/components/NumberInput/NumberInput.tsx
src/mantine-hooks/src/use-os/use-os.story.tsx
src/mantine-hooks/src/use-os/use-os.ts

Fix for https://github.com/mantinedev/mantine/issues/516 and https://github.com/mantinedev/mantine/issues/519

Fix for #516 and #519

---

src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
src/mantine-core/src/components/NumberInput/NumberInput.tsx
src/mantine-core/src/components/NumberInput/demos/decimalSeparator.tsx
src/mantine-core/src/components/NumberInput/demos/index.ts

This is for https://github.com/mantinedev/mantine/issues/521

[@mantine/core] NumberInput: Add decimal separator prop

---

src/mantine-core/src/components/NumberInput/demos/decimalSeparator.tsx

I forgot to change the placeholder.

[@mantine/core] NumberInput: Fix decimalSeparator placeholder demo

---

src/mantine-notifications/src/demos/interactive.tsx
src/mantine-notifications/src/demos/root.tsx

Fix for https://github.com/mantinedev/mantine/discussions/540

[@mantine/notifications] Remove "autoClose: false" from Input with button

---

docs/src/docs/others/notifications.mdx
src/mantine-core/src/components/Notification/Notification.styles.ts
src/mantine-core/src/components/Notification/Notification.tsx
src/mantine-core/src/components/Notification/demos/configurator.tsx

Fix for https://github.com/mantinedev/mantine/issues/559

[@mantine/notifications] Notifications: Add `radius` prop

---

src/mantine-core/src/components/Popper/Popper.styles.ts
src/mantine-core/src/components/Popper/Popper.tsx
src/mantine-core/src/components/Tooltip/Tooltip.styles.ts
src/mantine-core/src/components/Tooltip/Tooltip.tsx
src/mantine-core/src/components/Tooltip/demos/configurator.tsx

Fixes https://github.com/mantinedev/mantine/issues/560

[@mantine/core] Tooltip: Add the `radius` prop

---

src/mantine-core/src/components/Group/Group.test.tsx
src/mantine-core/src/components/Group/Group.tsx
src/mantine-core/src/utils/filter-falsy-children/filter-falsy-children.test.tsx
src/mantine-core/src/utils/filter-falsy-children/filter-falsy-children.ts

Fix for https://github.com/mantinedev/mantine/issues/565

[@mantine/core] Group: Fix incorrect size

---

docs/src/docs/core/TransferList.mdx
src/mantine-core/src/components/MultiSelect/MultiSelect.tsx
src/mantine-core/src/components/Select/Select.tsx
src/mantine-core/src/components/Select/SelectItems/SelectItems.tsx
src/mantine-core/src/components/TransferList/RenderList/RenderList.styles.ts
src/mantine-core/src/components/TransferList/RenderList/RenderList.tsx
src/mantine-core/src/components/TransferList/demos/group.tsx
src/mantine-core/src/components/TransferList/demos/index.ts
src/mantine-core/src/components/TransferList/styles.api.ts
src/mantine-core/src/components/TransferList/types.ts
src/mantine-core/src/utils/group-sort-data/group-sort-data.test.ts
src/mantine-core/src/utils/group-sort-data/group-sort-data.ts

Fix for https://github.com/mantinedev/mantine/issues/512

[@mantine/core] TransferList: Add grouping

---

src/mantine-rte/src/components/RichTextEditor/RichTextEditor.styles.ts
src/mantine-rte/src/components/RichTextEditor/RichTextEditor.tsx

This PR adds the `radius` prop to `RichTextEditor`.

[@mantine/rte] RichTextEditor: Add the `radius` prop.

---

docs/src/docs/core/Anchor.mdx

https://mantine.dev/core/anchor/

[docs] Fix wrong source

---

src/mantine-core/src/components/Select/Select.tsx

Creatable demo had string data as input.

[@mantine/core] Select: fix default shouldCreate

---

src/mantine-core/src/components/SegmentedControl/SegmentedControl.tsx
src/mantine-core/src/components/SegmentedControl/demos/index.ts
src/mantine-core/src/components/SegmentedControl/demos/scaled.tsx

Migrating SegmentedControl to useResizeObserver hook..
Update - 
This PR also fixes #585.

[@mantine/core] SegmentedControl - migrate to useResizeObserver hook

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
README.md
docs/src/components/Footer/data.ts
docs/src/components/GettingStarted/Guides/Guide.tsx
docs/src/components/HomePage/Community/Community.tsx
docs/src/components/HomePage/Jumbotron/Jumbotron.tsx
docs/src/components/SocialButton/SocialButton.tsx
docs/src/docs/hooks/use-form.mdx
docs/src/docs/pages/basics.mdx
docs/src/docs/pages/contributing.mdx
docs/src/pages/404.tsx
gallery/src/gallery/HeroTitle/HeroTitle.tsx
src/mantine-core/src/components/Notification/demos/configurator.tsx

Update to the proper casing for GitHub instead of `Github`.

[*] s/Github/GitHub

---

src/mantine-dates/src/components/DatePicker/DatePicker.tsx

Fixes https://github.com/mantinedev/mantine/issues/652

[@mantine/dates] DatePicker: Clamp date on blur

---

src/mantine-core/src/components/Select/Select.tsx

Fixes https://github.com/mantinedev/mantine/issues/653

[@mantine/core] Select: Fix pre-scroll

---

docs/src/demos/hooks/use-idle.tsx

Copy / paste is not working cause `idleStatus` should be renamed to `idle`

Fix(docs): Idle demos

---

src/mantine-core/src/components/SegmentedControl/SegmentedControl.styles.ts

[@mantine/core] Fix SegmentedControl borders around selected control

---

src/mantine-dates/src/components/DatePicker/DatePicker.tsx

Fixes https://github.com/mantinedev/mantine/issues/706

[@mantine/dates] DatePicker: Allow selecting dates with Enter key

---

src/mantine-dates/src/components/TimeInput/TimeInput.tsx

Fixes https://github.com/mantinedev/mantine/issues/698

[@mantine/dates] TimeInput: Call onChange when input is changed

---

src/mantine-core/src/components/Tabs/Tabs.tsx

[@mantine/core] Fix Tabs content not having a key

---

CONTRIBUTING.md

This PR reorganizes and rewords some of the contributing guidelines for Mantine. Namely:
- Ways to contribute to the project
- Developer contribution workflow
- General sentence structure
Extra food for thought: it would be nice to have a merge request format to add some more consistency to the repo 😁

[docs] Contributing: Reorganize and reword guidelines for contributing to Mantine

---

docs/src/docs/core/Text.mdx
src/mantine-core/src/components/Text/Text.styles.ts
src/mantine-core/src/components/Text/Text.tsx
src/mantine-core/src/components/Text/demos/usage.tsx

Fixes https://github.com/mantinedev/mantine/issues/729

[@mantine/core] Text: Add underline prop

---

src/mantine-core/src/components/TransferList/RenderList/RenderList.styles.ts

Fixes https://github.com/mantinedev/mantine/issues/722
Before this PR:
After this PR:

[@mantine/core] TransferList: Fix radius

---

src/mantine-dates/src/components/TimeInput/TimeInput.tsx

Fixes https://github.com/mantinedev/mantine/issues/714

[@mantine/dates] TimeInput: Fix infinite loop of onChange calls

---

src/mantine-core/src/components/SegmentedControl/SegmentedControl.styles.ts
src/mantine-core/src/components/SegmentedControl/SegmentedControl.tsx
src/mantine-core/src/components/SegmentedControl/styles.api.ts

`disabled={false}`:
`disabled={true}`:

Add `disabled` prop to SegmentedControl

---

src/mantine-dates/src/components/TimeInputBase/AmPmInput/AmPmInput.tsx

Fixes https://github.com/mantinedev/mantine/pull/607#issuecomment-1019527356

[@mantine/dates] TimeInput: Fixed non-qwerty keyboard support

---

docs/src/docs/core/ColorInput.mdx

[docs] ColorInput: fix `Controlled` example

---

docs/src/docs/core/Group.mdx

[docs] Fix Group children usage

---

src/mantine-core/src/components/Progress/Progress.styles.ts

[@mantine/core] Progress: Fix line break

---

docs/src/demos/modals/confirm.tsx

Fixes https://github.com/mantinedev/mantine/issues/761

[docs] Fix Confirm modal code example

---

docs/src/docs/hooks/use-hotkeys.mdx

Simple diff explains proposal, open to counterproposals.

Link to docs on key name format

---

src/mantine-core/src/components/Tooltip/Tooltip.test.tsx
src/mantine-core/src/components/Tooltip/Tooltip.tsx
src/mantine-demos/src/demos/packages/Tooltip/delay.tsx

[@mantine/core] Tooltip: Add "openDelay" prop

---

docs/src/components/MdxPage/MdxPageTabs/StylesApi/generate-styles-code.ts

[docs] Add missing commas in classNames section

---

docs/src/docs/theming/styles-api.mdx

This PR just fixes some minor documentation on the Styles API page.

[docs] Fix documentation Styles API

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

there were minor typos in the useForm docs, so i corrected them.
Let me know if I need to provide anything else with this PR

minor typos in use-form.mdx corrected

---

docs/src/docs/others/notifications.mdx

Looking to get involved with open source, so found the smallest change I could start with. Looking forward to working on some more contributions.

[docs] Update notifications.mdx: Fixed 'and' misspelling.

---

src/mantine-hooks/src/use-interval/use-interval.test.ts

Hi, This PR adds some unit tests on [use-interval](https://github.com/mantinedev/mantine/blob/master/src/mantine-hooks/src/use-interval/use-interval.ts) hook.

[@mantine/hooks] use-interval: Add unit tests

---

src/mantine-core/src/components/Portal/Portal.tsx

I need a `Portal` with a `fixed` position, it would be nice to be able to accomplish this directly!

Allow override of position property in Portal

---

src/mantine-core/src/components/Avatar/Avatar.tsx

[@mantine/core] Avatar: fix src typings

---

src/mantine-core/package.json
src/mantine-dates/package.json
src/mantine-dropzone/package.json
src/mantine-hooks/package.json
src/mantine-modals/package.json
src/mantine-next/package.json
src/mantine-notifications/package.json
src/mantine-prism/package.json
src/mantine-rte/package.json
src/mantine-ssr/package.json
src/mantine-storybook/package.json
src/mantine-styles/package.json

[core] Add keywords to all non private packages

---

src/mantine-demos/src/demos/packages/RichTextEditor/simple.tsx

[docs] fix react import

---

docs/src/pages/404.tsx

Added "a" and "the" in 404.tsx to improve readability

Fix missing text for better readability

---

src/mantine-core/src/components/TransferList/DefaultItem/DefaultItem.tsx
src/mantine-core/src/components/TransferList/RenderList/RenderList.styles.ts
src/mantine-core/src/components/TransferList/RenderList/RenderList.tsx
src/mantine-core/src/components/TransferList/TransferList.tsx
src/mantine-core/src/components/TransferList/types.ts

Fixes https://github.com/mantinedev/mantine/issues/508

[@mantine/core] TransferList: Add radius prop

---

src/mantine-core/src/components/Accordion/Accordion.story.tsx
src/mantine-core/src/components/Accordion/AccordionItem/AccordionItem.styles.ts
src/mantine-demos/src/demos/packages/Accordion/stylesApi.tsx

Fixes rotation behavior of nested accordion icons
Resolves https://github.com/mantinedev/mantine/issues/925

[@mantine/core]: Accordion: Fix rotation behavior of nested accordion icons

---

src/mantine-rte/src/components/RichTextEditor/default-labels.ts

Add missing labels to Rich Text Editor

[@mantine/rte] Add missing labels

---

docs/src/components/Layout/Navbar/NavbarDocsCategory/NavbarDocsCategory.tsx

Fixes the issue where the navbar would scroll the navbar item into view if the window was resized

[docs] Fix navbar scroll on height change

---

src/mantine-styles/src/theme/types/MantineColor.ts

[@mantine/styles] - Add teal back to DefaultMantineColor type

---

src/mantine-hooks/src/use-local-storage/use-local-storage.story.tsx
src/mantine-hooks/src/use-local-storage/use-local-storage.ts

[@mantine/hooks] fix falsy check for useLocalStorage reset to default value

---

src/mantine-core/src/components/MultiSelect/MultiSelect.tsx

[@mantine/core] MultiSelect: fix maxSelectedValues for controlled input

---

docs/src/docs/core/Tooltip.mdx
src/mantine-core/src/components/FloatingTooltip/FloatingTooltip.styles.ts
src/mantine-core/src/components/FloatingTooltip/FloatingTooltip.test.tsx
src/mantine-core/src/components/FloatingTooltip/FloatingTooltip.tsx
src/mantine-core/src/components/FloatingTooltip/index.ts
src/mantine-core/src/components/Popper/Popper.tsx
src/mantine-core/src/index.ts
src/mantine-demos/src/Demos.story.tsx
src/mantine-demos/src/demos/packages/FloatingTooltip/configurator.tsx
src/mantine-demos/src/demos/packages/FloatingTooltip/index.ts
src/mantine-demos/src/demos/packages/FloatingTooltip/positions.tsx
src/mantine-demos/src/index.ts

Creates the floating tooltip component.
Part of #700

[@mantine/core] FloatingTooltip

---

src/mantine-hooks/src/use-click-outside/use-click-outside.test.tsx
src/mantine-hooks/src/use-did-update/use-did-update.test.ts
src/mantine-hooks/src/use-hover/use-hover.test.tsx

I wrote another simple test (test coverage cannot be too high :)  !

[@mantine/hooks] use-did-update: Add tests

---

src/mantine-dates/src/components/DateRangePicker/DateRangePicker.tsx

Fixes https://github.com/mantinedev/mantine/issues/1154

[@mantine/dates] Fix allowLevelChange

---

src/mantine-core/src/components/Modal/Modal.tsx

I've implemented my proposed solution to #1008. Please let me know if there's any feedback or better ways to solve this.

Pass Modal transitionDuration prop to GroupedTransition (fixes #1008)

---

src/mantine-core/src/components/MultiSelect/MultiSelect.styles.ts

[@mantine/core] MultiSelect: Fix search input width

---

docs/src/docs/theming/next.mdx

Adding docs to prevent confusion when working with nextjs.
Solves: https://github.com/mantinedev/mantine/issues/1246

[docs] Adding more content to nextjs _document

---

src/mantine-core/src/components/Slider/Marks/Marks.styles.ts

[@mantine/core] Slider: add white-space nowrap for label

---

src/mantine-core/src/components/NumberInput/NumberInput.tsx

[@mantine/core] NumberInput: fix rightsectionwidth

---

docs/src/docs/theming/rtl.mdx

adds dynamic document direction to the docs, similar to https://github.com/mantinedev/mantine/blob/master/docs/src/components/Layout/Layout.tsx#L53

[docs] Update dynamic RTL section

---

docs/src/docs/hooks/use-focus-return.mdx

Plus some minor code highlighting improvements.

[docs] use-focus-return: Update example for shouldReturnFocus to reflect description.

---

src/mantine-modals/src/ModalsProvider.tsx
src/mantine-modals/src/use-modals/use-modals.test.tsx

[@mantine/modals] Fix context modals map type

---

README.md

"The" easiest not "an" easiest.

[readme]: fixed grammatical error

---

README.md

[docs] Update statistic

---

src/mantine-core/src/components/Text/Text.styles.ts
src/mantine-core/src/components/Text/Text.tsx
src/mantine-core/src/components/Text/Text.types.ts

Related to #1368.
Provides accurate intellisense for `dimmed` color value.

[@mantine/core] Text: Change color's type to include dimmed value.

---

package.json
src/mantine-ssr/package.json
yarn.lock

Update html-react-parser so that it supports react 18. 
Fixes #1381.

[@mantine/ssr] Update html-react-parser

---

docs/src/docs/core/Image.mdx

Fixed grammar for some parts so it is easier to read and understand.

Fixed grammar for Image.mdx

---

src/mantine-core/src/components/Slider/Thumb/Thumb.tsx

This should solve high CPU usage problems.
NOTE: there is one test failing, but it's independent of my changes, it's failing on main branch as well.
Closes #1436

Use `style` instead of `sx` to set thumb position

---

src/mantine-demos/src/demos/nprogress/NProgress.demo.autoReset.tsx
src/mantine-demos/src/demos/nprogress/index.ts
src/mantine-nprogress/src/NProgress.tsx

This PR makes resetting progress easier and more stable.
And also fixes a bug when withinPortal is false where the progress is centered and not on the left

[@mantine/nprogress] Add autoReset prop

---

src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
src/mantine-core/src/components/MultiSelect/MultiSelect.tsx
src/mantine-core/src/components/Select/Select.tsx

Fixes [aria-valid-attr-value](https://dequeuniversity.com/rules/axe/4.4/aria-valid-attr-value) issue I found with [@axe-core/react](https://www.npmjs.com/package/@axe-core/react).

Fix aria-owns attribute

---

src/mantine-demos/src/demos/modals/Modals.demo.content.tsx

Makes the docs display the actual code used and adds autofocus to the `TextInput` to improve the default UX.

Content modal demo fixes

---

src/mantine-demos/src/demos/core/Stepper/Stepper.demo.allowStepSelect.tsx

Typos in the docs Stepper component fixed

[docs] Fixed typo

---

docs/src/docs/core/Popper.mdx

[docs]: updated minor typo in popper docs

---

src/mantine-dropzone/src/mime-types.ts

add mime type for .exe files

---

src/mantine-hooks/src/use-move/use-move.story.tsx
src/mantine-hooks/src/use-move/use-move.ts

Fixes #1412 
I am using this hook in my project and have seen that it hasn't been fixed yet. I tried the solution of the person who suggested that issue and it works.
I also added a horizontal demo to the storybook, hope you don't mind

[@mantine/hooks] use-move: Fixed console errors, added horizontal demo to storybook

---

docs/src/docs/theming/dark-theme.mdx
src/mantine-styles/src/theme/ColorSchemeProvider.tsx

[@mantine/styles] Feature: add option do disable transitions

---

src/mantine-demos/src/demos/core/Menu/Menu.demo.usage.tsx

Errant comma

---

docs/src/docs/dates/date-picker.mdx
src/mantine-dates/src/components/DatePicker/DatePicker.tsx
src/mantine-dates/src/components/DatePickerBase/DatePickerBase.tsx
src/mantine-demos/src/demos/dates/DatePicker/DatePicker.demo.flip.tsx
src/mantine-demos/src/demos/dates/DatePicker/index.ts

[V5] Feat https://github.com/mantinedev/mantine/issues/1636
- Add dropdownPosition prop to DatePicker and documentation
Link to [Master MR](https://github.com/mantinedev/mantine/pull/1638)

[@mantine/dates] DatePicker: Add dropdownPosition prop

---

docs/src/docs/hooks/use-list-state.mdx
src/mantine-hooks/src/use-list-state/use-list-state.test.ts
src/mantine-hooks/src/use-list-state/use-list-state.ts

This PR adds .filter to UseListStateHandlers

Add .filter to UseListStateHandlers

---

docs/src/docs/hooks/use-list-state.mdx

Sorry, I have not properly define the useListState .filter handler (in the docs) in last PR

[docs] Fix: useListState .filter handler definition

---

docs/src/docs/core/Tabs.mdx

Minor documentation update for v5

[docs] Tabs: Update Tabs documentation to use setTab state onTabChange

---

src/mantine-demos/src/demos/carousel/Carousel.demo.cards.tsx
src/mantine-demos/src/demos/carousel/_card.tsx

[@mantine/carousel] Fix incorrect fontFamily style in cards demo

---

src/mantine-dropzone/package.json

It has some references to prism, that shouldnt be here

Fix Dropzone Package.json

---

docs/src/docs/core/LoadingOverlay.mdx
docs/src/docs/core/Overlay.mdx
docs/src/docs/core/Stepper.mdx
docs/src/docs/core/Tooltip.mdx
docs/src/docs/hooks/use-clipboard.mdx
docs/src/docs/others/prism.mdx

Fixed some misspellings/typos in the docs

[docs] Fixed a few misspellings

---

.github/ISSUE_TEMPLATE/bug_report.yml

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#body-must-have-unique-ids

[core] Update `id` attribute to `package` in bug report yml

---

docs/src/docs/hooks/use-toggle.mdx

[docs] Update use-toggle documentation with v5 API

---

.github/workflows/pull_request.yml
src/mantine-core/src/Burger/Burger.styles.ts

If you're doing multiple commits to the same PR, I thought it would be efficient to stop working on the CI of the previous commit.
For the configuration file, refer to vite.js below
https://github.com/vitejs/vite/blob/main/.github/workflows/ci.yml#L23

[core] cancel same in-progress workflow

---

CONTRIBUTING.md
docs/src/docs/hooks/use-debounced-state.mdx
docs/src/docs/hooks/use-debounced-value.mdx
src/mantine-demos/src/demos/hooks/index.ts
src/mantine-demos/src/demos/hooks/use-debounced-state.demo.leading.tsx
src/mantine-demos/src/demos/hooks/use-debounced-state.demo.usage.tsx
src/mantine-hooks/src/index.ts
src/mantine-hooks/src/use-debounced-state/use-debounced-state.story.tsx
src/mantine-hooks/src/use-debounced-state/use-debounced-state.test.ts
src/mantine-hooks/src/use-debounced-state/use-debounced-state.ts

From the discussion https://github.com/mantinedev/mantine/discussions/1679.
I mainly synchronized the contributing documents to include the instructions for how to build the packages.

[@mantine/hooks] Add use-debounced-state hook

---

src/mantine-core/src/Divider/Divider.tsx

[@mantine/core] Divider: Add `role="separator"` attribute

---

src/mantine-spotlight/src/Spotlight/Spotlight.tsx

#2050 added closeOnTrigger to actions but it only works when clicking, this PR adds the check to 'Enter' handler.

[@mantine/spotlight] Fix closeOnTrigger with 'Enter'

---

docs/src/docs/core/FileButton.mdx
src/mantine-demos/src/demos/core/FileButton/FileButton.demo.reset.tsx
src/mantine-demos/src/demos/core/FileButton/index.ts

[docs] Add reset part to FileButton docs (#2113)

---

docs/src/components/Layout/Layout.tsx

#2098 
https://github.com/gatsbyjs/gatsby/issues/29037#issuecomment-778701597

[docs] Improved docs keyboard accessibility

---

src/mantine-core/src/MultiSelect/MultiSelect.tsx

- fix dropdown opening when `maxSelectedValues` is reached
- fix `creatable` when using useForm

[@mantine/core] MultiSelect - minor fixes

---

src/mantine-styles/src/theme/utils/extract-system-styles/extract-system-styles.ts

If you use filterProps in the extractSystemStyles function, you can write more concise code.

[@mantine/styles] Improved extractSystemStyles function

---

src/mantine-dropzone/src/Dropzone.tsx
src/mantine-dropzone/src/index.ts

[@mantine/dropzone] Change onDrop type from File to FileWithPath (#2250)

---

src/mantine-core/src/Image/Image.tsx

[@mantine/core] Image: fix type validation value of `fit` props

---

src/mantine-hooks/src/use-local-storage/use-local-storage.ts

Fix until #2214 gets merged.
Currently, `useLocalStorage` returns default value in the `getInitialValueInEffect` `useEffect` if the stored value is falsy due to the `||` check. This can be verified even in the `SerializeBoolean` story. With the proposed change we support the storage of all falsy values including `null` (which should be completely valid).

[@mantine/hooks] use-local-storage: Fix for supporting falsy values.

---

src/mantine-core/src/Paper/Paper.tsx

```tsx
export default createStyles((theme, { radius, shadow, withBorder }: PaperStylesParams) => ({
root: {
// (...)
border: withBorder
? `1px solid ${theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[3]}` // here
: undefined,
},
}));
```
The actual code content and comments do not match.

[docs] Fix typo

---

src/mantine-core/src/Alert/Alert.styles.ts
src/mantine-core/src/Alert/Alert.tsx

Refactored by removing duplicate types.

[@mantine/core] Alert: remove duplicate types

---

src/mantine-notifications/src/NotificationContainer/NotificationContainer.tsx

https://github.com/mantinedev/mantine/issues/2327

fix the issue #2327

---

docs/src/docs/hooks/use-list-state.mdx

[docs] use-list-state: Fix filter description

---

src/mantine-carousel/src/CarouselSlide/CarouselSlide.styles.ts

[@mantine/carousel] CarouselSlide: remove margin from the last slide

---

src/mantine-core/src/AspectRatio/AspectRatio.styles.ts

[@mantine/core] AspectRatio: Fix ignore this parameter

---

src/mantine-core/src/Image/Image.tsx

[refactor] fix typo in Image/Image.tsx

---

docs/src/docs/core/Switch.mdx
scripts/docgen.ts
src/mantine-core/src/Switch/Switch.story.tsx
src/mantine-core/src/Switch/Switch.tsx
src/mantine-core/src/Switch/SwitchGroup.context.ts
src/mantine-core/src/Switch/SwitchGroup/SwitchGroup.test.tsx
src/mantine-core/src/Switch/SwitchGroup/SwitchGroup.tsx
src/mantine-core/src/Switch/index.ts
src/mantine-demos/src/demos/core/Switch/Switch.demo.groupConfigurator.tsx
src/mantine-demos/src/demos/core/Switch/index.ts

[mantine/core] Switch: create Switch.Group component

---

src/mantine-core/src/ColorInput/ColorInput.tsx
src/mantine-core/src/ColorPicker/AlphaSlider/AlphaSlider.test.tsx
src/mantine-core/src/ColorPicker/AlphaSlider/AlphaSlider.tsx
src/mantine-core/src/ColorPicker/ColorPicker.test.tsx
src/mantine-core/src/ColorPicker/ColorPicker.tsx
src/mantine-core/src/ColorPicker/ColorSlider/ColorSlider.test.tsx
src/mantine-core/src/ColorPicker/ColorSlider/ColorSlider.tsx
src/mantine-core/src/ColorPicker/HueSlider/HueSlider.test.tsx
src/mantine-core/src/ColorPicker/HueSlider/HueSlider.tsx
src/mantine-core/src/ColorPicker/Saturation/Saturation.tsx
src/mantine-core/src/ColorPicker/Swatches/Swatches.tsx

**Prop**
> Just like Slider onChangeEnd prop
```onChangeEnd?: (value: string) => void;```
**Effected Components**
- ColorPicker
- ColorInput

Add onChangeEnd prop on ColorPicker component

---

src/mantine-spotlight/src/Spotlight/Spotlight.styles.ts

Fix spotlight overflow scroll

---

src/mantine-carousel/package.json

[@mantine/carousel]  Wrong html home page from mantine/carousel #2522

---

src/mantine-core/src/Switch/Switch.styles.ts
src/mantine-core/src/Switch/Switch.tsx

[@mantine/core] Switch: add data-disabled + change color when disabled on label 

---

src/mantine-core/src/Checkbox/Checkbox.styles.ts
src/mantine-core/src/Checkbox/Checkbox.tsx

[@mantine/core] Checkbox: add data-disabled + change color when disabled on label

---

docs/src/docs/core/Collapse.mdx
src/mantine-core/src/Collapse/Collapse.tsx
src/mantine-core/src/Collapse/collapse.story.tsx
src/mantine-core/src/Collapse/use-collapse.ts
src/mantine-demos/src/demos/core/Collapse/collapse.demo.horizontal.tsx
src/mantine-demos/src/demos/core/Collapse/index.ts

Add axis prop for Collapse component 

---

docs/src/docs/core/Tabs.mdx

Update docs to include import useParams for example code to work properly.

Update docs to include import useParams

---

docs/src/docs/core/Accordion.mdx

thanks for maintaining this lib! 👋

Accordion.mdx - typo fix

---

docs/src/docs/core/Slider.mdx
src/mantine-core/src/Slider/RangeSlider/RangeSlider.tsx
src/mantine-core/src/Slider/Slider/Slider.tsx
src/mantine-core/src/Slider/Track/Track.styles.ts
src/mantine-core/src/Slider/Track/Track.tsx
src/mantine-demos/src/demos/core/Slider/Slider.demo.inverted.tsx
src/mantine-demos/src/demos/core/Slider/index.ts

Added an `inverted` prop to the `Slider` and `RangeSlider` components, as per @rtivital 's message [here](https://discord.com/channels/854810300876062770/887408088800448553/1016792289542148227).

[core] Slider: added inverted prop

---

src/mantine-core/src/List/List.styles.ts
src/mantine-core/src/List/ListItem/ListItem.styles.ts

[@mantine/core] Fix indentation on List (listStylePosition: 'inside')

---

src/mantine-core/src/MultiSelect/MultiSelect.tsx

[@mantine/core] MultiSelect: fix dropdown flicker and ondropdown handlers being called when dropdown isn't visible

---

src/mantine-core/src/Avatar/Avatar.story.tsx
src/mantine-core/src/Avatar/Avatar.tsx
src/mantine-core/src/ThemeIcon/ThemeIcon.story.tsx
src/mantine-core/src/ThemeIcon/ThemeIcon.tsx

[@mantine/core] Avatar, ThemeIcon: Respect gradient from MantineProvider.

---

src/mantine-dates/src/components/DatePickerBase/DatePickerBase.tsx

corrected inputRef type from HTMLButtonElement to HTMLInputElement

[@mantine/dates] DatePickerBase: corrected inputRef type to HTMLInputElement

---

docs/src/docs/core/Collapse.mdx
src/mantine-core/src/Collapse/Collapse.tsx
src/mantine-core/src/Collapse/collapse.story.tsx
src/mantine-core/src/Collapse/use-collapse.ts
src/mantine-demos/src/demos/core/Collapse/collapse.demo.horizontal.tsx
src/mantine-demos/src/demos/core/Collapse/index.ts

Add axis prop for collapse component

---

docs/src/docs/form/use-form.mdx

[docs] Add use-form setValues usage with previous state explanation

---

src/mantine-demos/src/demos/core/Grid/Grid.demo.order.tsx

[docs] Grid: fixed docs code example

---

src/mantine-core/src/Box/style-system-props/system-props/system-props.ts
src/mantine-styles/src/theme/types/MantineStyleSystem.ts

- add support for right to mantine system props

[@mantine/core] Add missing right prop to system props

---

src/mantine-demos/src/demos/core/Grid/Grid.demo.content.tsx

Fix typo in Grid.demo.content.tsx

---

docs/src/docs/core/ScrollArea.mdx

disclaimer: i'm only ~90% sure what i'm proposing matches the actual intention/behavior.
i can't detect the difference between `auto` and `always` based on the current description. but i'm also having a hard time based on their behavior.

doc: ScrollArea - type=auto description correction

---

src/mantine-core/src/NumberInput/NumberInput.tsx

[@mantine/core] NumberInput : Fix readOnly prop is ignored (mantinedev#2955)

---

docs/src/docs/others/tiptap.mdx
src/mantine-tiptap/src/RichTextEditor.tsx
src/mantine-tiptap/src/controls/controls.tsx
src/mantine-tiptap/src/labels.ts

- change label from strike though to strikethrough in mantine tip tap editor

[@mantine/tiptap] Change label to Strikethrough in tiptap text editor

---

docs/src/components/PackagesInstallation/PackagesInstallation.tsx

I found some alignment issues inside the Table cell with Checkbox on the Getting Started guide page.

fix checkbox alignment in table cell

---

src/mantine-core/src/NumberInput/NumberInput.tsx

fixes Issue: https://github.com/mantinedev/mantine/issues/2847

[@mantine/core] NumberInput: Fix precision update

---

src/mantine-form/src/types.ts

[@mantine/form] Fix typing issue with nested interfaces when used with useForm.

---

src/mantine-demos/src/demos/theme/Theme.demo.primaryColor.tsx

[docs] Colors: Fix typo

---

docs/src/docs/guides/custom-components.mdx

Raised Issue: https://github.com/mantinedev/mantine/issues/3281

Invlaid types for Custom Component

---

src/mantine-core/src/Skeleton/Skeleton.styles.ts

[@mantine/core] Skeleton: Allow overflow when not visible

---

src/mantine-carousel/src/Carousel.tsx
src/mantine-demos/src/demos/carousel/Carousel.demo.vertical-rtl.tsx
src/mantine-demos/src/demos/carousel/index.ts

This fixes Carousel in `vertical` orientation with RTL direction

[@mantine/carousel] fix vertical orientation with rtl direction

---

docs/src/docs/others/modals.mdx
src/mantine-modals/src/ModalsProvider.tsx
src/mantine-modals/src/context.ts
src/mantine-modals/src/events.ts
src/mantine-modals/src/index.ts
src/mantine-modals/src/use-modals/use-modals.test.tsx

[@mantine/modals] Add typesafety for context modals

---

src/mantine-core/src/Text/Text.story.tsx
src/mantine-core/src/Text/Text.styles.ts
src/mantine-core/src/Text/Text.tsx

Implements `truncateStart` on `<Text />`  based on feature request: https://github.com/mantinedev/mantine/discussions/3549

[@mantine/core] Text truncateStart

---

src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts

[@mantine/Hooks] use-focus-trap: aria-hidden Fix

---

src/mantine-demos/src/demos/core/NumberInput/NumberInput.demo.formatter.tsx

[@mantine/Core] Updated NumberInput.demo.formatter.tsx

---

src/mantine-core/src/Table/Table.styles.ts

[@mantine/core] Table.styles.ts

---

docs/src/docs/pages/contributing.mdx

Hey hey! I did my best to make the Contributing page easier to read and understand with minor changes to existing sentences. Please let me know what you think.

[docs] Fix grammatical issues and improve language clarity in Contributing docs

---

src/mantine-demos/src/demos/core/TypographyStylesProvider/TypographyStylesProvider.demo.usage.tsx

[@mantine/demos] Fixed typo in with two repeated words.

---

docs/src/docs/core/Tooltip.mdx

Fix issue: https://github.com/mantinedev/mantine/issues/3656

[docs] Fix docs about transitionProps in Tooltip

---

docs/src/docs/changelog/6-0-0.mdx

Fixed https://github.com/mantinedev/mantine/issues/3651

[docs] Fixed link to form values documentation

---

src/mantine-core/src/Floating/FloatingArrow/get-arrow-position-styles.ts
src/mantine-core/src/Tooltip/Tooltip.story.tsx

Fix for https://github.com/mantinedev/mantine/issues/3572

[@mantine/core] Tooltip: fixed styles for Tooltip if border set for tooltip and arrow in styles

---

src/mantine-core/src/Title/Title.tsx

Fix help wanted bug 4 (Gradient title) in Discord.
https://discord.com/channels/854810300876062770/1048155338152624198/1081226402990403686

[@mantine/core] Title: Fix gradient title

---

src/mantine-notifications/src/Notifications/Notifications.tsx
src/mantine-notifications/src/events.ts

p1 of :
https://discord.com/channels/854810300876062770/1048155338152624198/1081226402990403686

[@mantine/notifications] Notifications: added static methods

---

src/mantine-core/src/AppShell/AppShell.styles.ts

Bug Report:
https://discord.com/channels/854810300876062770/1080883253101215807/1080885205423886449

[@mantine/core] App Shell: Fix for padding prop

---

src/mantine-core/src/JsonInput/JsonInput.test.tsx
src/mantine-core/src/JsonInput/JsonInput.tsx

Fixes #3763 and some other issues with the component. Also adds some tests.

Issue 3763 fix json input

---

src/mantine-core/src/Select/Select.tsx

Fixed https://github.com/mantinedev/mantine/issues/3770

[@mantine/core] Select: fixed shadow prop

---

src/mantine-demos/src/demos/core/Chip/Chip.demo.group.tsx

Fixed https://github.com/mantinedev/mantine/issues/3790

[docs] Chip: Fixed demo code

---

src/mantine-core/src/Pagination/PaginationEdges/PaginationEdges.styles.tsx
src/mantine-core/src/Pagination/PaginationEdges/PaginationEdges.tsx

Fixed https://github.com/mantinedev/mantine/issues/3758

[@mantine/core] Pagination: Fixed reversed pagination arrows in RTL

---

src/mantine-core/src/Accordion/AccordionControl/AccordionControl.styles.ts

This PR is a fix for [#3810 ](https://github.com/mantinedev/mantine/issues/3810)

[@mantine/core] Accordion: Fix to prevent characters from being cut off

---

docs/src/docs/others/tiptap.mdx

As per https://tiptap.dev/installation/react#2-install-the-dependencies

[@mantine/tiptap] Add @tiptap/pm

---

src/mantine-form/src/paths/set-path.ts

potential solution for the issue described in #3803

Use klona/full to clone form values.

---

src/mantine-dates/src/components/PickerInputBase/PickerInputBase.tsx

[@mantine/core] PickerInputBase: Fix DOM prop leak

---

src/mantine-core/src/Slider/Marks/Marks.tsx

[@mantine/core] Slider: Fix disable handling (#3835)

---

docs/src/docs/theming/functions.mdx
src/mantine-core/src/TypographyStylesProvider/TypographyStylesProvider.styles.ts
src/mantine-demos/src/demos/create-styles/CreateStyles.demo.basics.tsx
src/mantine-demos/src/demos/create-styles/CreateStyles.demo.media.tsx

Clarify mediaQuery usage, fix wrong cases

---

docs/src/docs/core/Drawer.mdx
docs/src/docs/core/Modal.mdx

I noticed a few broken links to https://www.w3.org/. This PR fixes them.

[docs] fixed broken w3.org links

---

docs/src/docs/dates/DatePicker.mdx

Fixes https://github.com/mantinedev/mantine/issues/3929

Fix broken link to DatesProvider

---

docs/src/docs/core/NumberInput.mdx
src/mantine-core/src/NumberInput/NumberInput.story.tsx
src/mantine-core/src/NumberInput/NumberInput.test.tsx
src/mantine-core/src/NumberInput/NumberInput.tsx
src/mantine-demos/src/demos/core/NumberInput/NumberInput.demo.decimalSeparator.tsx

[@mantine/core] NumberInput: Add `thousandsSeparator` #3988

---

src/mantine-dates/src/components/WeekdaysRow/get-weekdays-names/get-weekdays-names.test.ts
src/mantine-dates/src/components/WeekdaysRow/get-weekdays-names/get-weekdays-names.ts

[@mantine/dates] Fix weekday labeling #3779

---

src/mantine-dates/src/components/DateInput/DateInput.tsx

Fixes #3944. See DateInput Usage story.

[@mantine/dates] DateInput: Fix defaultDate

---

src/mantine-core/src/Modal/Modal.tsx
src/mantine-core/src/ModalBase/ModalBaseCloseButton/ModalBaseCloseButton.styles.ts

fix: wrong CloseButton position if no title provided

---

src/mantine-core/src/MultiSelect/DefaultValue/DefaultValue.styles.ts

resolve https://github.com/mantinedev/mantine/issues/3949

 [@mantine/core] MultiSelect: fixed maxWidth

---

docs/src/components/PackagesInstallation/data.ts

Fix for: https://github.com/mantinedev/mantine/issues/4036

[docs] Fix `@tabler/icons-react` package version

---

src/mantine-dates/src/hooks/use-dates-state/is-in-range/is-in-range.test.ts
src/mantine-dates/src/hooks/use-dates-state/is-in-range/is-in-range.ts
src/mantine-dates/src/hooks/use-dates-state/use-dates-state.ts

[@mantine/dates] useDatesState: Fix `isInRange` handling #4014

---

docs/src/docs/others/notifications.mdx
src/mantine-core/src/Notification/Notification.story.tsx
src/mantine-core/src/Notification/Notification.styles.ts
src/mantine-core/src/Notification/Notification.tsx
src/mantine-demos/src/demos/core/Notification/Notification.demo.configurator.tsx

The function is the same as in Paper

[@mantine/core] Notification: Add withBorder prop

---

src/mantine-core/src/Slider/Marks/Marks.styles.ts
src/mantine-core/src/Slider/Marks/Marks.tsx
src/mantine-core/src/Slider/Track/Track.styles.ts
src/mantine-styles-api/src/styles-api/Slider.styles-api.ts

As discussed in #4000, this fixes the width of Slider following marks behavior update

[@mantine/core] fix slider not respecting container width

---

src/mantine-core/src/Notification/Notification.styles.ts

Sorry, I forgot the old border because you can't really see it in dark mode

[@mantine/core] Notification: Remove border

---

src/mantine-core/src/MultiSelect/MultiSelect.styles.ts

[core] MultiSelect: use primaryShade in placeholder error color 

---

src/mantine-core/src/Popover/Popover.tsx

Fix `clickOutside` trigger condition.
For details：#4114 #4146

[@mantine/core]:Fix clickOutside trigger condition

---

src/mantine-core/src/Select/Select.tsx

[@mantine/core] Select: get scrollableRef in Safari

---

src/mantine-core/src/PinInput/PinInput.tsx

Fixes #4366 and improves handling of delete and left/right arrow keys.
Unfortunately I currently don't have time to add some tests so if you require them maybe someone else can do this or I need some days to integrate them.

[@mantine/core] PinInput: fix/improve keyboard handling

---

src/mantine-tiptap/src/controls/LinkControl/LinkControl.tsx

see  [this discussion](https://github.com/mantinedev/mantine/discussions/4370)

[@mantine/tiptap] LinkControl: add initialExternal to props

---

src/mantine-hooks/src/use-window-event/use-window-event.ts

Changed the generic type in the function to display hints

Update use-window-event.ts: Fixed types

---

src/mantine-spotlight/src/use-actions-state/use-actions-state.ts

[@mantine/spotlight] Speed up `Spotlight` for thousands of actions

---

src/mantine-core/src/Table/Table.styles.ts

[@mantine/core] Table: Fix column border selectors

---

src/mantine-core/src/MultiSelect/MultiSelect.tsx

Fixed #4484 similar to Select component

[@mantine/core] MultiSelect: handle portalProps

---

src/mantine-dates/src/components/DatePicker/DatePicker.tsx

[@mantine/dates] DatePicker : remove onMonthSelect from extract parameters

---

src/mantine-dates/src/components/DatePickerInput/DatePickerInput.story.tsx
src/mantine-dates/src/components/DatePickerInput/DatePickerInput.tsx

fix: props `defaultDate` in `DatePickerInput` not work.

fix: date picker input default date

---

src/mantine-demos/src/demos/core/TransferList/TransferList.demo.differentPlaceholders.tsx

If PR must be done on dev branch let me know.

Fix typo on TransferList.demo.differentPlaceholders.tsx

---

src/mantine-core/src/Popover/PopoverTarget/PopoverTarget.tsx
src/mantine-dates/src/components/PickerInputBase/PickerInputBase.tsx

This PR introduces a fix for this [open issue](https://github.com/mantinedev/mantine/issues/4616) https://github.com/mantinedev/mantine/issues/4616.

[@mantine/core] & [@mantine/dates] Fix: DatePickerInput, DateTimePicker label click does not focus input #4616

---

docs/src/components/HomePage/Banner/Banner.styles.ts
src/mantine-core/src/BackgroundImage/BackgroundImage.styles.ts
src/mantine-demos/src/demos/carousel/Carousel.demo.cards.tsx
src/mantine-demos/src/demos/carousel/_card.tsx

Fix Issue: https://github.com/mantinedev/mantine/issues/4713

[@mantine/core]: Add double quotes to wrap src for backgroundImage property

---

src/mantine-demos/src/demos/core/Select/Select.demo.itemComponent.tsx

There was an extra breakline in the data array.

[docs] Removed extra space in the data array

---

docs/pages/guides/redwood.mdx

Updates link for Redwood started guide

[docs] Update Redwood guide link

---

src/mantine-core/src/components/AppShell/AppShell.module.css

[@mantine/core] Fix AppShell.Main not taking up full height

---

src/mantine-hooks/src/use-debounced-state/use-debounced-state.ts

This PR resolves this issue https://github.com/mantinedev/mantine/issues/4568

[@mantine/hooks] Wrap useDebouncedState in usecallback

---

docs/pages/changelog/7-0-0.mdx

Add note about Drawer `target` prop

Add note for drawer target -> portal props

---

src/mantine-core/src/components/TagsInput/TagsInput.tsx

[@mantine/core] TagsInput: Call onOptionSubmit on enter key in input

---

src/mantine-core/src/components/ActionIcon/ActionIcon.module.css
src/mantine-core/src/components/Button/Button.module.css
src/mantine-core/src/components/Rating/RatingItem/RatingItem.tsx

Small style fix for the borders of the `ActionIcon.Group` component when using RTL.

[@mantine/core] ActionIcon.Group, Button.Group, Rating: Fix style for RTL

---

src/mantine-core/src/components/TagsInput/TagsInput.tsx

- fixes #4946
- It looks like the same problem can be solved with the following PR.
https://github.com/mantinedev/mantine/pull/1570
https://github.com/mantinedev/mantine/assets/105474635/d0a1566c-a629-4009-a836-4387d29c0f45
https://github.com/mantinedev/mantine/assets/105474635/54c44288-9ca5-4ead-a48f-c4dd0eafc988

[@mantine/core] TagsInput: fix IME #4946

---

docs/yarn.lock
src/mantine-hooks/src/use-timeout/use-timeout.test.ts
src/mantine-hooks/src/use-timeout/use-timeout.ts

[@mantine/hooks] useTimeout callback not running after state change

---

docs/pages/changelog/7-0-0.mdx

Fixes typo for component extend functions

[docs] Update 7-0-0.mdx typo

---

src/mantine-spotlight/src/spotlight.store.ts

Fixes #4988

---

docs/pages/styles/css-files-list.mdx

added /styles/ to documentation path.

[docs] add missing styles to CSS files list path

---

src/mantine-core/src/components/Rating/Rating.module.css

[docs] Fix rating overflow issue

---

src/mantine-core/src/components/Highlight/highlighter/highlighter.ts

[@mantine/core] Highlight: sort highlight options by longest first

---

docs/yarn.lock
src/mantine-hooks/src/use-local-storage/create-storage.ts

[@mantine/hooks]: Fix storage access error in create-storage

---

src/mantine-core/src/components/Transition/transitions.ts

Fixes #1657
See the storybook Tooltip > Demo: Transitions.

[@mantine/core] Fix `pop-top-*` transitions

---

docs/pages/others/carousel.mdx

Fixing the issue https://github.com/mantinedev/mantine/issues/5144

Denote needed embla version for carousel

---

src/mantine-form/src/tests/reset.test.ts
src/mantine-form/src/use-form.ts

[@mantine/form] Reset should set values to current initialValues

---

docs/pages/styles/styles-api.mdx

The documentation is already really good. I just tried to further improve it a little bit by, for example, adding articles here and there.

DOC: slightly improve language style in styles-api.mdx

---

docs/pages/styles/data-attributes.mdx

As mentioned in #5131, the docs are really good and probably only require a few more articles in some places.

DOC: slightly improve language style in data-attributes.mdx

---

docs/pages/core/select.mdx

as discussed here
https://discord.com/channels/854810300876062770/1172251915988508703

[@mantine/docs] Select: fix annotation for useState<string | null>("")

---

src/mantine-modals/src/events.ts

Updated typings for `modals` — fixes #5298

---

docs/pages/getting-started.mdx

We humbly submit this PR to add [a link to a Figma component library](https://www.figma.com/community/file/1294398524808646906/mantine-lean-ui-library-alley-corp-nord) that we have created.
It utilizes Figma’s Local Variables functionality to allow for easy and consistent customization.
These components follow the same variants and specifications as the Mantine documentation to allow a seamless workflow between design and engineering.
We decided to create it for our own needs as we love using Mantine in our development projects, then decided to open it up to the community.
We are starting to see some usage traction and last week we got our first comment that encourage us to push it forward.  
We are very open to comments, suggestions, and feedback.
And again, thanks a lot for the great …

[docs: Community Design files] Add AlleyCorp Nord figma library

---

docs/pages/form/validators.mdx

Disscussion: https://discordapp.com/channels/854810300876062770/1179962399286116484/1179962399286116484
fixed regexp for isEmail on docs

[@mantine/docs] fix isEmail regexp

---

packages/@mantine/core/src/components/Combobox/OptionsDropdown/OptionsDropdown.tsx

[@mantine/core] Select component breaks if user translates page using google translate

---

packages/@docs/demos/src/demos/tiptap/TipTap.demo.codeHighlight.tsx

- Updates the example to work with lowlight 3.x
- Fixes a typo

Update TipTap.demo.codeHighlight.tsx for lowlight 3.x

---

scripts/build/rollup/rollup-exclude-use-client.ts

[@mantine/vanilla-extract] Make themeToVars build time compatible

---

docs/src/pages/getting-started.mdx

https://github.com/microsoft/vscode/issues/165933

remove obsolete meta tag

---

packages/@mantine/core/src/components/Combobox/Combobox.types.ts

[@mantine/core] Combobox: add readonly to ComboboxData

---

packages/@mantine/core/src/components/Combobox/use-combobox-target-props/use-combobox-target-props.ts
packages/@mantine/spotlight/src/SpotlightSearch.tsx

If you meant to leave out the numpad key, please ignore this request. Thank you!

Feat : Support numpad enter key for selecting items in combobox and spotlight

---

packages/@mantine/core/src/components/Transition/transitions.ts

Transition: Fix skew-up transition is not working

---

packages/@mantine/core/src/components/Popover/Popover.tsx

**Description:**
docs: combobox props update
**Issue Details:**
fixes: #5727
**Changes:**
-   it could be true, false or undefined 
**Checklist:**

docs: combobox props update

---

docs/src/pages/hooks/use-list-state.mdx
packages/@mantine/hooks/src/use-list-state/use-list-state.test.ts
packages/@mantine/hooks/src/use-list-state/use-list-state.ts

https://github.com/orgs/mantinedev/discussions/5715

[@mantine/hooks]: Add swap handle

---

packages/@mantine/hooks/src/use-network/use-network.ts

[@mantine/hooks] Fixed initial value of the `online` attribute returned by `useNetwork()`

---

packages/@mantine/core/src/components/ScrollArea/ScrollArea.module.css

[@mantine/core] ScrollArea: fix horizontal offsetScrollbars

---

changelog/7.3.0.md

docs: fix Grid overflow default value in 7.3.0 changelog

---

packages/@mantine/charts/src/AreaChart/AreaChart.tsx
packages/@mantine/charts/src/BarChart/BarChart.tsx
packages/@mantine/charts/src/LineChart/LineChart.tsx

Fixes: https://github.com/mantinedev/mantine/issues/5915

[@mantine/charts] fix height of chart legend

---

packages/@mantine/carousel/src/Carousel.test.tsx
packages/@mantine/carousel/src/Carousel.tsx
packages/@mantine/carousel/src/CarouselSlide/CarouselSlide.test.tsx
packages/@mantine/carousel/src/CarouselSlide/CarouselSlide.tsx

Fixed displayName to appropriate one 
- `@mantine/core` -> `@mantine/carousel`

[@mantine/carousel] chore: fix displayname

---

packages/@mantine/hooks/src/use-local-storage/create-storage.ts

Reverts mantinedev/mantine#5910

Revert "useLocalStorage and useSessionStorage missing dependencies" #5910

---

apps/mantine.dev/src/pages/form/values.mdx

Small typo I discovered, thanks for the effort of maintaining this library, Mantine is awesome!

[mantine.dev] fix typo on form values page

---

packages/@mantine/core/src/components/Progress/Progress.tsx
packages/@mantine/core/src/components/Progress/ProgressSection/ProgressSection.tsx
packages/@mantine/dates/src/components/Day/Day.tsx
packages/@mantine/notifications/src/Notifications.tsx

Hey, thanks for the project. I've found a few typos while working with the library, so I think it is time to open a PR to fix them.

Fix multiple typos

---

packages/@mantine/core/src/components/Combobox/Combobox.story.tsx
packages/@mantine/core/src/components/Combobox/ComboboxFooter/ComboboxFooter.tsx
packages/@mantine/core/src/components/Combobox/ComboboxHeader/ComboboxHeader.tsx

[@mantine/core] fix combobox footer and header interactions 6335

---

packages/@mantine/core/src/components/ScrollArea/ScrollAreaScrollbar/Scrollbar.tsx

Fix scrollbar drag events

---

apps/mantine.dev/src/pages/form/schema-validation.mdx

Updated to valibot >= 0.31.0
https://github.com/Songkeys/mantine-form-valibot-resolver/pull/1

doc(form): update valitbot validator usage

---

packages/@mantine/hooks/src/use-os/use-os.test.ts
packages/@mantine/hooks/src/use-os/use-os.ts

Add `useOs` unit tests
Fixtures taken from [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent)

[@mantine/hooks]: use-os tests

---

packages/@mantine/emotion/src/create-styles.ts

Added back classes names from `createStyles` to work like Mantine 6.

[@mantine/emotion] Added back classes names to createStyles

---

packages/@mantine/spotlight/src/limit-actions.ts

[@mantine/spotlight] FIX #6620: spotlight limit prop

---

packages/@mantine/spotlight/src/index.ts

fixes: https://github.com/mantinedev/mantine/issues/6708

[@mantine/spotlight] fix: export `SpotlightRoot`

---

apps/mantine.dev/src/pages/form/actions.mdx

see: https://github.com/mantinedev/mantine/actions/runs/10606584449/job/29397600397?pr=6732

[docs] Fixed Ci Failing due to Prettier

---

packages/@mantine/core/src/components/Table/Table.module.css

fixes: https://github.com/mantinedev/mantine/issues/6857

[@mantine/core] fix: zindex of thead

---

packages/@mantine/core/src/components/MultiSelect/MultiSelect.tsx

[@mantine.core] chore: fix typo `whe`

---

apps/mantine.dev/src/pages/x/dropzone.mdx

thanx to: https://discord.com/channels/854810300876062770/861521000985264138/1286309119912968296

[mantine.dev] fix typo `sgv`

---

packages/@mantine/charts/src/ChartTooltip/ChartTooltip.tsx

[@mantine/chart] fix: exception when chart tooltip contains period

---

README.md
apps/help.mantine.dev/src/pages/q/roadmap.mdx
apps/mantine.dev/src/components/Footer/data.ts
apps/mantine.dev/src/pages/contribute.mdx
packages/@docs/demos/src/demos/core/HoverCard/HoverCard.demo.profile.tsx
packages/@docs/demos/src/demos/hooks/use-favicon.demo.usage.tsx
packages/@mantinex/mantine-meta/src/meta.ts

closes: https://github.com/mantinedev/mantine/issues/6752
I've also changed some patterns of `Twitter` into `X` in mantine.dev. I understand this isn't that important, so I'll leave it up to you to decide if you want to incorporate it.

[mantine.dev] update twitter to x

---

packages/@mantine/core/src/components/PinInput/PinInput.tsx

fixes: https://github.com/mantinedev/mantine/issues/6870

[@mantine/core] fix: disable `Backspace` if index of input is 0

---

packages/@mantine/dates/src/components/HiddenDatesInput/HiddenDatesInput.tsx

fixes: https://github.com/mantinedev/mantine/issues/6828

[@mantine/dates] fix: add timezone to hidden input

---

packages/@docs/demos/src/demos/charts/AreaChart/AreaChart.demo.pointLabels.tsx
packages/@docs/demos/src/demos/charts/CompositeChart/CompositeChart.demo.pointLabels.tsx

I've fixed some demo codes and demo component of charts in the docs :+1:

[mantine.dev] fix demos of Charts

---

packages/@docs/styles-api/src/data/Dates.styles-api.ts

just as the title. some description of styles api was incorrect.

[@mantine/dates] fix styles api description of level groups

---

changelog/7.13.0.md

fix from bug report: https://discord.com/channels/854810300876062770/1288433557915697184/1288433557915697184

[mantine.dev] fix typo at 7.13 changelog

---

apps/mantine.dev/src/mdx/data/mdx-charts-data.ts
apps/mantine.dev/src/mdx/mdx-pages-group.ts
apps/mantine.dev/src/pages/charts/funnel-chart.mdx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.color.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.noTooltip.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.size.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.story.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.strokeColor.module.css
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.strokeColor.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.strokeWidth.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.tooltipDataSource.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.usage.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.withLabels.tsx
packages/@docs/demos/src/demos/charts/FunnelChart/_data.ts
packages/@docs/demos/src/demos/charts/FunnelChart/index.ts
packages/@docs/demos/src/index.ts
packages/@docs/styles-api/src/data/FunnelChart.styles-api.ts
packages/@docs/styles-api/src/index.ts
packages/@mantine/charts/src/FunnelChart/FunnelChart.module.css
packages/@mantine/charts/src/FunnelChart/FunnelChart.story.tsx
packages/@mantine/charts/src/FunnelChart/FunnelChart.test.tsx
packages/@mantine/charts/src/FunnelChart/FunnelChart.tsx
packages/@mantine/charts/src/FunnelChart/index.ts
packages/@mantine/charts/src/index.ts

@rtivital 
As we discussed before, I have created a Funnel Chart for the next minor release on my end. The change diffs are a bit much, but I would be happy to have them reviewed!

[@mantine/chart] feat: add FunnelChart

---

packages/@mantine/hooks/src/use-fullscreen/use-fullscreen.ts

Sometimes we need to change the ref value with another element

feat: allow useFullscreen to update the event listener when ref changes

---

packages/@mantine/core/src/components/Slider/Slider.module.css

fixes: https://github.com/mantinedev/mantine/issues/6877

[@mantine/core] fix: Mark of Slider is slightly right

---

packages/@mantine/hooks/src/use-in-viewport/use-in-viewport.ts

Fixes https://github.com/mantinedev/mantine/issues/6812

Fix use-in-viewport when ref changes

---

packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.tsx

fixes: https://github.com/mantinedev/mantine/issues/7006

[@mantine/dates] fix: close DatePickerInput when disabled

---

packages/@mantine/form/src/index.ts

Export type FormValidateInput from "@mantine/form"

---

packages/@mantine/charts/src/BarChart/BarChart.tsx

added a function that determines "dx" and "dy" parameters of the bar label

---

packages/@mantine/core/src/components/NumberInput/NumberInput.tsx

Fix number input NaN issue

---

scripts/build/rollup/create-package-config.ts

Fixes https://github.com/mantinedev/mantine/issues/7186.

[@mantine/core] Fixing source map generation

---

packages/@mantine/tiptap/src/RichTextEditor.module.css

Remove paragraph inline-block

---

packages/@mantine/core/src/components/ScrollArea/ScrollAreaThumb/ScrollAreaThumb.tsx

[@mantine/core] Fix scrollbar visibility on initial scroll

---

packages/@mantine/core/src/components/TypographyStylesProvider/TypographyStylesProvider.module.css

[@mantine/core] Restrict unexpected margin removal in TypographyStylesProvider

---

packages/@mantine/core/src/components/TypographyStylesProvider/TypographyStylesProvider.module.css

Reverts mantinedev/mantine#7290
Fixes #7333

[@mantine/core] TypographyStylesProvider: Fix incorrect top and bottom margins of first and last elements

---

changelog/7.16.0.md
packages/@docs/demos/src/demos/core/Pagination/Pagination.demo.withPages.tsx

withPages prop is missing in the demo code for the Pagination component as well as the version 7.16 changelog

Add missing 'withPages' prop to Pagination examples

---

packages/@mantine/charts/src/AreaChart/AreaChart.tsx

[@mantine/chart] AreaChart : fix console error

---

packages/@docs/demos/src/demos/form/Form.demo.nested.tsx

"I accepts terms & conditions" > "I accept terms and conditions"

Fix typo in Form.demo.nested.tsx

---

packages/@mantine/dates/src/components/MonthPicker/MonthPicker.tsx
packages/@mantine/dates/src/hooks/use-dates-state/use-dates-state.ts

[@mantine/dates] MonthPicker: improve set picked date update logic

---

package.json
packages/@mantine/emotion/src/create-styles.ts

fix: broken "go to definition" for `createStyles().classes` object

---

packages/@mantine/hooks/src/use-hotkeys/parse-hotkey.test.ts
packages/@mantine/hooks/src/use-hotkeys/parse-hotkey.ts
packages/@mantine/hooks/src/use-hotkeys/use-hotkeys.test.tsx

Fix useHotKeys matching physical key codes when usePhysicalKeys unset

---

packages/@mantine/core/src/components/AngleSlider/AngleSlider.tsx

This pull request refactors the keyboard interaction logic for the `[Mantine] AngleSlider` component. Additionally, it introduces support for restricting slider positions to predefined marks.
1. Refactored keyboard interaction logic to improve responsiveness and maintainability.
2. Added support for restricting slider movements to defined marks.

Refactor AngleSlider keyboard interactions and add mark restrictions

---

apps/mantine.dev/src/components/HomePage/HomePageComponents/HomePageComponents.tsx

Thank you for this amazing library. I found a minor typo in the landing page.

Fix typo in landing page

---

packages/@mantine/dates/src/components/TimePicker/TimePicker.test.tsx
packages/@mantine/dates/src/components/TimePicker/use-time-picker.ts

[@mantine/dates] TimePicker min max fix

---

packages/@mantine/hooks/src/use-move/use-move.ts

This PR fixes the React 18 callback ref warning that occurs when using the Slider component in development mode.
- Modified `useMove` hook to store cleanup function in a ref instead of returning it from the callback
- Prevents "Unexpected return value from a callback ref" warning in React 18
- Maintains compatibility with both React 18 and React 19
- Resolves console warnings in Slider component during development
- Tested with React 18 and React 19
- No more console warnings in development mode
- Slider functionality remains unchanged
- Memory leaks prevented through proper cleanup
Fixes #7993
- Bug fix (non-breaking change which fixes an issue)  #7993

fix(hooks): resolve React 18 callback ref warning in useMove hook

---

apps/mantine.dev/src/pages/x/carousel.mdx

Small wording improvements in carousel docs.

[mantine.dev] Wording improvement in carousel docs
