- src/mantine-hooks/src/use-click-outside/use-click-outside.ts
> [@mantine/hooks] use-click-outside: Prevent extra invocations of handler if both events fire

- src/mantine-hooks/src/use-local-storage-value/use-local-storage-value.story.tsx
- src/mantine-hooks/src/use-local-storage-value/use-local-storage-value.ts
This change immediately sets `defaultValue` to localStorage if provided.
> Update useLocalStorageValue to return defaultValue

- src/mantine-core/src/Select/Select.tsx
I haven't tested this - I am editing from the GitHub GUI not from my VSCode.
However this could have a clash if for some reason the user wanted to use `xx-placeholder-xx` as a value, however unlikely that is.
Not sure what the best solution would be.
> Select - Possible Simple Fix to Placeholder/defaultValue

- .gitattributes
Force LF on text files for windows with autocrlf=true. This avoids having issues with lint requiring LF endings. 
Note that for the change to take place people on windows will need to save their changes and rebuild the repository:
**Running commands below remove all local changes**
```
git rm --cached -r . 
git reset --hard
```
> fix checkout on windows

- docs/src/docs/hooks/use-uncontrolled.mdx
- src/mantine-core/src/components/Select/Select.story.tsx
- src/mantine-core/src/components/Select/Select.tsx
- src/mantine-hooks/src/use-uncontrolled/use-uncontrolled.story.tsx
- src/mantine-hooks/src/use-uncontrolled/use-uncontrolled.test.ts
- src/mantine-hooks/src/use-uncontrolled/use-uncontrolled.ts
Fixes https://github.com/mantinedev/mantine/issues/154
This has turned out to be bit more complex than originally anticipated because Select has own state as well that needs to be handled, however I believe I have succeeded.
The behavior should be backwards compatible.
I'm not certain what the expectations of `onValueUpdate?(value: T): void;` are since it isn't used anywhere and I fail to see possible use cases, however I tried to keep the behavior same.
The hook now returns third value "mode" that indicates whether it's controlled or uncontrolled currently.
> use-controlled - fix controlled input behavior

- src/mantine-core/src/components/Highlight/Highlight.story.tsx
- src/mantine-core/src/components/Highlight/Highlight.test.tsx
- src/mantine-core/src/components/Highlight/Highlight.tsx
Attempts to resolve: #143 
Current issues, the search is forward only, so an input of `world\,Hello` would result in 'Hello `world`' (only world being highlighted.
it might be better to use regex for this?
Syntax for multiple is currently `\,` however this can be easily changed.
> feat: add ability for multiple highlights

- docs/src/components/Layout/Navbar/NavbarDocsCategory/NavbarDocsCategory.tsx
- docs/src/docs/core/Tabs.mdx
- docs/src/docs/hooks/use-window-scroll.mdx
- eslint/package.json
- package.json
- src/mantine-core/package.json
- src/mantine-core/src/components/Input/Input.story.tsx
- src/mantine-core/src/components/Input/Input.styles.ts
- src/mantine-core/src/components/Input/Input.test.tsx
- src/mantine-core/src/components/Input/Input.tsx
- src/mantine-core/src/components/Input/styles.api.ts
- src/mantine-core/src/components/Select/Select.story.tsx
- src/mantine-core/src/components/Select/Select.tsx
- src/mantine-core/src/components/Tabs/TabControl/TabControl.styles.ts
- src/mantine-core/src/components/Tabs/TabControl/TabControl.tsx
- src/mantine-core/src/components/Tabs/Tabs.story.tsx
- src/mantine-core/src/components/Tabs/Tabs.styles.ts
- src/mantine-core/src/components/Tabs/Tabs.test.tsx
- src/mantine-core/src/components/Tabs/Tabs.tsx
- src/mantine-core/src/components/Tabs/demos/colorsConfigurator.tsx
- src/mantine-dates/package.json
- src/mantine-hooks/README.md
- src/mantine-hooks/package.json
- src/mantine-notifications/package.json
- src/mantine-prism/package.json
- src/mantine-tag-picker/package.json
- src/mantine-tests/package.json
Implementing the item found here: https://trello.com/c/zZYcbrU4/8-mantine-core-tabs-add-vertical-orientation-support
> [@mantine/core] Tabs: add support for `orientation` prop

- src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts
The typed return value of useFocusTrap has been updated to be consistent with the signature in the `setRef` callback.
> Fix useFocusTrap callback signature

- docs/src/demos/hooks/use-cookie.tsx
- docs/src/demos/index.ts
- docs/src/docs/hooks/use-cookie.mdx
- src/mantine-hooks/README.md
- src/mantine-hooks/src/index.ts
- src/mantine-hooks/src/use-cookie/use-cookie.test.ts
- src/mantine-hooks/src/use-cookie/use-cookie.ts
Followed the given signature except the user has to use the cookie.current for accessing the value.
``` 
const [cookie, setCookie] = useCookie('cookie-name');
cookie; // -> current cookie value
setCookie('my-cookie-value'); // -> sets cookie value
```
Used a useRef for persistence and `setCookie` accepts a callback using which user can use for further customisation.
> useCookie hook implementation.

- src/mantine-core/src/components/Autocomplete/Autocomplete.story.tsx
- src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
- src/mantine-core/src/components/Select/Select.story.tsx
- src/mantine-core/src/components/Select/Select.tsx
Update to allow data prop to be string for both Autocomplete and Select.
This works by mapping over the `data` and formatting correctly and ensuring all future references to data refer to the `formattedData` variable.
Included storybook for both components.
Needed to create a new Type for the data prop as there were warnings suggesting that `item.value` doesn't exist on a `string`.
> Autocomplete and Select allow strings

- docs/src/demos/hooks/use-fullscreen.tsx
- docs/src/demos/index.ts
- docs/src/docs/hooks/use-fullscreen.mdx
- src/mantine-hooks/src/index.ts
- src/mantine-hooks/src/use-fullscreen/use-fullscreen.ts
Adds the use-fullscreen hook.
Attempts to ensure cross browser compatibility and offer a simple to use elementRef for custom root
> [@mantine/hooks] use-fullscreen: add hook

- src/mantine-hooks/src/use-cookie/use-cookie.ts
Noticed that build failed for SSR Gatsby. This small change fixes it.
> [@mantine/hooks] use-cookie: fix document not available in ssr

- docs/src/components/HomePage/Explore/demos/Hooks.tsx
- docs/src/demos/hooks/use-scroll-lock.tsx
- docs/src/docs/hooks/use-scroll-lock.mdx
- src/mantine-hooks/src/use-scroll-lock/use-scroll-lock.story.tsx
- src/mantine-hooks/src/use-scroll-lock/use-scroll-lock.test.ts
- src/mantine-hooks/src/use-scroll-lock/use-scroll-lock.ts
Migrate to internal state handling.
Changed the API to maintain custom init state handling, please let me know if the naming and API is as intended or not.
Once I know what the API looks like I will update the docs accordingly
> [@mantine/hooks] use-scroll-lock: migrate to internal state

- docs/src/docs/core/TextInput.mdx
- src/mantine-core/src/components/TextInput/demos/index.ts
- src/mantine-core/src/components/TextInput/demos/rightSection.tsx
Adds an example of using `rightSection` to the `TextInput` page. This was one I had to figure out myself so perhaps useful for future visitors. Let me know if you want to change the text.
> [docs] Adds rightSection example for TextInput

- src/mantine-dates/src/components/DatePickerBase/DatePickerBase.tsx
If the DatePicker is used inside a Modal, the DatePicker popover appears behind the Modal, since the zIndex prop of the Popper Component which is used for the DatePicker popover is set to 3.
Added zIndex property to DatePickerBase which allows you to modify the z-index attribute of the Popper component. 
The default value is still set to 3.
I don't know if "zIndex" is the correct property name in this case, since it's only for the Popper component and not the DatePicker component itself.
> Added zIndex prop to DatePickerBase

- src/mantine-core/src/components/MultiSelect/MultiSelect.tsx
Fixes Issue #203 for Multiselect component.
Didn't attach a new onClick handler for input element as it was creating event propagation issues with the parent div.
> Issue #203 fix for Multiselect Component

- src/mantine-core/src/components/ActionIcon/ActionIcon.story.tsx
- src/mantine-core/src/components/ActionIcon/ActionIcon.styles.ts
- src/mantine-core/src/components/ActionIcon/ActionIcon.tsx
- src/mantine-core/src/components/ActionIcon/demos/configurator.tsx
I might have over-simplified how I inject the `Loader` in place of the Icon when in loading state but seems to work fine in the stories.
> Enable `loading` state for ActionIcon

- src/mantine-dates/src/components/TimeRangeInput/demos/usage.tsx
I was checking the new components and noticed this demo was previewing `withSeconds` when it wasn't supposed to.
> Updated demo and removed `withSeconds` prop

- src/mantine-core/src/components/MultiSelect/MultiSelect.tsx
This PR fixes the following -
- prevent from clearing when disabled
- when all items are selected, removing the last item doesn't open the drop down
- removing items shouldn't close the dropdown but just open it.
> [@mantine/core] MultiSelect - fix dropdown and clearable issues

- docs/src/demos/hooks/use-idle.tsx
- docs/src/docs/hooks/use-idle.mdx
- src/mantine-hooks/src/use-idle/use-idle.ts
It would useful to be able to set the initialState of `useIdle` (which currently defaults to true).
Currently the following code logs you out the moment you render the component:
```
// ...
const shouldLogout = useIdle(logoutSeconds * 1000);
useEffect(() => {
if (shouldLogout) {
logout();
}
}, [logout, shouldLogout]);
// ...
```
With this PR you will be able to set the initial idle state so that it doesn't start off rendering as idle:
```
// ...
const shouldLogout = useIdle(logoutSeconds * 1000, { initialState: false });
useEffect(() => {
if (shouldLogout) {
logout();
}
}, [logout, shouldLogout]);
// ...
```
The cleanest way to implement this interface is to move everything after the timeout into an options prop, but unfortunately that is a breaking change so I am open to other ideas.
> [@mantine/hooks] use-idle: Add initialState option to use-idle hook

- docs/src/docs/core/Popper.mdx
- src/mantine-core/src/components/Autocomplete/Autocomplete.story.tsx
- src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
- src/mantine-core/src/components/ColorInput/ColorInput.story.tsx
- src/mantine-core/src/components/ColorInput/ColorInput.tsx
- src/mantine-core/src/components/Menu/Menu.story.tsx
- src/mantine-core/src/components/Menu/Menu.tsx
- src/mantine-core/src/components/MultiSelect/MultiSelect.story.tsx
- src/mantine-core/src/components/MultiSelect/MultiSelect.tsx
- src/mantine-core/src/components/Popover/Popover.story.tsx
- src/mantine-core/src/components/Popover/Popover.tsx
- src/mantine-core/src/components/Popper/Popper.tsx
- src/mantine-core/src/components/Popper/PopperContainer/PopperContainer.test.tsx
- src/mantine-core/src/components/Popper/PopperContainer/PopperContainer.tsx
- src/mantine-core/src/components/Select/Select.story.tsx
- src/mantine-core/src/components/Select/Select.tsx
- src/mantine-core/src/components/Select/SelectDropdown/SelectDropdown.tsx
- src/mantine-core/src/components/Tooltip/Tooltip.story.tsx
- src/mantine-core/src/components/Tooltip/Tooltip.tsx
- src/mantine-dates/src/components/DatePicker/DatePicker.story.tsx
- src/mantine-dates/src/components/DatePicker/DatePicker.tsx
- src/mantine-dates/src/components/DatePickerBase/DatePickerBase.tsx
- src/mantine-dates/src/components/DateRangePicker/DateRangePicker.story.tsx
- src/mantine-dates/src/components/DateRangePicker/DateRangePicker.tsx
This MR follows up the conversation #435, and enables Popper and all Popper-related components to be used without Portals, through an opt-out prop `withinPortal` which defaults to `true`.
I've added a `Without Portal` story to all related components Storybook, and added a section about Portal in the `Popper` documentation.
Tell me if anything is missing or if you see anything wrong in my implementation 👍
> Feature: Popper without Portal

- src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
- src/mantine-core/src/components/MultiSelect/MultiSelect.tsx
- src/mantine-core/src/components/Select/Select.tsx
- src/mantine-core/src/components/Select/SelectDropdown/SelectDropdown.tsx
- src/mantine-core/src/components/Select/stories/Select.story.tsx
Implement a `switchDirectionOnFlip` prop for Select, MultiSelect and Autocomplete, allowing to opt out of direction switching.
It simply disables the `onDirectionSwitch` callback, effectively freezing the state into the default direction.
> [@mantine/core] Make direction switch optional on Select

- docs/src/demos/hooks/use-page-leave.tsx
- docs/src/demos/index.ts
- docs/src/docs/hooks/use-page-leave.mdx
- src/mantine-hooks/src/index.ts
- src/mantine-hooks/src/use-page-leave/use-page-leave.ts
as potential improvement and extendable future we can:
return a boolean variable that indicates if mouse is out of page. 
accept `onReturn` function callback - left a comment with similar implementation
> [@mantine/hooks] use-page-leave

- src/mantine-core/src/components/Drawer/Drawer.tsx
the default z-index of Drawer should be `getDefaultZIndex('modal')` rather than `1000`
issue here #481
> [@mantine/core] Drawer: fix Drawer z-index

- docs/src/docs/core/MultiSelect.mdx
The docs for MultiSelect referenced labelComponent, which is wrong. It should be valueComponent.
> Docs typo fix on MultiSelect page

- src/mantine-styles/src/theme/GlobalStyles.tsx
Just noticed that the invalid property `fontSizes` was being added to the css of the document's `body` element when using `GlobalStyles`. I believe this is intended to be `fontSize` instead.
> Fix typo in `GlobalStyles` fontSize property

- src/mantine-core/src/components/TransferList/RenderList/RenderList.tsx
- src/mantine-core/src/components/TransferList/TransferList.tsx
This PR proposes to add a `showSearch` prop to the `TransferList` component, which controls whether you want to show the search feature of `TransferList`. The motivation is that you may not need a search functionality all the time and a configuration option to turn it off is always nice. The default value for this prop is `true` for backwards compatibility.
> [@mantine/core] TransferList: Add the `showSearch` prop.

- docs/src/docs/core/RingProgress.mdx
- src/mantine-core/src/components/RingProgress/Curve/Curve.tsx
- src/mantine-core/src/components/RingProgress/RingProgress.tsx
- src/mantine-core/src/components/RingProgress/demos/configurator.tsx
- src/mantine-core/src/components/RingProgress/get-curves/get-curves.test.ts
- src/mantine-core/src/components/RingProgress/get-curves/get-curves.ts
This PR incorporates the `capIsRound` prop on RingProgress, which adds rounded corners appropriately to the circles that compose the component. Closes #397 if merged
Screenshot of the feature in action:
> [@mantine/core] RingProgress: Add the `capIsRound` prop

- src/mantine-core/src/components/Alert/Alert.styles.ts
- src/mantine-core/src/components/Alert/Alert.tsx
This PR adds the `radius` prop to `Alert` components. This can either be a `MantineNumberSize` or a `number` (which will then set the `border-radius` to that px value). The default value of this is `'sm'` to maintain backwards compatibility.
Fixes #528
> [@mantine/core] Alert: Add the `radius` prop.

- src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
- src/mantine-core/src/components/NumberInput/NumberInput.tsx
- src/mantine-core/src/components/NumberInput/demos/step.tsx
- src/mantine-core/src/components/NumberInput/stories/NumberInput.story.tsx
Add the ability to automatically increment the value of an InputNumber, by clicking and holding the step arrow buttons.
If either `stepIncrementInterval` or `stepIncrementInitialDelay` are not supplied, then the current functionality is retained and there is not any automatic incrementing.
#525 specifically asks for exponential increase, but I think that a single delay value in milliseconds handles most use cases without much complexity.
If providing something other than a single delay value is required, then I think the type for `stepIncrementInterval` should change and the prop can be a function to calculate the rate.  The type would change from `stepIncrementInterval?: number` to `stepIncrementInterval?: number | (count: number) => number` where count is the current increment count and …
> [@mantine/core] InputNumber: Add props to increment values on holding step arrows

- src/mantine-core/src/components/TransferList/RenderList/RenderList.tsx
- src/mantine-core/src/components/TransferList/TransferList.tsx
This PR adds the `hideTransferAll` prop, which controls whether the Transfer All buttons (`<<` && `>>`) get's shown. The default value for this prop is false to retain backwards compatibility.
Addresses #544
> [@mantine/core] TransferList: Add the `showTransferAll` prop.

- docs/src/demos/hooks/use-resize-observer.tsx
The resize handle is not located on the bottom left corner, but on the right.
Location on Firefox:
Location on Chrome:
Location on Edge:
> [docs] Change resize handle location from left to right

- src/mantine-core/src/components/Skeleton/Skeleton.styles.ts
- src/mantine-core/src/components/Skeleton/Skeleton.tsx
This commit proposes to add a `showAnimation` prop to the `Skeleton` component. This can be used to disable skeleton animation. It's default value is `true` to maintain backwards compatibility.
References:
-------------
1. https://mui.com/api/skeleton/
2. https://ant.design/components/skeleton/#API
> [@mantine/core] Skeleton: Add the `showAnimation` prop.

- src/mantine-core/src/components/MultiSelect/stories/MultiSelect.story.tsx
- src/mantine-core/src/components/Select/Select.tsx
- src/mantine-core/src/components/Select/stories/Select.story.tsx
Hello!
This PR fixes the fact that Select's input does not re-render if the label of the selected item changes in the `data` array.
I did not have to change MultiSelect which didn't have the issue. I added a story for both Select and MultiSelect to see it in action.
> [@mantine/core] Make Select re-render the input on label change

- src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
Replace the timers and promises with jest mocking, so the results are more reliable.  The timeouts and intervals are controlled directly, instead of waiting for time to pass.
FYI @ jerebtw since you pointed the original issue out.
Fixes #562.
> Use jest timer mocking for numberinput tests

- src/mantine-core/src/components/Modal/Modal.tsx
This PR adds the `closeOnEscape` prop for `Modal` to enable closing when <kbd>escape</kbd> is pressed. I have mostly adapted the code from 
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Drawer/Drawer.tsx#L136-L149 
over to `Modal`, so hopefully it's okay. It appears to work correctly at any rate.
Fixes #588
> [@mantine/core] Modal: Add the `closeOnEscape` prop.

- src/mantine-core/src/components/Progress/Progress.styles.ts
Before this PR:
After this PR:
> [@mantine/core] Progress: Fix label overflow

- src/mantine-modals/src/ModalsProvider.tsx
This PR fixes https://github.com/mantinedev/mantine/issues/592
> [@mantine/modals] Fix onClose callback not called in closeAll function

- docs/src/docs/core/Switch.mdx
- src/mantine-core/src/components/Switch/Switch.styles.ts
- src/mantine-core/src/components/Switch/Switch.tsx
- src/mantine-core/src/components/Switch/demos/configurator.tsx
- src/mantine-core/src/components/Switch/demos/index.ts
- src/mantine-core/src/components/Switch/demos/labels.tsx
This PR adds the `onLabel` & `offLabel` props to control the text that gets shown in a `Switch` component in the checked/unchecked state respectively.
> [@mantine/core] Switch: Add the `(on|off)Label` props.

- docs/src/demos/hooks/use-element-size.tsx
- docs/src/demos/index.ts
- docs/src/docs/hooks/use-element-size.mdx
- src/mantine-hooks/src/index.ts
- src/mantine-hooks/src/use-element-size/use-element-size.ts
This PR implements the simpler use-element-size hook.
> [@mantine/hooks] use-element-size: init hook

- docs/src/docs/core/Select.mdx
- src/mantine-core/src/components/Select/Select.tsx
- src/mantine-core/src/components/Select/demos/deselectable.tsx
- src/mantine-core/src/components/Select/demos/index.ts
- src/mantine-core/src/components/Select/stories/Select.story.tsx
This PR adds `allowDeselect` prop to Select component.
Features - 
- add deselectable feature.
- making sure the dropdown doesn't close on deselecting
> [@mantine/core] Select: allowDeselect prop

- src/mantine-core/src/components/Alert/Alert.styles.ts
- src/mantine-core/src/components/Alert/Alert.tsx
- src/mantine-core/src/components/Alert/demos/configurator.tsx
- src/mantine-core/src/components/Alert/styles.api.ts
This PR proposes to add an `outline` prop to the `Alert` component to show an outline instead of filling the Alert container with the chosen color.
Reference: https://mui.com/components/alert/#outlined
> [@mantine/core] Alert: Add a `variant` prop.

- src/mantine-core/src/components/TransferList/RenderList/RenderList.styles.ts
Reported by user **David** on discord. https://discord.com/channels/854810300876062770/861521000985264138/927839935690604604
This PR fixes a situation where the border radius of the input search and action icons were interfering with the overall border radius of the transfer list body.
So the top left & right border radii of input & icons needs to match that of the body for the radii to be uniform.
> [@mantine/core] TransferList: Fix border issues.

- src/mantine-core/src/components/Accordion/Accordion.tsx
- src/mantine-core/src/components/Accordion/AccordionItem/AccordionItem.tsx
- src/mantine-core/src/components/Accordion/stories/Accordion.story.tsx
As discussed on Discord, allow setting the level for Accordion Item headings.
It still defaults to three, in order not to be breaking.
> [@mantine/core] Make Accordion heading-level customizable

- src/mantine-core/src/components/AppShell/AppShell.styles.ts
Before applying `100vw`:
After applying `100vw` (also had to add a div with `margin-right: 16px`, but at least it works here):
Can also consider adding `height: 100vh`, but I'm not an expert at CSS and don't want to fix something that doesn't seem broken.
> [@mantine/core] AppShell: Fix responsive layout bug

- docs/src/docs/core/AppShell.mdx
Due to how the `AppShell` component is architected, I've noticed that if you are setting a `height` on a `Header` component or a `width` on a `Navbar` component, you need to explicitly set it on the wrapped component, otherwise the layout breaks. It's not enough to just do `{...remainingProps}`
> [@mantine/core] AppShell: Update docs about wrapped components

- src/mantine-core/src/components/Divider/demos/labels.tsx
Before this PR:
After this PR:
> [@mantine/core] Divider: Fixed labels demo when `RTL` is enabled

- docs/src/docs/core/Box.mdx
Fixed a wrong link :shaved_ice:
> [docs] Fix incorrect link in Box docs

- docs/src/docs/core/AppShell.mdx
Hello,
Since your `CustomHeader` and `CustomNavbar` contains it's own children that's not passed as an argument when using in the example, we need to change the props type to remove the children. We could also make the `children` as an optional argument inside `NavbarProps` or `HeaderProps`, but that's probably not the best idea.
> [docs] Fix props type in `CustomNavbar` and `CustomHeader` examples

- docs/src/docs/theming/dark-theme.mdx
Hello,
This fix an example where `useHotKeys` is used but `useWindowEvent` is imported.
> [docs] Fix incorrect import in Dark theme docs

- src/mantine-styles/src/theme/types/MantineTheme.ts
This small change improves the TS type for `MantineTheme['colors']`. This should have two major improvements:
1. Autocomplete on the `colors` property should work now
```ts
const theme = useMantineTheme()
theme.colors. // This should now autocomplete showing all the default Mantine colors
const useStyles = createStyles(theme => ({
root: {
color: theme.colors. // This should now autocomplete showing all the default Mantine colors
}
})
```
2. TS users will now be able to overwrite the `MantineColor` type to include their custom color names, like so:
```ts
// ./types.ts
declare module "@mantine/core" {
export type MantineColor = "myColorName"
}
// or extend
import { MantineColor } from '@mantine/core'
declare module "@mantine/core" {
export type MantineColor =  MantineColor | "myColorName"
} …
```
> [@mantine/styles] Improve MantineTheme['colors'] TS type

- src/mantine-styles/src/theme/types/index.ts
A type needs to exist in the `@mantine/core` package to be able to be overwritten as shown in the docs
> [@mantine/styles] Export MantineThemeOther from package

- docs/src/docs/theming/extend-theme.mdx
I recently added this section as part of a PR to improve TS support. With those changes being released in `3.6.3` I tried to set it up in our project but found that it doesn't quite work as expected. 
I have not been able to find a solution, as locally I can only get it to work when changing the `node_modules/MantineTheme.d.ts` to import `MantineColor` from `@mantine/core` rather than `./MantineColor`. Obviously this is not possible to do within the actual monorepo as it only gets re-exported on build. 
I tried overwriting `@mantine/styles` using the solution described in these docs, but that doesn't help either. 
The code itself is fine, and does still improve TS support for standard colors, just the overwriting is not currently possible.
> [docs] Removed "extend theme" TS section

- src/mantine-core/src/components/Avatar/Avatar.tsx
This PR introduces the `imageProps` prop on the `Avatar` component. This allows to pass custom properties to the underlying `img` tag. Here's an example:
```jsx
<Avatar src="example.com/profile-picture.png" referrerPolicy="no-referrer" />
```
> [@mantine/core] Avatar: Add imageProps

- docs/src/docs/hooks/use-form.mdx
Update a code example link after mantine/demos migration
> [docs] Fix AuthenticationForm path in use-form documentation

- src/mantine-dates/src/components/TimeInput/TimeInput.test.tsx
- src/mantine-dates/src/components/TimeInput/TimeInput.tsx
- src/mantine-dates/src/components/TimeInputBase/AmPmInput/AmPmInput.tsx
- src/mantine-dates/src/components/TimeInputBase/TimeField/TimeField.tsx
- src/mantine-dates/src/components/TimeInputBase/create-amPm-handler/create-amPm-handler.tsx
- src/mantine-dates/src/components/TimeInputBase/create-time-handler/create-time-handler.ts
- src/mantine-dates/src/components/TimeInputBase/get-date/get-date.test.ts
- src/mantine-dates/src/components/TimeInputBase/get-date/get-date.ts
- src/mantine-dates/src/components/TimeInputBase/get-time-values/get-time-value.ts
- src/mantine-dates/src/components/TimeInputBase/get-time-values/get-time-values.test.ts
- src/mantine-dates/src/components/TimeRangeInput/TimeRangeInput.tsx
- src/mantine-demos/src/demos/packages/TimeInput/configurator.tsx
- 12-hour times are displayed from 01-12 instead of 00-11
- Fixed bug with advancing to next field when entering 00, 01, etc.
- Fixed missing onUpdate calls in certain scenarios
- Add format and clearable to TimeInput configurator
- Fix value prop not overriding TimeInput and TimeRangeInput internal state
- Change TimeRangeInput to use 2 TimeInput fields
- onChange can be called with null to indicate cleared state
> [@mantine/dates] Improvements for time inputs

- src/mantine-core/src/components/NumberInput/NumberInput.tsx
These changes add `inputMode` to [NumberInput](https://mantine.dev/core/number-input/) component. 
If `step` and `precision` properties are set, `inputMode` is set to 'decimal' and on mobile devices, a keyboard looks like:
Without properties  `step` and `precision` `inputMode` is set to 'decimal' and keyboard looks like:
> [@mantine/core] Added inputMode for NumberInput

- src/mantine-core/src/components/Select/Select.tsx
Will only fire the `onDropdownOpen/onDropdownClose` callback if the value actually changes.
Resolves #854
> [@mantine/core] Select: only use open/close callback when value changes

- src/mantine-dates/src/components/DateRangePicker/DateRangePicker.test.tsx
- src/mantine-dates/src/components/DateRangePicker/DateRangePicker.tsx
There is no related issue (at least I can't find it)
I found this defect during development
> [@mantine/dates] DateRangePicker: Fix locale

- src/mantine-core/src/components/Select/Select.tsx
- src/mantine-hooks/src/use-page-leave/use-page-leave.story.tsx
- src/mantine-hooks/src/use-page-leave/use-page-leave.ts
The callback will no longer be called twice when leaving the page through the scrollbar.
Resolves #886
> [@mantine/hooks] usePageLeave: callback calls twice when leaving scrollbar fix

- docs/src/components/Layout/Navbar/NavbarDocsCategory/NavbarDocsCategory.tsx
This was already partially implemented, but it only worked on initial page loads.
Now on any navigation the active item in the navbar will scroll into view, but only if needed. This change also expands the navbar section if needed so the item can be visible (e.g. Collapse the hooks section of navbar then navigate to a hooks doc page via search)
Tested w/ clicking on pages, navigating via search, and navigating via links on page (e.g. "Extend Theme" page link to "TypographyStylesProvider")
> [docs] Scroll active sidebar item into view on navigate

- docs/src/docs/core/AppShell.mdx
Fix: Typo in Navigation.Section example, missing the grow prop that is mentioned in the comment. If I should include all the generated docs in the PR please let me know, thank you!
> [docs]  Missing grow prop in example

- docs/src/docs/others/notifications.mdx
from: ... update adn remove notification, be default id generates randomly
to : ... update and remove notification, by default id is randomly generated
> [docs] Fixed typo on Notifications document

- src/mantine-core/src/components/ActionIcon/ActionIcon.tsx
- src/mantine-core/src/components/Anchor/Anchor.tsx
- src/mantine-core/src/components/AppShell/Navbar/NavbarSection/NavbarSection.tsx
- src/mantine-core/src/components/Avatar/Avatar.tsx
- src/mantine-core/src/components/Badge/Badge.tsx
- src/mantine-core/src/components/Box/Box.tsx
- src/mantine-core/src/components/Button/Button.tsx
- src/mantine-core/src/components/Card/Card.tsx
- src/mantine-core/src/components/Card/CardSection/CardSection.tsx
- src/mantine-core/src/components/Center/Center.tsx
- src/mantine-core/src/components/ColorSwatch/ColorSwatch.tsx
- src/mantine-core/src/components/Highlight/Highlight.tsx
- src/mantine-core/src/components/Input/Input.tsx
- src/mantine-core/src/components/Menu/MenuItem/MenuItem.tsx
- src/mantine-core/src/components/Overlay/Overlay.tsx
- src/mantine-core/src/components/Paper/Paper.tsx
- src/mantine-core/src/components/Text/Text.tsx
- src/mantine-styles/src/theme/types/Polymorphic.ts
As discussed on Discord, this PR changes the following structure:
```ts
C extends React.ElementType ? PolymorphicComponentProps<C, SomeProps>  : never
```
to
```ts
C extends React.ElementType ? PolymorphicComponentProps<C, SomeProps>  : (SomeProps & { component: React.ElementType })
```
This allows for clearer error messages when providing a wrong value as `component`: instead of having all props failing, now only the `component` prop fails.
Furthermore it moves the conditional typing logic inside `PolymorphicComponentProps` directly to avoid duplicating it everywhere.
Note: one use case was not discussed on Discord, it's using the "generic" structure:
```ts
<Avatar<wrong> size="sm" />
```
Then the error is a bit less straightfoward, because it starts by saying that `component` prop is …
> [@mantine/core] clearer typescript error for polymorphic components

- docs/src/docs/others/rte.mdx
The code example is using `{}` instead of `[]` as a dependency list to `useMemo`
> [docs] Fix typo in useMemo

- src/mantine-demos/src/demos/packages/NumberInput/hold.tsx
Fixed a typo in the docs description for the NumberInput hold demo. (Ste -> Step)
> [docs] Fixed typo in NumberInputDemos.hold

- src/mantine-core/src/components/Modal/Modal.styles.ts
Fixes #927 
Should work w/ long and short modals centered/not centered with overflow outside/inside
Here's a codesandbox that should demo the fix just by applying the styles to the modals directly
https://codesandbox.io/s/mantine-modal-issue-forked-gq49mz?file=/src/App.tsx
> [@mantine/core] Modal: Prevent top from extending off screen for long centered, overflow outside modals

- src/mantine-styles/src/theme/types/MantineTheme.ts
This improves the type for strict mode users so that they no longer get a "possibly undefined" error when using it.
> [@mantine/styles] - Fix primaryColor not being a keyof MantineThemeColors

- src/mantine-core/src/components/Tooltip/Tooltip.tsx
This MR changes the usage of `mergeRefs` function to `useMergedRefs` hook in the `Tooltip` component, to fix an infinite re-render loop bug when using Mantine Tooltip with Preact
> [@mantine/core] use useMergedRefs hook in Tooltip component

- src/mantine-dates/src/components/Calendar/Calendar.story.tsx
- src/mantine-dates/src/components/CalendarBase/MonthPicker/MonthPicker.styles.ts
Fixes calendar full width issue when viewing the month.
Before:
After:
> [@mantine/dates]: Calendar: Fix full width on month view

- src/mantine-dates/src/components/TimeInput/TimeInput.tsx
- src/mantine-dates/src/components/TimeInputBase/create-time-handler/all-but-last-digit/all-but-last-digit.test.ts
- src/mantine-dates/src/components/TimeInputBase/create-time-handler/all-but-last-digit/all-but-last-digit.ts
- src/mantine-dates/src/components/TimeInputBase/create-time-handler/create-time-handler.test.ts
- src/mantine-dates/src/components/TimeInputBase/create-time-handler/create-time-handler.ts
This PR aims to improve the UX of the TimeInput component by advancing the user's focus to the next input field when we can infer their intent. If we can't deduce anything useful, then it falls back to the existing logic. The additional logic is only used when entering times that require a leading zero (e.g. `1:45`).
Here are a few examples demonstrating the difference:
**TimeInput props**: 12 hour time format without seconds
**Desired time (What the user is trying to enter)**: `1:30`
**User keystrokes (What the user types in the input)**: `1`, `3`, `0`
**Result (with current implementation)**: `12:00` (incorrect)
**Result (with this PR)**: `1:30` (correct)
**TimeInput props**: 24 hour time format without seconds
**Desired time (What the user is trying to enter)**: `2:45`
**User …
> [@mantine/dates] Improve the UX of the TimeInput component

- src/mantine-core/src/components/Popper/PopperContainer/PopperContainer.test.tsx
- src/mantine-notifications/src/NotificationContainer/NotificationContainer.test.tsx
- src/mantine-tests/src/is-supports-input-props.tsx
- src/mantine-tests/src/it-connects-label-and-input.tsx
- src/mantine-tests/src/it-filters-children.tsx
- src/mantine-tests/src/it-handles-boolean-state.tsx
- src/mantine-tests/src/it-is-polymorphic.tsx
- src/mantine-tests/src/it-renders-children.tsx
- src/mantine-tests/src/it-supports-classname.tsx
- src/mantine-tests/src/it-supports-focus-events.tsx
- src/mantine-tests/src/it-supports-input-icon.tsx
- src/mantine-tests/src/it-supports-input-right-section.tsx
- src/mantine-tests/src/it-supports-margins.tsx
- src/mantine-tests/src/it-supports-others.tsx
- src/mantine-tests/src/it-supports-paddings.tsx
- src/mantine-tests/src/it-supports-ref.tsx
- src/mantine-tests/src/it-supports-style.tsx
- src/mantine-tests/src/it-supports-sx.tsx
- src/mantine-tests/src/it-supports-wrapper-props.tsx
Hi,
Recently I noticed that conformance test cases props aren't safe that much, so I decided to make this PR to add this option to those.
```tsx
itSupportsSx(NotificationContainer, 
{ /* all NotificationContainer component props will be suggested  */ }
);
```
> [@mantine/tests] conformance test cases type safety

- src/mantine-core/src/components/Image/BackgroundImage/BackgroundImage.tsx
- src/mantine-spotlight/src/ActionsList/ActionsList.tsx
- src/mantine-spotlight/src/Spotlight.story.tsx
- src/mantine-spotlight/src/Spotlight/Spotlight.tsx
This pull request is a fix for issue #986.
Grouping is now done in the Spotlight component instead of ActionList in order to keep keyboard navigation consistent with the displayed list.
> [@mantine/spotlight] Fix keyboard navigation triggering wrong action when using grouping

- src/mantine-core/src/components/ColorPicker/converters/parsers.ts
- src/mantine-hooks/src/utils/random-id/random-id.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> [@mantine/core] & [@mantine/hooks] Replace deprecated String.prototype.substr() 

- src/mantine-core/src/components/Group/Group.styles.ts
- src/mantine-core/src/components/Group/Group.tsx
- src/mantine-demos/src/demos/packages/Group/configurator.tsx
Fixes #745 
alignItems (align) and justifyContent (position) now works properly for both row and column Groups
Added top/bottom as position properties for flex-start and flex-end
Adjusted demo so it better shows the effects of the properties
> [@mantine/core] Group: Fix position and align for column direction

- src/mantine-styles/src/theme/functions/fns/rgba/rgba.test.ts
- src/mantine-styles/src/theme/utils/to-rgba/to-rgba.test.ts
- src/mantine-styles/src/theme/utils/to-rgba/to-rgba.ts
Issue
Using a valid shorthand hex code value for a shade in mantine theme was not being converted to the correct color. For example, #ccc was returning black and not the correct color
Solution
- Update the isHexColor function to accept shorthand hex codes
- if hex is short hand, convert to the long version to be correctly converted to rgba
> Allow 3 character hex strings for mantine colors

- src/mantine-core/src/components/Slider/RangeSlider/RangeSlider.tsx
- src/mantine-core/src/components/Slider/Slider/Slider.tsx
- src/mantine-core/src/components/Slider/utils/get-change-value/get-change-value.test.ts
- src/mantine-core/src/components/Slider/utils/get-change-value/get-change-value.ts
As discussed on Discord, this adds the `precision` prop to `Slider` to allow clamping the computed value in case of floating point steps.
Default behavior when `precision` is `undefined` is to keep raw value, as it was the case before.
> [@mantine/core] allow precision prop for slider

- docs/src/docs/hooks/use-set-state.mdx
Fixed typo in [use-set-state](https://mantine.dev/hooks/use-set-state/) page
> [docs] Fixed typo

- src/mantine-demos/src/demos/packages/Badge/configurator.tsx
Default value of "[@mantine/core] Badge" component is "light" as configured [here](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Badge/Badge.tsx#L55).
But, at the "Badge" configurator docs, initial value and default value are set as "filled". This PR includes fix of this issue.
> [@mantine/demos] Badge: Set initial and default value as light

- docs/src/docs/dates/date-picker.mdx
Not being familiar with `dayjs` I spent the better part of an hour trying to figure out why the date parsing wasn't working when using `allowFreeInput` on a `DatePicker`.
I've updated the docs to include the relevant details to get this to work.
> Add documentation about dayjs plugins

- src/mantine-demos/src/demos/notifications/Notifications.demo.clean.tsx
- src/mantine-notifications/src/events.ts
The [`Clean queue` button](https://mantine.dev/others/notifications/#remove-notifications-from-state-and-queue) doesn't work
> [@mantine/notifications] Fix cleanNotificationsQueue

- src/mantine-core/src/components/PasswordInput/PasswordInput.story.tsx
- src/mantine-core/src/components/PasswordInput/PasswordInput.tsx
Previously the PasswordInput did not respect the default radius set in the theme, due to overwriting it with its own default props.
> [@mantine/core] PasswordInput: Make input respect theme default radius

- src/mantine-prism/src/Prism.styles.ts
use min-width of max lines 65535 like VSCode.
user can easy override with styles. if they want smaller space caused only small lines code
> [@mantine/prism] Fix prism number spacing

- docs/src/docs/dates/calendar.mdx
- scripts/utils/build-package.ts
- src/mantine-dates/src/components/CalendarBase/CalendarBase.tsx
- src/mantine-dates/src/components/CalendarBase/MonthsList/MonthsList.tsx
- src/mantine-dates/src/components/DatePicker/DatePicker.tsx
- src/mantine-dates/src/components/DateRangePicker/DateRangePicker.tsx
- src/mantine-dates/src/components/Month/Day/Day.test.tsx
- src/mantine-dates/src/components/Month/Day/Day.tsx
- src/mantine-dates/src/components/Month/Month.test.tsx
- src/mantine-dates/src/components/Month/Month.tsx
- src/mantine-dates/src/utils/get-weekdays-names/get-weekdays-names.ts
Adds a `renderDay` prop to the Calendar which is passed to the Day component that allows a day to be rendered using a custom component.  
Added a weekday label to allow custom labels. Typical in calendars is the use of three-letter weekdays as the size of a calendar grows. Whereas the default in Mantine is two-letter weekdays which works well for a calendar date picker though not so much as an event calendar.
> [@mantine/dates] Calendar: Added render day and weekday labels

- src/mantine-styles/src/theme/MantineProvider.tsx
```tsx
import tw from 'twin.macro';
export const styles: MantineProviderProps['styles'] = {
// Specifying `ButtonStylesParams` will report an error
Button: (theme: MantineTheme, { size }: ButtonStylesParams) => {
return {
root: {
...tw`transition duration-300`,
...(size === 'lg' && tw`text-base`),
...(size === 'md' && tw`text-sm`),
},
filled: tw`bg-primary-500 hocus:(bg-primary-400) active:(bg-primary-600)`,
outline: tw`text-primary-500/80 border-primary-500/80`,
} as Record<ButtonStylesNames, CSSObject>;
},
};
```
> [@mantine/styles] Any params type to allow specifying styles names

- CONTRIBUTING.md
`[commit convention](##commit-convention)` ->`[commit convention](#commit-convention)`
> [docs] Fix broken link in `CONTRIBUTING.md`

- docs/src/components/GettingStarted/Guides/Guide.tsx
Seems like remix updated their package
https://github.com/remix-run/remix/blob/main/examples/mantine/app/entry.server.tsx
> [docs] update package name in `get started with Remix` section

- src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
The default dropdownPosition is bottom, it not flips to above when there is not enough space. The Select component dropdownPosition default also is flip, so I did this.
another, i saw the default limit is 5，but i want show large data，when I set limit to 30, the flip is also not work, so I also
need to set maxDropdownHeight，thus Autocomplete SelectDropdown will same as Select component.
I hope I did the right thing, Thanks.
https://codesandbox.io/s/adoring-merkle-bffpbm?file=/src/App.tsx
> [@mantine/core] Autocomplete: make dropdownPosition default to flip

- src/mantine-rte/src/components/RichTextEditor/RichTextEditor.styles.ts
copy styles from demo react quill https://codesandbox.io/s/6x93pk4rp3?file=/index.js:70-80
display none make useStyles re-render and caused racing setValue. onChange value from paste and onChange from re-render
https://github.com/mantinedev/mantine/issues/1086
> [@mantine/rte] fix rte copy paste on highlight

- src/mantine-dates/src/components/DatePicker/DatePicker.tsx
When an input has `type="date"` the `value` read/written to the dom node is a string in the format `YYYY-MM-DD` (the format actually rendered is determined by the browser), so when someone sets `type="date"` on the `DatePicker` component and it attempts to set the value in the dom the value doesn't actually get rendered without a properly set formatting string. Having `type="date"` is preferential when using a framework that ecourages form submissions such as Remix since otherwise the `input` will submit locale-formatted values rather than a timestamp or ISO date (whereas with `type="date"` the value is ISO-formatted).
Additionally, when `type="date"`, there is a browser-supplied clear button, resulting in two clear buttons being rendered. There is no reliable cross-browser way to hide …
> Fix DatePicker when type="date"

- src/mantine-dropzone/src/Dropzone/Dropzone.test.tsx
- src/mantine-dropzone/src/Dropzone/Dropzone.tsx
This PR adds a `name` prop to allow this component to be used in HTML forms, which is being popularized by frameworks like Remix.
Resolves https://github.com/mantinedev/mantine/discussions/1111
> [@mantine/dropzone] Dropzone: Add name prop 

- src/mantine-hooks/src/use-fullscreen/use-fullscreen.ts
Added a check to ensure a custom ref element toggles the fullscreen state
> [@mantine/hooks] use-fullscreen: custom ref state

- src/mantine-demos/src/demos/core/Stepper/Stepper.demo.usage.tsx
This typo is present in the docs too:
https://mantine.dev/core/stepper/
> Fix typo in Stepper demo

- src/mantine-core/src/components/Notification/Notification.story.tsx
- src/mantine-core/src/components/Notification/Notification.styles.ts
- src/mantine-core/src/components/Notification/Notification.tsx
while text so large it not hidden.
ps: I am worried about if I should removing the `disallowClose` prop in NotificationStylesParams,  maybe others custom Notification styles  might use this property?
> [@mantine/core] Notification: fix text so large not hidden

- src/mantine-core/src/components/InputWrapper/InputWrapper.tsx
- src/mantine-tests/src/it-supports-input-wrapper-props.tsx
Omit the required "*" from the accessible name of labels by using `aria-hidden` on the span.
> [core] Omit "*" from label accessible names

- src/mantine-core/src/components/Alert/Alert.test.tsx
- src/mantine-core/src/components/Alert/Alert.tsx
- Add `alert` role to `Alert` components
- Use the title to label alerts
- Use the body to describe alerts
> [@mantine/core] Alert: a11y fixes

- src/mantine-rte/src/components/RichTextEditor/RichTextEditor.tsx
Hi! I see that there are not enough args. Can we add them?
> [@mantine/rte] add args for onChange callback

- src/mantine-core/src/components/SegmentedControl/SegmentedControl.story.tsx
- src/mantine-core/src/components/SegmentedControl/SegmentedControl.styles.ts
- src/mantine-core/src/components/SegmentedControl/SegmentedControl.tsx
#1239 ... assuming we don't want initial transition on render, have done this. If it is to be avoided via a prop, shall do it
> [@mantine/core] SegmentedControl: remove initial active tab translation animation

- src/mantine-core/src/components/Modal/Modal.test.tsx
- src/mantine-core/src/components/Modal/Modal.tsx
The `id` prop passed to `<Modal/>` is not being added to the DOM.
> [@mantine/core] Modal: add id to root element

- src/mantine-core/src/components/MultiSelect/MultiSelect.tsx
Currently the defaultRadius is not applied on the MultiSelect
> [@mantine/core] MultiSelect: Fix defaultRadius

- src/mantine-core/src/components/RadioGroup/Radio/Radio.tsx
- src/mantine-core/src/components/RadioGroup/RadioGroup.test.tsx
- src/mantine-core/src/components/RadioGroup/RadioGroup.tsx
- Ensure a radio group is labelled
- Hide the styled radio dot
> [@mantine/core] RadioGroup: accessible name

- src/mantine-modals/src/context.ts
- src/mantine-modals/src/use-modals/use-modals.test.tsx
Replace for `confirm` and `cancel` labels type `string` to `ReactNode`. 
This change will allow to place all valid values of the type `ReactNode` inside the confirm and cancel buttons confirm modal component.
#1286
> [@mantine/modals] Add new value to Record type ConfirmLabels

- src/mantine-core/src/components/SegmentedControl/SegmentedControl.story.tsx
- src/mantine-core/src/components/SegmentedControl/SegmentedControl.styles.ts
- src/mantine-core/src/components/SegmentedControl/SegmentedControl.tsx
- src/mantine-demos/src/demos/core/SegmentedControl/SegmentedControl.demo.disabled.tsx
- src/mantine-demos/src/demos/core/SegmentedControl/index.ts
Add `disabled` property support for individual options.
Add missing `not-allowed` value for `cursor` for `disabled` state of control and individual options.
> [@mantine/core] SegmentedControl: Add disabled property support for individual options.

- docs/src/docs/hooks/use-element-size.mdx
`use-element-size` hook is not exported into its own file and is actually located inside `use-resize-observer`'s source.
> [docs] use-element-size: Update source reference.

- docs/src/docs/hooks/use-element-size.mdx
- docs/src/docs/hooks/use-event-listener.mdx
Fix missing `.ts` extension for:
1. `use-element-size`.
2. `use-event-listener`.
> [docs] Fix incorrect source references for hooks.

- src/mantine-modals/src/ConfirmModal.tsx
- src/mantine-modals/src/Modals.story.tsx
Fixes #836 
Sets default confirm modal labels to empty string to avoid browser error (and no modal opening) if the labels are not. Empty string instead of English labels so it is not confusing for non-English development/usage
> [@mantine/modals] ConfirmModal: Add default labels

- docs/src/docs/theming/functions.mdx
`theme.fn.radialGradient` only takes an argument of type `string[]`, which wasn't represented correctly in the documentation.
> [docs] Removed incorrect argument types for radialGradient

- src/mantine-core/src/components/Alert/Alert.test.tsx
- src/mantine-core/src/components/Alert/Alert.tsx
Fix label association of alerts when they have no `id`
> [@mantine/core] Alert: Fix a11y name without id

- src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
Fixes #1360
Now pressing enter when there are no filtered items doesn't call event.preventDefault(), so a parent form will be submitted now. Try the Autocomplete -> Within form story to test the changes.
> [@mantine/core] Autocomplete: Fix enter not submitting form

- src/mantine-hooks/src/use-move/use-move.ts
`onScrubEnd` is being called before the `onChange` of parent component like `Slider`, hence a mismatch in the value being passed to `onScrubEnd`.
> [@mantine/hooks] use-move: fix onScrubEnd on quick tap i.e without any scrubbing

- docs/src/docs/others/dropzone.mdx
- package.json
- src/mantine-dropzone/package.json
- src/mantine-dropzone/src/Dropzone/Dropzone.tsx
- yarn.lock
I struggled with docs a bit. I wasn't sure where to add the example since using an array is so simple and intuitive, it's nice having it right at the top so it's the first thing users see. At the same time, the two current examples flow so nicely into the mime types table that I didn't want to disrupt the flow. Anyway, I'm happy to make any changes.
> [@mantine-dropzone] Add support for React 18

- src/mantine-core/src/components/NumberInput/NumberInput.tsx
The current logic to determine the NumberInput `inputMode` prop checks various combinations of the `step` and `precision` props to make that determination. I'm proposing that users should be allowed to supply their own `inputMode` prop in the event that the logic in `mantine/src/mantine-core/src/utils/get-input-mode` doesn't account for their needs.
> [@mantine/core] NumberInput: Allow user to pass inputMode

- docs/src/docs/hooks/use-network.mdx
- src/mantine-hooks/src/use-network/use-network.ts
Yeah, the support is truly terrible.
TypeScript types i.e. `NetworkInformation`, `ConnectionType` and such are incomplete and don't reflect the MDN docs as well so I didn't use them.
> [@mantine/hooks] use-network: Include all properties and remove dummy object.

- docs/src/docs/form/use-form.mdx
- src/mantine-form/src/use-form.test/use-form.stable-functions.test.ts
- src/mantine-form/src/use-form.ts
- src/mantine-form/src/use-prop-ref/use-prop-ref.ts
- src/mantine-form/src/use-state-ref/use-state-ref.ts
Fixes #1196, #1193 
This makes all functions returned by `useForm` stable. I used the eslint react-hooks plugin for their exhaustive dependencies rule while converting these. It helped catch everywhere that the state needed to be switched to using the ref value within the `useCallback` uses
> [@mantine/form] use-form: Make functions referentially stable

- src/mantine-labs/src/PinInput/PinInput.tsx
Before this PR when you entered 4 numbers and remove one the onChange function is called twice and the second time with the old value so for example `1234` instead of `123` the real value that is display
> [@mantine/labs] PinInput calls onChange twice

- docs/src/docs/core/ActionIcon.mdx
Changed the order of the ActionIcon variants so that they match with the order in the demo
> [docs] Change the order of the ActionIcon variants

- src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
- src/mantine-core/src/components/NumberInput/NumberInput.tsx
Fixes the bug in NumberInput raised in the [discord bugs channel](https://discord.com/channels/854810300876062770/972850721244471436/973654286154203156)
> Is NumberInput not allowing the "-" symbol in an empty NumberInput expected behavior? Currently, you are unable to type "-" in an empty NumberInput unless you first put a number then go back and place the "-" before it
Changes:
- You can now type `-` in an empty NumberInput.
- If `-` is the only thing in a NumberInput, the value will remain `undefined`, and the NumberInput will be cleared when the `onBlur` event fires.
> [@mantine/core] NumberInput: Allows the "-" symbol in an empty NumberInput

- src/mantine-styles/src/theme/types/DefaultProps.ts
With strictMode, TS will give an error following this use case: https://mantine.dev/theming/sx/#sx-array
This PR add `undefined` to `sx` array's definition.
> [@mantine/styles] `sx`: Add `undefined` for array

- src/mantine-core/src/components/Box/Box.tsx
- src/mantine-core/src/components/Box/use-sx/use-sx.ts
Do some clean up by removing unnecessary types from Box component.
This PR is just clean up code.
> [@mantine/core] Box: Remove unnecessary types

- src/mantine-dates/src/components/TimeInput/TimeInput.story.tsx
- src/mantine-dates/src/components/TimeInputBase/get-date/get-date.test.ts
- src/mantine-dates/src/components/TimeInputBase/get-date/get-date.ts
Fix for #1443.
Outside change through the `onChange` handler in controlled variant still preserves milliseconds.
> [@mantine/dates] TimeInput: Clear milliseconds on input value change.

- src/mantine-form/src/use-form.ts
This PR addresses issue raised in #1394 
The reason why input errors are not clearing out is because errors are stored in the format of `form name + input field index + field name`. Which results in the following errors state, if we take the example raised in the issue (given 2 same inputs are created).
```
{
employees.0.name: "Name should have at least 2 letters"
employees.1.name: "Name should have at least 2 letters"
}
```
Whenever we pass field to the `clearFieldError` utility, we always pass just the `form name`, thus receiving `employees`, instead of full error path.
This PR uses full error path for each individual input.
> [@mantine/form] `use-form`: Use correct error paths to clear single input errors

- src/mantine-styles/src/theme/types/MantineColor.ts
Related to #1127 
The current issue is when a user overrides custom color in the method defined in the docs [here](https://mantine.dev/theming/extend-theme/#adding-custom-colors), TS ends up with just `string` as the type for color on something like `<Button color='my-custom-color' />`. Instead, infer the type which lets TS use the string union defined.
Technically a user could say their colors are indexed by objects or something dumb and have runtime issues. That's on the user though. There might be some clever way to revert to the default colors if the user specifies things that aren't string keys, but I don't think it's worth the effort/trickier TS when it's pretty clear to the user that they should be strings
> [@mantine/styles] Fix custom color typescript override

- docs/src/docs/core/Card.mdx
Fixes minor typo in `Card.mdx`
> [docs] Fix typo in Card section

- src/mantine-core/src/components/Drawer/Drawer.tsx
The docs described `closeOnClickOutside` and `closeOnEscape` as disabling an "onClock" trigger. They actually refer to `onMouseDown` and `onKeyDownCapture`  triggers, respectively.
> [docs] Drawer: fix small typo

- docs/src/components/Layout/Header/HeaderControls/HeaderControl.styles.ts
- docs/src/components/SocialButton/SocialButton.tsx
#7289da is used on Mantine's documentation page for Discord's background color; the actual color is #5865f2 which is used on the dark mode version of the page.
> [docs] Use Discord's new blurple for light mode

- docs/src/components/GettingStarted/Guides/Guide.tsx
The `yarn create @vitejs/app` command to create Vite apps has been depracted few months back in favor of `yarn create vite`.
I have updated the docs to accomodate this change.
> [docs] Update Vite init command

- src/mantine-form/src/index.ts
Exports FormList type so TS users can use it in their explicit form values definition without breaking `form.getListInputProps`.
Example of the issue:
https://codesandbox.io/s/eloquent-lake-1cb038?file=/src/Registeration.tsx
> [@mantine/form] - Export FormList type for explicit TypeScript users

- src/mantine-dates/src/components/TimeInputBase/AmPmInput/AmPmInput.tsx
As android doesn't publish the key code ([issue](https://bugs.chromium.org/p/chromium/issues/detail?id=118639)) and is always undefined. Using `onChange` -> `event.target.value` to toggle am/pm
> [@mantine/date]: fix am-pm for android

- docs/src/docs/core/Image.mdx
[docs] fixed typo in Image Placeholders
been using mantine a lot, found this small typo
> [docs] fixed typo in Image Placeholders

- src/mantine-core/src/components/Switch/Switch.story.tsx
- src/mantine-core/src/components/Switch/Switch.styles.ts
Fix issue: https://github.com/mantinedev/mantine/issues/1582
The on label for the switch had incorrect styling resulting in the label not being visible. To fix this I just copied the styles from the off label which was showing correctly. I added some stories as well
> [@mantine/core] Switch: fix on / off label

- src/mantine-core/src/components/TypographyStylesProvider/TypographyStylesProvider.styles.ts
This PR fixes the missing `px` unit for the TypographyStylesProvider code.
|Screenshot|
|-|
|<img width="183" alt="Screenshot 2022-06-12 at 10 54 45 AM" src="https://user-images.githubusercontent.com/6391763/173217133-8b0bd16f-0a72-4635-b84f-ccf03ce852ee.png">|
> [@mantine/core] TypographyStylesProvider: Add missing `px`

- src/mantine-demos/src/demos/dropzone/Dropzone.demo.manual.tsx
Adding null to useRef so that TypeScript does not throw an error when using this example inside a TS file.
> [docs] Dropzone: strict mode adjustment

- src/mantine-core/src/components/NumberInput/NumberInput.tsx
NumberInput does not seem to follow the correct order of the onChange events when using the controls. The blur of other inputs is triggered too late as the focus event is triggered after onChange. This could be resolved by triggering the focus earlier.
> [@mantine/core] NumberInput: Fix late focus when using controls

- src/mantine-core/src/components/NumberInput/NumberInput.tsx
As mentioned on [Discord](https://discord.com/channels/854810300876062770/972850721244471436/993098144067899472). Fixes that NumberField does not respect repeating keys (by holding them long) when "stop on hold" is used.
> [@mantine/core] NumberInput: Fixes repeating keys when step on hold is used

- src/mantine-core/src/components/Autocomplete/Autocomplete.tsx
- src/mantine-labs/src/TagInput/TagInput.tsx
- src/mantine-spotlight/src/Spotlight/Spotlight.tsx
Relates #1565. I faced the same issue to use Japanese IME (maybe also in Chinese IME?) on Autocomplete, TagInput and SpotLight components. So I apply the same fix of #1570 to these components.
It may relate to the type of IME and IME settings. I tested with the default Japanese IME in macOS Monterey (with enabled the live conversion setting).
https://user-images.githubusercontent.com/62416191/176714240-8a90959d-38f4-48cf-9733-3ffd44e737a2.mov
https://user-images.githubusercontent.com/62416191/176715515-1d209542-1bb6-418f-912a-5ab15f0be84b.mov
https://user-images.githubusercontent.com/62416191/176714399-819e39e1-0a22-48df-8f82-579970688705.mov
https://user-images.githubusercontent.com/62416191/176717652-3cb2c738-2c81-41a2-8319-cd8affa17b0b.mov …
> Fix input bug with Japanese IME

- src/mantine-hooks/src/use-interval/use-interval.ts
The use case I ran into is polling a status api for long running reports. When I generate the report it returns the taskId and I need to poll with that taskId. This doesn't currently work with the existing hook because taskId isn't defined until the user clicks a button to generate a report.
* Use a ref to `fn` and update the ref if the `fn` changes
* [Article that references a similar issue]( https://overreacted.io/making-setinterval-declarative-with-react-hooks/) by Dan Abramov
This now works 🎉 
```tsx
const pollingInterval = useInterval(() => {
checkStatus({ taskId: taskIdState });
}, 1000);
```
> [@mantine/hooks] use-interval: handle dynamic functions with a ref

- src/mantine-dates/src/components/TimeInput/TimeInput.styles.ts
Disabled time input had opacity set on both the component and wrapper, causing the final opacity to be incorrect.
fix for [#1795](https://github.com/mantinedev/mantine/issues/1795)
> [@mantine/dates]: TimeInput: Fix opacity applied twice when disabled

- src/mantine-dates/src/components/Month/Month.tsx
Bare minimum to re-produce:
```
import React, { useState } from 'react';
import { Calendar } from '@mantine/dates';
function Demo() {
const [value, setValue] = useState(null);
return (<Calendar
value={value}
onChange={setValue}
excludeDate={() => true}
/>);
}
```
The bug was caused because of a loop to find the first non-excluded date and then used in another function call.
The loop couldn't find a proper day so it was returning undefined, which caused the bug.
Fix for: #1784
> [@mantine/dates] Calendar: Fix bug when all days are excluded:

- src/mantine-core/src/components/Transition/use-transition.ts
Hi, this is my suggestion to fix the transition duration (possible temporary until the hook is also fixed) application in dev mode. It more or less is just a deletion of the useState which causes a side effect in the useDidUpdate hook where the transition duration is not correctly returned (probably cause the hook fired twice in the new React 18 strict mode). Please refer to the issue I created for a description of the faced error. #1686 
Happy to discuss
> [@mantine/core] Fix useTransition.ts not correctly emit duration

- package.json
- src/mantine-next/src/NextLink.tsx
- yarn.lock
- The `href` prop should not be passed to the `a` element and should be handled automatically by `next/link` to fix the [`basePath`](https://nextjs.org/docs/api-reference/next.config.js/basepath#links)
- Respect `next/link` all props
- Add `displayName` as `@mantine/next/NextLink`
- Upgrade `next` dependence
> [@mantine/next] Improve next link

- docs/src/docs/form/use-form.mdx
This prop [has been](https://github.com/mantinedev/mantine/commit/102a62ec48a90857090afc915443ffbecaa249b6#diff-885f0cbfb62b24bda2ed7145a69597b51a67fabc68b78fde5b672962ed97559eL192) removed and should no longer be mentioned in the api overview
> [Docs] Remove form list documentation

- src/mantine-dates/src/components/CalendarBase/CalendarBase.tsx
- src/mantine-dates/src/components/CalendarBase/MonthsList/MonthsList.test.tsx
- src/mantine-dates/src/components/CalendarBase/MonthsList/MonthsList.tsx
- src/mantine-dates/src/components/RangeCalendar/RangeCalendar.story.tsx
- src/mantine-dates/src/components/RangeCalendar/RangeCalendar.tsx
Hi, this is my suggestion for the Range calendar to specify how many months are scrolled at a time. Currently when clicking to next or previous months, the amount of months scrolled is decided by the amountOfMonths property. This update would allow the user to specify how many months are "scrolled" at a time. 
PS: Happy to discuss and thanks so much for the great project! 🙏
> [@mantine/dates] Add paginateBy property for Range Calendar

- docs/src/docs/hooks/use-focus-return.mdx
Update docs to reflect the removal of `transitionDuration` prop due to changes in [use-focus-trap]
> Update use-focus-return.mdx to reflect 5.0.0 changes

- src/mantine-core/src/NumberInput/NumberInput.tsx
Related issue: https://github.com/mantinedev/mantine/issues/1905
Before:
https://user-images.githubusercontent.com/22859283/181459033-21669098-e90c-4173-9e60-677fbdc75a23.mov
After:
https://user-images.githubusercontent.com/22859283/181459057-3de74e75-c259-4f90-9f2c-69990f35af0d.mov
> [@mantine/core] NumberInput: Preserve cursor selection on format/parse

- src/mantine-demos/src/demos/core/Stepper/Stepper.demo.stylesApi.tsx
Replaced stepProgress and stepCompleted styles by data-progress and data-completed props.
> [@mantine/demos] Stepper - Corrected example of using styles API

- src/mantine-prism/src/Prism/Prism.tsx
- src/mantine-prism/src/PrismTabs/PrismTabs.tsx
#1872 
- In the code area of ​​the official documentation, I think it would be better for the translator not to translate.
- add `translate="no"` in `Prism` and `PrismTabs`
In my opinion the tab area should also not be translated. Let me know if you have any other comments!
Thanks for the hard work of the mantine development team!
> [@mantine/prism] no translate

- docs/src/docs/hooks/use-mouse.mdx
- src/mantine-hooks/src/use-mouse/use-mouse.ts
This PR adds a `resetOnExit` option (false by default for backwards compatibility) to the `useMouse()` hook. When true, the values of x & y will be 0 when the mouse leaves the specified element
> [@mantine/hooks] use-mouse: Add resetOnExit option

- docs/src/docs/hooks/use-toggle.mdx
- src/mantine-hooks/src/use-toggle/use-toggle.test.ts
- src/mantine-hooks/src/use-toggle/use-toggle.ts
Fix #1876.
With this PR, users don't need a type parameter for `useToggle` anymore.
```ts
import { useToggle } from "@mantine/hooks";
const [value] = useToggle(["light", "dark"] as const);  // `value` is inferred as "light" | "dark"
```
> Avoid manual type annotation for useToggle

- src/mantine-dates/src/components/DatePicker/DatePicker.tsx
Fixes the capitalization issue in #1844 - just one place appeared to be missing the `upperFirst` call.
> [@mantine/dates] Fix capitalization of date input state

- src/mantine-core/src/Burger/Burger.styles.ts
- Pseudo-Element(`&::before, &::after`) - fix typo
Modified for consistency with virtual elements of other components.
> [@mantine/core] Burger: pseudo element typo fix

- src/mantine-core/src/Notification/Notification.styles.ts
- src/mantine-core/src/Switch/Switch.styles.ts
- fixed typo
It has been modified for consistency with the value of the existing content property.
> [@mantine/core] fixed typo `content` attribute to Notification and Switch

- src/mantine-core/src/Button/Button.styles.ts
#1717 , when a variant is not 'gradient', maybe don't need the 'background-image', which now returns invalid value 'transparent'.
> [@mantine/core] fix: Invalid background-image property in Button

- docs/src/docs/form/nested.mdx
Fixes [#1994](https://github.com/mantinedev/mantine/issues/1994) - validation example for lists in useform has error messages swapped
> [docs] Fix useform list validation example

- src/mantine-rte/src/components/RichTextEditor/RichTextEditor.styles.ts
Rich text editor
https://mantine.dev/others/rte/#mentions
- Mention has width and height properties, but the actual size is not applied because it is an inline property.
- If the Mention has inline-block properties, width, height, margin, padding can be set, so I think it is very useful.
- Even for inline block properties, the width (65px) and height (24px) currently specified are too small, so I thought it would be better to delete them.
- If there are several lines of mentions, it would be better to see if there is a margin-bottom. What do you think?
If you agree with this, I'll add a commit.
> [@mantine/rte] Change the display property of the mention to `inline-block`

- src/mantine-core/src/AppShell/Header.story.tsx
- src/mantine-core/src/AppShell/HorizontalSection/HorizontalSection.styles.ts
- src/mantine-core/src/AppShell/HorizontalSection/HorizontalSection.tsx
- src/mantine-core/src/AppShell/Navbar.story.tsx
- src/mantine-core/src/AppShell/VerticalSection/VerticalSection.tsx
Added an optional `withBorder` prop to the appshell header component. By default, it is set to true.
> [@mantine/core] AppShell/Header: Add withBorder Prop

- src/mantine-hooks/src/use-click-outside/use-click-outside.ts
This PR makes `useClickOutside` less permissive. If an element is not inside the DOM (it was removed), assume that the deleted element could have been inside the relevant `nodes` and do NOT fire the click outside event.
This is a proposed solution to #1986.
> [@mantine/hooks] use-click-outside: ignore clicks on elements removed from DOM

- src/mantine-core/src/Popover/PopoverDropdown/PopoverDropdown.tsx
As discussed on Discord, simply expose the `ctx.placement` from Floating UI as a `data-position` attribute on `Popover.Dropdown`
> [@mantine/core] add data-position attribute to popover dropdown

- src/mantine-utils/src/create-polymorphic-component/create-polymorphic-component.ts
This PR adds missing Typescript properties on polymorphic components: `displayName`, `defaultProps`, `propTypes` and `contextTypes`.
It uses a future-proof select on `FunctionComponent` to include any property that could be added by the React team in the future
> [@mantine/core] add all properties to polymorphic component types

- docs/src/docs/others/spotlight.mdx
- src/mantine-demos/src/demos/spotlight/Spotlight.demo.actionsCloseOnTrigger.tsx
- src/mantine-demos/src/demos/spotlight/index.ts
- src/mantine-spotlight/src/Spotlight.story.tsx
- src/mantine-spotlight/src/Spotlight/Spotlight.tsx
- src/mantine-spotlight/src/types.ts
> [@mantine/spotlight] Add closeOnTrigger prop to SpotlightAction (#2040)

- src/mantine-hooks/src/use-interval/use-interval.ts
Fix #2093: Interval hook ensure only 1 running timer
This ensures even when creating and destroying components in React 18 it ensures that only 1 timer can be running at a time.
> Fix #2093: [@mantine/hooks] Interval hook ensure only 1 running timer

- src/mantine-core/src/Box/use-sx/get-system-styles/get-system-styles.ts
In addition to `margin`, also receive `padding` values, so I think need to change the name!
> [@mantine/core] Refactor: rename isValidSizeValue, getSizeValue parameter

- src/mantine-hooks/src/use-id/use-id.ts
I thought I could replace that syntax with the already existing Hooks.
1. If you look at the use-isomorphic-effect hook, you are checking the document, not the window. Is it intentional?
```ts
// hooks/use-isomorphic-effect.ts
export const useIsomorphicEffect = typeof document !== 'undefined' ? useLayoutEffect : useEffect;
```
> [@mantine/hooks] use-id: replace with `useIsomorphicEffect` hooks

- src/mantine-core/src/Collapse/use-collapse.ts
Fixes error reported on Discord where the Collapse component would sometimes make the page crash. "Sometimes" narrowed down to "people using reduced motion accessibility setting".
> [@mantine/core] fixed issue when using collapse with reduced motion

- src/mantine-demos/src/components/Demo/CodeDemo/CodeDemo.styles.ts
- https://mantine.dev/core/tabs/#icon-and-right-section
- https://mantine.dev/core/stepper/#customize-with-styles-api
- https://mantine.dev/core/accordion/#custom-control-label
> [docs] fix: Change the style of code controls in the demo

- src/mantine-styles/src/theme/types/MantineTheme.ts
- create a named type for `Record<string, ThemeComponent>`
- remove unnecessary code (`fn` was being `Omit`ted twice)
- refactor to use `Partial<Pick<>`
> improve types

- docs/src/docs/core/Grid.mdx
- src/mantine-core/src/Grid/Col/Col.styles.ts
- src/mantine-core/src/Grid/Col/Col.tsx
- src/mantine-demos/src/demos/core/Grid/Grid.demo.order.tsx
- src/mantine-demos/src/demos/core/Grid/index.ts
Adds an `order` prop to the `Grid.Col` component so that columns can be re-ordered/be ordered based on responsiveness.
> [@mantine/core] Grid: Add column prop

- src/mantine-core/src/Container/Container.tsx
Description of fluid prop was misleading because it implied that the prop would apply `width: 100%`, but it actually applies `max-width: 100%`
closes #2175
> [@mantine/core] Container: Change desc of fluid prop

- src/mantine-core/src/Grid/Col/Col.styles.ts
- src/mantine-demos/src/demos/core/Grid/Grid.demo.order.tsx
Fixes issue with both `offset` and `order` props for `Grid.Col` that requires each to have a responsive prop (`xs`, `sm`, `md`, `lg`, `xl`) for their respective responsive props (`offsetXs`, `orderXs`, etc). to work.
Also updated the docs for `order` to properly use `Grid.Col` rather than the `Col` shorthand.
> [@mantine/core] Grid: Fix offset and order responsive props

- src/mantine-core/src/Title/Title.styles.ts
- src/mantine-core/src/Title/Title.tsx
> [@mantine/core] Title: Fix `inline` prop being ignored

- src/mantine-demos/src/demos/hooks/use-debounced-state.demo.leading.tsx
- src/mantine-demos/src/demos/hooks/use-debounced-state.demo.usage.tsx
- src/mantine-demos/src/demos/hooks/use-debounced-value.demo.cancel.tsx
- src/mantine-demos/src/demos/hooks/use-debounced-value.demo.leading.tsx
- src/mantine-demos/src/demos/hooks/use-debounced-value.demo.usage.tsx
- src/mantine-demos/src/demos/hooks/use-validated-state.demo.usage.tsx
closed #2165 
Fix to prevent horizontal scrolling when entering a long string
- https://mantine.dev/hooks/use-validated-state/
- https://mantine.dev/hooks/use-debounced-state/
- https://mantine.dev/hooks/use-debounced-value/
> [docs] Fix to prevent horizontal scrolling when entering a long string

- src/mantine-demos/src/demos/core/ActionIcon/ActionIcon.demo.configurator.tsx
Please see the screenshots and the videos in the discord thread: https://discord.com/channels/854810300876062770/1010668931842855064
This PR is more of a "Expose the problem to the maintainers" PR than anything, even though it does fix the mismatch
The demo real code was changing both the ActionIcon's size and the embedded Icon's size.
While this seems to be desirable, **it was not reflected in the apparent demo code**.
There are two way to "fix" this. One simple way, and one difficult way
1. (Easy way) **Make the real code match the apparent code**: do not change the embedded Icon's size when the slider moves.
2. (Hard way) **Make the apparent code match the real code**: continue to change the embedded Icon's size when the slider moves, but reflect that in the code template in real time …
> ActionIcon:  Fix mismatch between demo apparent code and real code

- docs/src/docs/core/Notification.mdx
- src/mantine-core/src/Notification/Notification.tsx
[original discord thread](https://discord.com/channels/854810300876062770/887408088800448553/1011259560012566609)
Spread Notification's `closeButtonProps` after CloseButton's `iconSize` and `color` would be better experience to customize Notification's CloseButton. (override default prop `iconSize=16, color=gray`)
Like below code, for customizing, using  CloseButton's props will better than using `classNames` because it is more simple and It can use CloseButton's predefined props.
```tsx
// If using classNames to customize Notification's closeButton
const useStyles = createStyles(
(theme) => ({
closeButton: {
color: theme.colors.gray[2],
width: '44px',
height: '44px',
},
})
);
const { classes } = useStyles();
<Notification classNames={{ ...classes }} />
// If using closeButtonProps to …
```
> [@mantine/core] Notification: spread closeButtonProps after iconSize, color

- docs/src/docs/hooks/use-intersection.mdx
By the way, should I be branching off of `dev` instead of `master` for more complex changes? I've been branching from master since it seems to be more up-to-date.
> [docs] Fix typo in use-intersection docs

- package.json
@rtivital
Volta is a node version manager just like **nvm** 
https://volta.sh/
By pinning the `node version` to `package.json`, volta can automatically pick up the node version to use when running `yarn install` making the process more user friendly.
> [core]: Add volta support

- src/mantine-core/src/Radio/Radio.story.tsx
- src/mantine-core/src/Radio/Radio.tsx
- src/mantine-core/src/Radio/RadioGroup.context.ts
- src/mantine-core/src/Radio/RadioGroup/RadioGroup.tsx
The name prop should probably be required in a future major release because otherwise you get [odd behaviour](https://codesandbox.io/s/jolly-worker-yfclb5).
> [@mantine/core] Add name attribute to Radio.Group

- src/mantine-core/src/Autocomplete/Autocomplete.tsx
> [@mantine/core] Autocomplete: fix grouping in Autocomplete

- docs/src/docs/hooks/use-text-selection.mdx
from ...  `import { useClipboard } from '@mantine/hooks';`
to ...  `import { useTextSelection } from '@mantine/hooks';`
> [@mantine/hooks]use-text-selection: Fixed typo on useTextSelection document

- docs/src/docs/core/Grid.mdx
- src/mantine-core/src/Grid/Col/Col.styles.ts
- src/mantine-core/src/Grid/Col/Col.tsx
- src/mantine-demos/src/demos/core/Grid/Grid.demo.auto.tsx
- src/mantine-demos/src/demos/core/Grid/Grid.demo.content.tsx
- src/mantine-demos/src/demos/core/Grid/index.ts
Discussion https://github.com/mantinedev/mantine/discussions/2292
Add two additional options for grid columns spans:
- `auto` - A column with auto grows to fill additional space on the row. All columns with span `auto` will be the same size.
- `content` - The column fits its content. Using the same name as flex-basis for the same concept: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis
Auto
Content
> [@mantine/core] Grid: Add auto and content spans

- src/mantine-carousel/src/Carousel.tsx
Current workaround is to reinit embla instance.
```ts
const [embla, setEmbla] = useState<Embla | null>(null);
useEffect(() => {
if (embla) {
embla.reInit({ containScroll: "trimSnaps", skipSnaps: true });
}
}, [embla]);
```
So to me it seems reasonable to add it directly to Mantine.
> [@mantine/carousel] Carousel: add options `skipSnaps` and `containScroll`

- docs/src/docs/core/Radio.mdx
- src/mantine-demos/src/demos/core/Radio/Radio.demo.groupConfigurator.tsx
- src/mantine-demos/src/demos/dates/Calendar/Calendar.demo.stylesApi.tsx
Previously, if you copied the [example from the Calendar Styles API demo](http://localhost:7521/dates/calendar/#customize-with-styles-api), you were unable to switch the current month.
I noticed you updated to `useState<Date | null>`. Sneaky sneaky :grin:
> [docs] Include usage of Radio.Group name prop and fix Calendar example

- src/mantine-rte/src/components/RichTextEditor/RichTextEditor.tsx
- Quill can proceed undefined values
- defaultValue is related to defaultValue of HTML input, this is not right
- Also, onChange can be undefined because field can be readOnly
> [@mantine/rte] fix prop types

- src/mantine-core/src/Modal/Modal.tsx
Fixes #2371 by setting the Modal Overlay z-index to -1 instead of 0.
> [@mantine/core] Modal: Prevent overlay from sitting on top of scrollbar

- src/mantine-styles/src/tss/create-styles.ts
- src/mantine-styles/src/tss/utils/merge-class-names/merge-class-names.ts
Right now if you define a different key when you create a custom EmotionCache, it only changes in the serialized class "newkey-j45j320" with this small feature it would also change the prefix of the classes.
> Add cache key in classNames prefix

- docs/src/docs/core/Slider.mdx
- src/mantine-core/src/Slider/RangeSlider/RangeSlider.tsx
- src/mantine-core/src/Slider/Slider/Slider.test.tsx
- src/mantine-core/src/Slider/Slider/Slider.tsx
- src/mantine-demos/src/demos/core/Slider/Slider.demo.scale.tsx
- src/mantine-demos/src/demos/core/Slider/index.ts
Added a `scale` prop to mimic the functionality of the Slider for [Material UI](https://mui.com/material-ui/react-slider/#non-linear-scale) as requested by @rtivital in Discord [here](https://discord.com/channels/854810300876062770/887408088800448553/1016792289542148227).
> [@mantine/core] Slider: added scale prop

- src/mantine-core/src/ActionIcon/ActionIcon.story.tsx
- src/mantine-core/src/ActionIcon/ActionIcon.styles.ts
- src/mantine-core/src/ActionIcon/ActionIcon.test.tsx
- src/mantine-core/src/Button/Button.story.tsx
- src/mantine-core/src/Button/Button.styles.ts
- src/mantine-core/src/Button/Button.test.tsx
Fixes #2428 using adding a disabled style to button, as suggested by @UgurKacak.
I added simple storybook story, wrapping the states example in a fieldset disabled, all buttons should be disabled.
I have added a basic test as well, please provide feedback if you'd like to see more details on top.
> [@mantine/core] Button: Button is disabled when inside fieldset disabled

- src/mantine-utils/src/create-use-external-events/create-use-external-events.ts
#2436, when creating the closeModal function, the state is empty. But openModal will change the state modals, so I think we should update the handlers. Maybe there are other problems with this, I think we can update the handlers to get the latest state in all cases. Not sure of the best practice for this. Please give feedback or give improvement advice.
> [@mantine/utils] fix: closeModal not working with openModal

- package.json
- src/mantine-dropzone/package.json
- yarn.lock
The react-dropzone 14.2.2 version is fixing an issue on multiple MIME types accepted (https://github.com/react-dropzone/react-dropzone/pull/1207
> [@mantine/dropzone]: Dependencies: upgrade react-dropzone version

- docs/src/docs/core/Group.mdx
- src/mantine-core/src/Group/Group.styles.ts
- src/mantine-core/src/Group/Group.test.tsx
- src/mantine-core/src/Group/Group.tsx
Replaces the logic in `<Group />` that passes `className` as prop with a direct child selector.   This removes the requirement for Group children to accept `className` as a prop.
> [@mantine/core] Group: use css selectors to style children

- docs/src/docs/core/MultiSelect.mdx
- docs/src/docs/core/Select.mdx
- src/mantine-core/src/MultiSelect/MultiSelect.tsx
- src/mantine-core/src/Select/Select.tsx
- src/mantine-demos/src/demos/core/MultiSelect/MultiSelect.demo.searchableControlled.tsx
- src/mantine-demos/src/demos/core/MultiSelect/index.ts
- src/mantine-demos/src/demos/core/Select/Select.demo.searchableControlled.tsx
- src/mantine-demos/src/demos/core/Select/index.ts
Added controlled/uncontrolled searchValue prop into Select/MultiSelect: (Original discussion: https://github.com/mantinedev/mantine/discussions/2480)
> Controlled search in Select/MultiSelect

- src/mantine-core/src/List/ListItem/ListItem.tsx
By Removing the span we can now pass a div or any other JSX Element which can take the full width of the container the list is in.
Eg. I can put Text on the left side and have a button floated / flexed to the right side.
> [@mantine/core] ListItem:  Span limits the full width capability

- src/mantine-dates/src/components/TimeInputBase/TimeInputBase.styles.ts
The AM/PM label for `TimeInput` is getting reset to `auto` which causes it to be around 200px wide. If the TimeInput's width is shrunk to make it take up less extraneous space, that interior input bleeds outside of the container width. It seems that if this `width: auto` is removed then the input has a more reasonable size.
Motivation (copied over from Discord):
> I have a horizontal form with a TimeInput on the end. For some reason, the TimeInput uses up a lot of extra space:
> 
> https://codesandbox.io/s/long-pine-68z7s3?file=/src/App.tsx
>
> As a workaround, I've set its width property manually, and while that does make it take up less space in the <Group/>, it still bleeds outside of its container which is causing a horizontal scroll bar to show up:
> 
> …
> [@mantine/date] TimeInput: fix the width of the am/pm input

- docs/src/docs/others/nprogress.mdx
- src/mantine-nprogress/src/NavigationProgress.tsx
https://github.com/mantinedev/mantine/issues/2517
> [@mantine/nprogress] NavigationProgress: add progressLabel props

- package.json
- src/mantine-carousel/src/Carousel.tsx
- src/mantine-core/src/AppShell/Aside/Aside.tsx
- src/mantine-core/src/AppShell/HorizontalSection/HorizontalSection.tsx
- src/mantine-core/src/AppShell/Navbar/Navbar.tsx
- src/mantine-core/src/Checkbox/Checkbox.tsx
- src/mantine-core/src/Chip/Chip.tsx
- src/mantine-core/src/Grid/Grid.test.tsx
- src/mantine-core/src/Grid/Grid.tsx
- src/mantine-core/src/List/List.tsx
- src/mantine-core/src/Radio/Radio.tsx
- src/mantine-core/src/ScrollArea/ScrollArea.tsx
- src/mantine-core/src/Stepper/Stepper.tsx
- src/mantine-core/src/Switch/Switch.tsx
- src/mantine-core/src/Tabs/Tabs.tsx
- src/mantine-core/src/Timeline/Timeline.test.tsx
- src/mantine-core/src/Timeline/Timeline.tsx
- src/mantine-core/src/Tooltip/Tooltip.tsx
- src/mantine-dropzone/src/Dropzone.tsx
- src/mantine-prism/src/Prism/Prism.tsx
- src/mantine-prism/src/index.ts
- src/mantine-utils/src/ForwardRefWithStaticComponents.ts
- yarn.lock
closes #2504 
This PR refactors the utility type `ForwardRefWithStaticComponents` defined in `src/mantine-utils/src/ForwardRefWithStaticComponents.ts` in order to build a final type which match what forwardRef returns plus the static properties we want to expose.
Changing `ForwardRefWithStaticComponents` has helped to find that at least 15 components were affected with missing ref attribute in their type
Note that prettier had to be updated due to this issue https://github.com/prettier/prettier/issues/12640
> [@mantine/core] Fix types for components that forward ref

- package.json
- src/mantine-core/package.json
- src/mantine-core/src/Floating/FloatingArrow/FloatingArrow.tsx
- src/mantine-core/src/Floating/FloatingArrow/get-arrow-position-styles.ts
- src/mantine-core/src/Popover/Popover.context.ts
- src/mantine-core/src/Popover/Popover.story.tsx
- src/mantine-core/src/Popover/Popover.tsx
- src/mantine-core/src/Popover/PopoverDropdown/PopoverDropdown.tsx
- src/mantine-core/src/Popover/use-popover.ts
- src/mantine-core/src/Tooltip/Tooltip.story.tsx
- src/mantine-core/src/Tooltip/Tooltip.tsx
- src/mantine-core/src/Tooltip/use-tooltip.ts
- src/mantine-demos/src/demos/core/Popover/Popover.demo.arrow.tsx
- src/mantine-demos/src/demos/core/Popover/index.ts
- src/mantine-demos/src/demos/core/Tooltip/Tooltip.demo.arrow.tsx
- yarn.lock
> [@mantine/core] FloatingArrow: fix Arrow postion

- src/mantine-carousel/src/Carousel.styles.ts
- src/mantine-carousel/src/Carousel.tsx
- src/mantine-carousel/src/CarouselSlide/CarouselSlide.styles.ts
> [@mantine/carousel] Fix wrong carousel size calculation

- src/mantine-carousel/src/Carousel.tsx
Allow `auto` value for prop `slidesToScroll` 
Docs:  https://www.embla-carousel.com/api/options/#slidestoscroll
> Allow `auto` value for prop `slidesToScroll`

- src/mantine-hooks/src/use-previous/use-previous.test.ts
I stumbled across a typo in the test definition of use-previous :)
> [@mantine/hooks] Fix typo in use-previous test

- src/mantine-dates/package.json
My renovate configuration cannot group `@mantine/*` dependencies by source URL, since `@mantine/dates` missed the repository field
```json
{
"matchSourceUrls": ["https://github.com/mantinedev/mantine"],
"groupName": "mantine"
}
```
> Add repository field

- src/mantine-core/src/AppShell/AppShell.styles.ts
- src/mantine-core/src/AppShell/HorizontalSection/HorizontalSection.styles.ts
- src/mantine-core/src/AppShell/HorizontalSection/HorizontalSection.tsx
- src/mantine-core/src/Grid/Col/Col.styles.ts
- src/mantine-core/src/MediaQuery/MediaQuery.styles.ts
- src/mantine-core/src/SimpleGrid/SimpleGrid.styles.ts
- src/mantine-core/src/Stepper/Stepper.styles.ts
- src/mantine-styles/src/theme/functions/fns/breakpoints/breakpoints.test.ts
- src/mantine-styles/src/theme/functions/fns/breakpoints/breakpoints.ts
Closes #2550
Docs examples have not been affected, because used just for demo and are not critical in terms of actual breakpoints for the end user.
> Breakpoints usage fix

- src/mantine-core/src/List/List.styles.ts
- src/mantine-demos/src/demos/core/List/List.demo.nested.tsx
Issue #2494 
=> Keep the indentation with multiline contents of Item in List
Change in @mantine/core package at List/List.styles.ts component
Fix:
list-style-position: outside;
Reference:
https://www.w3schools.com/cssref/pr_list-style-position.asp
> Unordered list indent fix

- docs/src/docs/others/nprogress.mdx
- src/mantine-demos/src/demos/nprogress/NProgress.demo.usage.tsx
- src/mantine-nprogress/src/NavigationProgress.tsx
- src/mantine-nprogress/src/events.ts
- src/mantine-nprogress/src/index.ts
tried to resolve this issue https://github.com/mantinedev/mantine/issues/2359
the idea is instead of calling `resetNavigationProgress` when the page load is done which will set the progress to 0 and reset the progress, now can use `finishNavigationProgress` to set the progress to 100, so progress will fill the entire width and then set the `autoReset` to `true` to automatically reset the progress bar.
> [@mantine/nprogress] add finishNavigationProgress

- src/mantine-core/src/SegmentedControl/SegmentedControl.story.tsx
- src/mantine-core/src/SegmentedControl/SegmentedControl.tsx
Fix an edge-case in SegmentedControl with dynamic data, where going from 0 option to >0 option or the other way around would crash because of broken rule of hooks
> [@mantine/core] fixed hook issue in segmented-control

- src/mantine-core/src/MultiSelect/MultiSelect.tsx
- src/mantine-core/src/Select/Select.tsx
> [@mantine/core] Select: close dropdown on click

- docs/src/docs/hooks/use-local-storage.mdx
- Update `mac` to `MacOS`
- Add comma
- Fix spelling
> [docs] Minor tweaks to use-local-storage page

- docs/src/docs/theming/theme-object.mdx
- fix[docs]: corrected link for global styles guide in theme object page
> [docs] Fix link to go to global styles guide in theme object page

- docs/src/docs/others/nprogress.mdx
@mantine/nprogress doesn't have an exported member `finishNavigationProgress`, and from looking at previous examples, I believe it's supposed to be `completeNavigationProgress`
> [@mantine/nprogress] Fix Next.js usage example

- src/mantine-demos/src/demos/dropzone/Dropzone.demo.preview.tsx
- fix[docs] : add FileWithPath type imports for  image previews example in Dropzone
> [docs] import FileWithPath type in Dropzone for image previews example

- src/mantine-core/src/NumberInput/NumberInput.test.tsx
- src/mantine-core/src/NumberInput/NumberInput.tsx
Should resolve [#2633](https://github.com/mantinedev/mantine/issues/2633).
Replaces "toFixed" with a function that does the same and also removes trailing zeroes if its enabled.
> [@mantine/core] NumberInput: implement parsePrecision function

- src/mantine-core/src/Popover/use-popover.ts
Add [limiter](https://floating-ui.com/docs/shift#limiter) to shift middleware which prevents detachment from its target element
Reference to #2688
> [@mantine/core] Popover: fixed issue with popover/menu not staying in place

- docs/src/docs/theming/theme-object.mdx
- src/mantine-core/src/Image/Image.story.tsx
- src/mantine-core/src/Image/Image.tsx
Addressing #2631 
Add div around ImageIcon for a responsive placeholder.
> [@mantine/core] Image: Add div around placeholder

- docs/src/docs/hooks/use-timeout.mdx
- src/mantine-hooks/src/use-timeout/use-timeout.test.ts
- src/mantine-hooks/src/use-timeout/use-timeout.ts
Issue discussed here - https://discord.com/channels/854810300876062770/1029643292431892491/1029643292431892491
As of now, setTimeout callback function is called without any parameters. I found it to be useful when these parameters can be pased from start() function.
> [@mantine/hooks] use-timout: Add parameters for callback function

- src/mantine-core/src/Image/Image.story.tsx
- src/mantine-core/src/Image/Image.tsx
Remove height from `Image` root style.
Now storybook demo can see this error directly，I also test when container is less than fixed image height, placeholder also work fine.
> [@mantine/core] Image: fix figcaption overflow with removed height from root style.

- src/mantine-core/src/Rating/Rating.tsx
Quickfix for #2762. 
However, this component seems prone to other errors related to how value and fractions interact with each other and should be reviewed more extensively.
> [@mantine/core] Rating: Fix count and fractions parameters to accept integers only.

- docs/src/docs/core/TransferList.mdx
- src/mantine-core/src/TransferList/RenderList/RenderList.tsx
- src/mantine-core/src/TransferList/TransferList.tsx
- src/mantine-demos/src/demos/core/TransferList/TransferList.demo.controlledSearch.tsx
- src/mantine-demos/src/demos/core/TransferList/TransferList.demo.customIcons.tsx
- src/mantine-demos/src/demos/core/TransferList/TransferList.demo.differentPlaceholders.tsx
- src/mantine-demos/src/demos/core/TransferList/TransferList.demo.placeholder.tsx
- src/mantine-demos/src/demos/core/TransferList/index.ts
As discussed on Discord, a few improvements to the `TransferList` component:
- `transferIcon` and `transferAllIcon` for customising the icons. The props take a component with a reversed props to allow handling both lists correctly.
- `placeholder` prop that is used in place of `nothingFound` if query is empty. If `placeholder` is omitted, `nothingFound` is used in its place
- `searchPlaceholder`, `nothingFound` and `placeholder` can now take a tuple instead of a single value, to customize each panel independently. A single value can still be passed, in which case it's applied to both panels.
- `searchValues` and `onSearch` props allowing to control the searches
> [@mantine/core] add controlled search and per-list wording to transfer-list

- src/mantine-core/src/Popover/Popover.tsx
As discussed on discord, this adds memoization for `reference` and `floating` functions in popover
> [@mantine/core] fixed preact infinite loop in popover

- src/mantine-core/src/FocusTrap/FocusTrap.test.tsx
- src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts
This PR resolves #2726.
Turns out that `restoreAria.current();` was simply not called on unmount; this has now been changed.
Furthermore, I fixed an additional issue where aria-hidden attributes would only be applied on the first render, but would not update after that. This was caused by https://github.com/mantinedev/mantine/blob/f7da1459fba6284e23ff57f3e839e691bbb8e980/src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts#L16 After the first render, `ref.current` would already hold the node and aria attributes would not be reapplied again.
Finally, I added a test to `FocusTrap.test.tsx` which makes sure aria-hidden is added and removed. I'll be the first to admit it is kinda ugly but I could not find a better version. Also tested it manually with storybook - components like `Modal` or …
> [@mantine/hooks] use-focus-trap: Fix aria-hidden

- src/mantine-hooks/src/use-idle/use-idle.ts
Improve typing of events option to useIdle hook. This change allows for a better development experience, verifying code-time typing and making it easier to find correct events.
> [@mantine/hooks] use-idle: improves typing of events options

- src/mantine-core/src/Floating/FloatingArrow/FloatingArrow.tsx
- src/mantine-core/src/Floating/FloatingArrow/get-arrow-position-styles.ts
- src/mantine-core/src/Popover/Popover.context.ts
- src/mantine-core/src/Popover/Popover.story.tsx
- src/mantine-core/src/Popover/Popover.tsx
- src/mantine-core/src/Popover/PopoverDropdown/PopoverDropdown.tsx
- src/mantine-core/src/Tooltip/Tooltip.story.tsx
- src/mantine-core/src/Tooltip/Tooltip.tsx
- src/mantine-demos/src/demos/core/Tooltip/Tooltip.demo.arrow.tsx
Adding support for borderRadius css property with `arrowRadius` prop to Tooltip and Popover arrows.
> [@mantine/core] Add arrowRadius support to Tooltip and Popover

- src/mantine-rte/src/components/RichTextEditor/RichTextEditor.story.tsx
- src/mantine-rte/src/components/RichTextEditor/RichTextEditor.styles.ts
- src/mantine-rte/src/components/Toolbar/Toolbar.styles.ts
Respect theme `defaultRadius` for:
1. Tooltip input
2. Tooltip button
3. Mention
4. Toolbar actions
Even though `Popover` component respects it by default, I skipped adding default radius to Quill's tooltip as there is no way to change it afterwards.
> [@mantine/rte]: Respect `defaultRadius` from `MantineProvider`.

- docs/src/docs/core/CopyButton.mdx
Minor typo fix in CopyButton (No iframes section)
> Minor typo fix in CopyButton (No iframes section)

- src/mantine-styles/src/theme/GlobalStyles.tsx
Using `color-scheme` attribute instructs the browser which color scheme is used on the current web page to help it in rendering interface (e.g. scroll bars) in appropriate mode. It's really missing piece right now, just feel the difference:
| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/198038267-73c28ec8-01d9-430f-a047-013d4a688138.png) | ![image](https://user-images.githubusercontent.com/4408379/198038166-0dbb78b4-cff2-4a16-8534-4e74846e3a28.png) |
> [@mantine/styles] Add support for `color-scheme` attribute

- src/mantine-core/src/Pagination/Pagination.styles.ts
`font-weight` is removed as it didn't affect the boldness before but it does now.
> [@mantine/core] Pagination: Respect `font-family` from theme.

- docs/src/docs/core/Button.mdx
- src/mantine-core/src/Button/Button.styles.ts
- src/mantine-core/src/Button/Button.tsx
- src/mantine-demos/src/demos/core/Button/Button.demo.loadingConfigurator.tsx
- src/mantine-styles-api/src/styles-api/Button.styles-api.ts
Added a center option for Button loaderPosition
> Button loader position center

- src/mantine-demos/src/demos/core/Menu/Menu.demo.usage.tsx
https://mantine.dev/core/menu/#usage
The code provided at above link looks like this:
This PR removes unwanted `,` after `Delete My Account` button.
> [docs] remove `,` from `Menu` Demo

- src/mantine-demos/src/demos/core/PasswordInput/PasswordInput.demo.validation.tsx
Updated the docs for [PasswordInput Validations example](https://mantine.dev/core/password-input/#invalid-state-and-error) from "Incorrect email" to "Incorrect password" to match the code example
> PasswordInput: Fix validations Example doc typo

- src/mantine-core/src/List/ListItem/ListItem.tsx
#2146 makes a pull request that removes the `<span>` tag around the `{children}` in `ListItem.tsx` This causes an overflow to happen in the `ListItem`, as represented in the image below. In this pull request, I re-added the `<span>` tags.
Before (from MantineUI, it overflows in to 2 lines):
After (my own personal project, it stays on one line):
> Added <span> tag around {children} in ListItem.tsx

- src/mantine-form/src/FormProvider/FormProvider.tsx
`createFormContext` function in `FormProvider.tsx` was returning `UseForm<Values>` without `TransformValues`. This pr adds `UseForm<Values, TransformValues>`
> [@mantine/form] Add TransformValues type for createFormContext

- src/mantine-hooks/src/use-local-storage/create-storage.ts
> [@mantine/hooks] use-local-storage: return undefined instead of empty string

- src/mantine-hooks/src/use-scroll-into-view/use-scroll-into-view.ts
Currently, useScrollIntoView returns a memoized callback that always refers to the params passed during the first render of the calling component, so calling with dynamically computed params, e.g. useScrollIntoView({ offset: someVariable }) will memoize the offset passed during the first render. If the component re-renders, any new offset passed is ignored.
Aditionally, 'scrollableRef.current' is an invalid dependency, see [https://epicreact.dev/why-you-shouldnt-put-refs-in-a-dependency-array/](https://epicreact.dev/why-you-shouldnt-put-refs-in-a-dependency-array/)
> Fix useScrollIntoView ignoring parameter changes

- scripts/docgen/docgen-parser.ts
- src/mantine-core/src/Box/style-system-props/extract-system-styles/extract-system-styles.ts
> [@mantine/core] Add `right` system prop to extracted system styles and remove from docs.

- src/mantine-core/src/Radio/Radio.story.tsx
- src/mantine-core/src/Radio/Radio.tsx
Allows overriding the size of a specific radio button when used in `Radio.Group`.
Fixes configurator demo in the `Radio` page: https://mantine.dev/core/radio/#usage.
> [@mantine/core] Radio: Respect `Radio`'s `size` parameter over context.

- src/mantine-core/src/Modal/Modal.story.tsx
- src/mantine-core/src/Modal/Modal.tsx
As discussed in #2890 and in the Discord, this PR fixes a bug where the modal would close when you mouse down in the modal but drag the mouse outside before releasing it. I've added a story which shows this working, even when the modal content uses portals.
The fix also doesn't cause a regression in #2669.
> Fix bug when dragging mouse outside

- src/mantine-core/src/InlineInput/InlineInput.styles.ts
When a component is passed as label then it appears on the bottom right of the component like  Checkbox, Switch or Radio component, added inline flex on InlineInput labelWrapper class to fix this issue
> [@mantine/core] Adjust Inline input label while passing component as label

- src/mantine-core/src/Slider/Marks/Marks.tsx
- src/mantine-core/src/Slider/Marks/is-mark-filled.test.ts
- src/mantine-core/src/Slider/Marks/is-mark-filled.ts
- src/mantine-core/src/Slider/Track/Track.tsx
Fix for https://github.com/mantinedev/mantine/issues/2877
Let me know if you need any changes :)
> [@mantine/core] Slider: fix issue #2877 mark fill inverted slider

- src/mantine-core/src/ColorPicker/ColorPicker.tsx
- src/mantine-core/src/ColorPicker/converters/converters.ts
- src/mantine-core/src/ColorPicker/converters/parsers.ts
- src/mantine-core/src/ColorPicker/types.ts
- src/mantine-demos/src/demos/core/ColorInput/ColorInput.demo.formatsConfigurator.tsx
- src/mantine-demos/src/demos/core/ColorPicker/ColorPicker.demo.formatsConfigurator.tsx
This PR adds a new color format to both color picker and color input. Both #rrggbbaa and #rgba are supported, as defined in https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color. 
(Didn't expect I'd have enough time to finish this today, but here we are)
> Add hexa format to ColorPicker

- docs/src/docs/core/Tabs.mdx
Fixing a typo in the `Uncontrolled Tabs` section of the docs.
> [docs] Fix typo in Tabs documentation

- src/mantine-core/src/MultiSelect/MultiSelect.tsx
It seems that wrapperRef in Multiselect component is defined and attached to a dom element, but it's not actually being used
> [@mantine/core] MultiSelect: remove unneccessary wrapper ref

- src/mantine-core/src/Drawer/Drawer.test.tsx
- src/mantine-core/src/Drawer/Drawer.tsx
As per [discussion](https://github.com/mantinedev/mantine/discussions/3016), added `id` to `Drawer` to allow `aria-` attributes on title and body of `Drawer`. 
Unlike `Modal`, I did not apply the `baseId` directly, but use it only for generating `titleId` and `bodyId`. This now passes an axe DevTools scan 
Added a test to check that passing `id` gets sent to title and body of `Drawer`
> [@mantine/core] Drawer: Add id for aria- attributes

- src/mantine-dropzone/src/Dropzone.tsx
Add a new prop to the `<Dropzone />` component that receives a function that is called on any file drop. 
This callback function will receive two arguments, the accepted files, and the rejected ones.
This solves the following issue: https://github.com/mantinedev/mantine/issues/3003
> [@mantine/dropzone] Add onDropAny prop

- src/mantine-tiptap/src/RichTextEditor.tsx
- forward ref to avoid ref warning in mantine tip tap editor
> [@mantine/tiptap]: add forward ref to mantine tip tap editor

- src/mantine-core/src/Stepper/Step/Step.styles.ts
fixes issue https://github.com/mantinedev/mantine/issues/3060
minHeight:"auto" result 0px on overflow-y 
by look I think this intended for hide the separator. 
so by display none the last item separator works good.
> [@mantine/core] Stepper: Fix vertical last step

- src/mantine-carousel/src/Carousel.tsx
Included a fix to make sure the indicator count is updated based on the value of slidesToScroll
Fixes: #3057
> [@mantine/carousel] Carousel: fixed carousel indicator not changing when slidesToScroll value is changed

- docs/src/docs/changelog/5-0-0.mdx
Hi! Website of Tabler Icons is https://tabler-icons.io, not tablericons.com - this site is not connected with my project :) 
You can verify it here: https://github.com/tabler/tabler-icons
Paweł, author of Tabler Icons 
btw, great project! If you need any extra icon to your framework give me a ping :)
> Update url to Tabler Icons website

- src/mantine-dropzone/src/Dropzone.tsx
Add getFilesFromEvent and validator props to the Dropzone component, both are methods that React Dropzone supports
The Dropzone component a getFilesFromEvent prop that enhances the handling of dropped file system objects and allows more flexible use of them e.g. passing a function that accepts drop event of a folder and resolves it to an array of files adds plug-in functionality of folders drag-and-drop.
Though, note that the provided getFilesFromEvent fn must return a Promise with a list of File objects (or DataTransferItem of {kind: 'file'} when data cannot be accessed). Otherwise, the results will be discarded and none of the drag events callbacks will be invoked.
In case you need to extend the File with some additional properties, you should use …
> [@mantine/dropzone] Add the getFilesFromEvent and validator props

- docs/src/docs/changelog/5-9-0.mdx
fixing appshell & use hotkeys links broken in change log 
app-shell : from ```https://mantine.dev/core/```  to  ```https://mantine.dev/core/app-shell```
use hotkeys : from ```https://mantine.dev/hooks/use-hot-keys``` to ``` https://mantine.dev/hooks/use-hotkeys ```
> [docs] fix changlog component links

- src/mantine-core/src/Table/Table.styles.ts
Fixed the style issues with table component. There are multiple issues with borders when we use the table component with different props such as striped, withBorder or withColumnBorders.
@mantine/core
[x] When we use withColumnBorders and rowSpan, the border left is not visible of the cells which are now in front of the rowSpan cell. (This is fixed by using borderRight instead of borderLeft for the cells)
[x] When we use rowSpan and rowspaned cell reaches the last row, the unexpected border bottom is added to the last row. (This is fixed by using borderTop for the rows instead of borderBottom)
[ ] When we use striped, striping works well but when the rowspan is used along, the user might expect the striping to be applied to the cells in front of the rowspan cell regarded as one row. (This …
> [@mantine/core] Table: Fix wrong styling with borders and rowspan

- src/mantine-core/src/TypographyStylesProvider/TypographyStylesProvider.styles.ts
Add a vertical line to blockquote in the TipTap editor by updating TypographyStylesProvider to have border-left property on blockquote.
> [@mantine/core] TypographyStylesProvider: Add borderLeft to blockquote.

- src/mantine-form/src/types.ts
Union types were incorrectly distributed when computing validation functions. This was not visible for the most classic unions, those including `undefined` and `null`, because Mantine's codebase is not in strict mode.
In strict mode, if the type of a value includes `null` or `undefined` in a union, it will get incorrectly distributed, as `undefined` and `null` will be inferred independently.
To avoid that, I wrap the `Value` inferred type into `NonNullable` before checking it against Array and Record cases. This prevents early distribution of the `Value` inferred type since the check is not directly against it. 
It is safe since `NonNullable` will get rid of `undefined` and `null`, which would be "false" in those checks anyway (not an Array, not a Record), so the comparison is still …
> [@mantine/form] fix type inference of validation for union types

- src/mantine-core/src/Floating/FloatingArrow/FloatingArrow.tsx
- src/mantine-core/src/Floating/FloatingArrow/get-arrow-position-styles.ts
- src/mantine-core/src/Floating/index.ts
- src/mantine-core/src/Floating/types.ts
- src/mantine-core/src/Popover/Popover.context.ts
- src/mantine-core/src/Popover/Popover.tsx
- src/mantine-core/src/Popover/PopoverDropdown/PopoverDropdown.tsx
- src/mantine-core/src/Tooltip/Tooltip.tsx
- src/mantine-demos/src/demos/core/Menu/Menu.demo.positionConfigurator.tsx
- src/mantine-demos/src/demos/core/Tooltip/Tooltip.demo.configurator.tsx
- src/mantine-demos/src/shared/floating-position-data.ts
This MR adds a `arrowPosition?: 'side' | 'center'` prop to Tooltip and Popover (and components inheriting from Popover).
`'side'` is the previous behavior, where arrow sticks to the side of the tooltip in `end` and `start` position, but it not correctly placed when the dropdown is shifted to stay in the viewport.
`'center'` is the newer behavior, where arrow tries to center itself to the target, but ends up aligned to the "wrong" side if the tooltip is smaller than the target.
> [@mantine/core] add a prop to choose how to position floating arrow

- src/mantine-hooks/src/use-hash/use-hash.ts
Two bugs fixed:
* If you `setHash` to something that doesn't start with "#" it would be reflect that temporarily in `hash`
* `setHashValue` was being called multiple times (one in the listener and the set hash) resulting in the multiple renders
Result:
* `setHash` only rerenders the page once.
* `hash` consistently starts with '#'
> [@mantine/hooks] Fixing `use-hash` extra rerendering issue

- src/mantine-core/src/Image/Image.test.tsx
- src/mantine-core/src/Image/Image.tsx
If you render an Image component with a valid src, then update the src prop to null, the placeholder does not render. With this fix, the placeholder will be properly rendered when the component updates.
> [@mantine/core] Image: Fix image component update bug with placeholder

- src/mantine-form/src/validate/validate-field-value.test.ts
- src/mantine-form/src/validate/validate-field-value.ts
This is the current behavior
```
// 'parent.path.precise' is in error.
form.isValid() // false
form.isValid('parent.path') // true  
form.isValid('parent.path.precise') // false
```
This is the wanted behavior
```
// 'parent.path.precise' is in error.
form.isValid() // false
form.isValid('parent.path') // false  
form.isValid('parent.path.precise') // false
```
**Current**
`validateFieldValue` receives the path used in `form.isValid('path.to.check')` and verifies if it match an exact key.
**Fixed**
`validateFieldValue` parses the path used in `form.isValid('path.to.check')` with `Array.prototype.split` and verifies each path indexes for a match with keys in error.
> [@mantine/form] validate-field-value: parent path validation

- src/mantine-form/src/tests/dirty.test.ts
- src/mantine-form/src/types.ts
- src/mantine-form/src/use-form.ts
By computing the isDirty only on demand using deep comparison of the `values` state, it removes many bugs related to `isDirty` and nested fields. Manually managing a dirty state parallel to the values state was very much bug prone, considering all the possible updates to form values that can occur.
~Disclaimer: by doing this we loose 2 functionalities `initialDirty` and `setDirty`. IMHO the pros outweighs the cons, but I am curious to see what the community thinks.~ Fixed ✅ 
Fixes:  https://github.com/mantinedev/mantine/issues/3001 and https://github.com/mantinedev/mantine/issues/2937
> [@mantine/form] useForm: fix isDirty for list fields

- docs/src/docs/others/dropzone.mdx
- src/mantine-demos/src/demos/dropzone/Dropzone.demo.enableChildPointerEvent.tsx
- src/mantine-demos/src/demos/dropzone/index.ts
I raised this question on Discord as it's not documented. This PR document Enables child pointer events with an example for Dropzone.
> [docs] Update Dropzone docs for Enable child pointer event

- docs/src/docs/hooks/use-hotkeys.mdx
- docs/src/docs/others/spotlight.mdx
- src/mantine-hooks/src/use-hotkeys/use-hotkeys.ts
- src/mantine-spotlight/src/SpotlightProvider.tsx
- src/mantine-spotlight/src/use-spotlight-shortcuts/use-spotlight-shortcuts.ts
As per here: https://github.com/mantinedev/mantine/discussions/3043
apologies if i missed something
> [@mantine/hooks] use-hotkeys: Add ability to specify tags to ignore

- docs/src/docs/core/RingProgress.mdx
- src/mantine-core/src/RingProgress/RingProgress.story.tsx
- src/mantine-core/src/RingProgress/RingProgress.test.tsx
- src/mantine-core/src/RingProgress/RingProgress.tsx
- src/mantine-core/src/RingProgress/get-curves/get-curves.test.ts
- src/mantine-core/src/RingProgress/get-curves/get-curves.ts
- src/mantine-demos/src/demos/core/RingProgress/RingProgress.demo.rootColor.tsx
- src/mantine-demos/src/demos/core/RingProgress/index.ts
Pr for discussion #3147
Adds the `rootColor` property to the RingProgress which can be used to define the color of the root curve.
> [@mantine/core] RingProgress: Add rootColor property

- src/mantine-tiptap/src/RichTextEditor.tsx
As mentioned in this issue https://github.com/mantinedev/mantine/issues/3124, current implementation has missing types for Tiptap editor static components (generic and controls component). 
So, added types for all those components with ForwardRefWithStaticComponents utility type
> [@mantine/tiptap]: Add missing ref type for Tiptap editor static components

- src/mantine-styles/src/tss/create-styles.ts
By making this change, a user can click on the className to go to the original definition. Like clicking on `classes.wrapper`, it'll go to the object where `wrapper` was defined. Also renaming `wrapper` will rename it from all the places
> types: make createStyle go to original definition

- docs/src/docs/theming/mantine-provider.mdx
- src/mantine-core/src/Text/Text.styles.ts
- src/mantine-core/src/Text/Text.tsx
This PR updates the getLineClamp function to behave like how Tailwind or Bootstrap works.
There is also a case for changing the getLineClamp function to truncate as it's more descriptive.  Also perhaps something like:
```
<Text truncate>Foo foo foo foo</Text> 
```
> Foo foo foo foo...
As a default (1 line) option, but then 
```
<Text truncate={3}>
Foo foo foo foo
Foo foo foo foo
Foo foo foo foo
</Text>
``` 
>Foo foo foo foo
>Foo foo foo foo
>Foo foo foo foo...
To support the 3 line truncate.
It's a breaking change but something to think about for Mantine 6?  🤔
> Update getLineClamp in Text.styles.ts to support 1 liner

- docs/src/docs/core/Stepper.mdx
- src/mantine-core/src/Stepper/Step/Step.tsx
- src/mantine-core/src/Stepper/Stepper.tsx
- src/mantine-demos/src/demos/core/Stepper/Stepper.demo.allowNextStepsSelect.tsx
- src/mantine-demos/src/demos/core/Stepper/Stepper.demo.stepFragmentComponents.tsx
- src/mantine-demos/src/demos/core/Stepper/index.ts
As discussed on Discord, this PR adds some flexibility to Stepper's API:
- Adds a `allowSelectNextSteps` props on Stepper, defaults to `true` to match current behavior. When false, clicking is disabled by default on upcoming steps.
- Adds a `StepFragmentComponent` type for all props currently accepting a React.Node. This is a component that receives the current step index as props, allowing the use of reusable templates easily.
I added some demos, don't hesitate to ask for changes in them if they are not useful enough!
> [@mantine/core] improve Stepper API

- docs/src/docs/form/validation.mdx
- src/mantine-demos/src/demos/form/Form.demo.superstruct.tsx
- src/mantine-form/src/index.ts
- src/mantine-form/src/resolvers/superstruct-resolver/superstruct-resolver.ts
add superstructResolver for useForm validation
- [superstruct](https://github.com/ianstormtaylor/superstruct)
> [@mantine/form] Add superstruct support

- .github/workflows/pull_request.yml
- Currently, the `yarn` cache in the `pull_request` always misses. The total time to install dependencies take ~2 minutes.
- This PR fixes this issue by using the latest `setup-node@v3`.
- With the new cache, it takes ~30 seconds to download the cache, and ~1 minute 10 seconds to install the dependencies. So in total it saves 20 seconds. It's not a huge improvement because the cache size is very large and it takes a while to download.
- Also there are no more deprecated `set-output` / `save-state` command warnings.
- Please note that the cache will only start to work on the second run. So on this PR, the installation time will remain the same. But here is a screenshot of subsequent runs:
> [core] Update yarn cache in github action

- docs/src/docs/core/Container.mdx
`padding` is not an accepted component prop for Container.
> [@mantine/docs] Update Container documentation to remove outdated component prop

- docs/src/docs/core/BackgroundImage.mdx
It tripped me up so I thought worth fixing for others.  "below" indicates content displayed after content, while "behind" indicates content displayed under content.
> Change from "below" to "behind"

- src/mantine-spotlight/src/Spotlight/Spotlight.tsx
Hey, it would be awesome to have the ability to override search input size via searchInputProps on Spotlight/SpotlightProvider 🙏
Checked locally, also verified in Storybook, test/types passing ☑️
(Mantine is great btw!)
> [@mantine/spotlight] Allow overriding search input size

- src/mantine-core/src/Stack/Stack.tsx
There is no `top` property for `justify-content`. I search elsewhere and didn't found other occurrence.
> [@mantine/core] Stack: Fix default justify property

- docs/src/docs/core/Stepper.mdx
- src/mantine-core/src/Stepper/Stepper.test.tsx
- src/mantine-core/src/Stepper/Stepper.tsx
- src/mantine-demos/src/demos/core/Stepper/Stepper.demo.allowStepSelect.tsx
- Fixes #3335
- Adds a few tests to prevent this from happening in the future
- Updates Stepper docs with an example of a common usecase for allowStepSelect 
This is my first contribution to the repo so feel free to roast me if something isn't up to the standards :)
> [@mantine/core] [docs] Fix allowStepSelect regression

- src/mantine-hooks/src/use-fullscreen/use-fullscreen.ts
add `webkitEnterFullscreen` method on `enterFullScreen` function to support `ios devices`;
> fix(hooks) : update `use-fullscreen`;

- src/mantine-core/src/InlineInput/InlineInput.styles.ts
The problem with `inline-flex` was only visible on `Switch`. Nothing changes on `Checkbox` and `Radio`. 
Let me know if I missed something.
closes #3295
> [@mantine/core] InlineInput: Replace display inline-flex by flex

- src/mantine-modals/src/ModalsProvider.tsx
- src/mantine-modals/src/reducer.ts
Closes #3289
Made the logic simpler and not assume that the closed modal is the last in the stack.
> [@mantine/modals] Fixed closeModal async logic

- docs/src/docs/core/TransferList.mdx
- src/mantine-core/src/TransferList/RenderList/RenderList.tsx
- src/mantine-core/src/TransferList/TransferList.tsx
- src/mantine-demos/src/demos/core/TransferList/TransferList.demo.transferAllMatchingFilter.tsx
- src/mantine-demos/src/demos/core/TransferList/index.ts
Adds the `transferAllMatchingFilter` prop to `TransferList` that, when true, makes it so clicking the `transfer all` button transfers only items that match the current search.
Resolves #3430
> [@mantine/core] TransferList: add `transferAllMatchingFilter` prop

- package.json
- src/mantine-core/package.json
- src/mantine-core/src/Floating/use-floating-auto-update.ts
- src/mantine-core/src/Popover/Popover.context.ts
- src/mantine-core/src/Popover/use-popover.ts
- src/mantine-core/src/Tooltip/TooltipFloating/use-floating-tooltip.ts
- src/mantine-core/src/Tooltip/TooltipGroup/TooltipGroup.tsx
- src/mantine-core/src/Tooltip/use-tooltip.ts
- yarn.lock
issue: https://github.com/mantinedev/mantine/issues/3376
> [@mantine/core] Dependency: migrate `@floating-ui/react-dom-interactions` to `@floating-ui/react`

- src/mantine-core/src/Pagination/Pagination.tsx
This fixes issue #3441 where passing `spacing={0}` defaults to the fallback
> [@mantine/core] Pagination: Added zero spacing support

- src/mantine-form/src/resolvers/zod-resolver/zod-resolver.ts
I had a situation where a wrong & invalid data was being passed to the zodResolver as the schema argument.
This makes the zodResolver schema parameter to require the safeParse property.
I don't see a way to type test this in Mantine repo. In my codebase it didn't throw false negatives and it did complain properly.
> [@mantine-form] zodResolver: Make schema parameter typesafe

- src/mantine-dates/src/components/DateRangePicker/DateRangePicker.tsx
openDropdownOnClear would still open dropdown on DateRangePicker when set to false
> [@mantine/dates] Fix openDropdownOnClear on DateRangePicker

- docs/src/docs/changelog/6-0-0.mdx
Fix props typo from `transitionDuration` → `transitionProps.transition` to `transitionDuration` → `transitionProps.duration`
> [docs] Fix props typo

- src/mantine-hooks/src/use-disclosure/use-disclosure.ts
Avoid re-render when using disclosure functions.
Use callbacks and the functional version of the "set" of the state to avoid re-render in effects that depend on
"open", "close" or "toggle" function of disclosure.
Something like this 
```js
const [opened, {open}] = useDisclosure(false);
useEffect(()=> {
open();
},[open]);
```
the effect was re-run when the opened value changed, which is wrong
> [@mantine/hooks] use-disclosure

- src/mantine-modals/src/ModalsProvider.tsx
- src/mantine-modals/src/reducer.ts
This PR fixes some issues regarding multi modal handling.
- `closeModal()` crashed when providing an invalid id
- If only one modal was left calling `closeModal()` would close this modal regardless whether the given id is correct
- `closeModal()` assumed that the given modal is the topmost one and therefore modified the state accordingly. This might lead to a not topmost modal suddenly popping up
The fixes now introduce a more defensive approach by checking for validity and not making these assumptions.
> [@mantine/modals] Fix various issues regarding usage assumptions

- src/mantine-core/src/MultiSelect/MultiSelect.tsx
The [documentation](https://mantine.dev/core/multi-select/#dropdown-position) claims `MultiSelect` uses `"flip"` as the default for `dropdownPosition`, but is instead `undefined`.
> [@mantine/core] MultiSelect: Add missing default for dropdownPosition

- docs/src/docs/core/Drawer.mdx
The size prop controls the width of the drawer for left/right positionned drawers and height for top/bottom drawers. I've corrected a tiny issue where the documentation contradicted itself by saying the size controlled the width for a top drawer
> [docs] Fix erroneous drawer size prop documentation

- src/mantine-core/src/Input/use-input-props.ts
Fix: `useInputProps`
The reason for the type error here is not clear to me, but I gave it a type through `as` and it worked.
I hope this is what you expect.
> fix: update useInputProps to strong type

- docs/src/docs/others/tiptap.mdx
According to the https://github.com/ueberdosis/tiptap/releases/tag/v2.0.0-beta.210 , `@tiptap/pm` is needed now.
> doc(others): add `@tiptap/pm` to tiptap installation

- docs/src/docs/core/Switch.mdx
Fixing issue highlighted here: https://github.com/mantinedev/mantine/issues/3599
> [docs] Fixed import typo for Switch.Group

- src/mantine-core/src/Tooltip/Tooltip.story.tsx
- src/mantine-core/src/Tooltip/TooltipFloating/TooltipFloating.tsx
- src/mantine-core/src/Tooltip/TooltipFloating/use-floating-tooltip.ts
Fixes #3605 and adds a Storybook demo for it.
> [@mantine/core] Tooltip.Floating: Fix `disabled` behaviour

- src/mantine-core/src/Floating/use-floating-auto-update.ts
- src/mantine-core/src/Popover/Popover.story.tsx
Popover drop-down not following target.
Issue link: [https://github.com/mantinedev/mantine/issues/3351](https://github.com/mantinedev/mantine/issues/3351)
`autoUpdate` in `useFloatingAutoUpdate` wasn't registering the `floating.refs.floating` changes
> [@mantine/core] Popover: fix floating-auto-update issue

- src/mantine-modals/src/reducer.ts
This fixes #3409.
Originally when closing the **last** modal the action `CLOSE_ALL` got called which cleaned the `modals` state but kept the last one around in `current`. Therefore when rendering the `ModalsProvider` the last modal had been rendered but with a closed state.
In my previous PR I changed this behaviour as in my opinion when a modal has been closed it shouldn't stay in `current` - even if it's the last one. Therefore during rendering the `ModalsProvider` a closed modal with default props got rendered instead. However because closing the modal isn't immediate because of an exit transition this default modal rendering was visible.
Therefore this PR partially reverts the last one and makes sure the last modal always will be kept around (not only in `CLOSE_ALL` but also in …
> [@mantine/modals] Fix jumping of centered modals on close (#3409)

- src/mantine-core/src/AppShell/HorizontalSection/HorizontalSection.styles.ts
the fallback value should have an unit (px or rem), otherwise it won't work.
> fix(core): appshell section height calculation

- docs/src/docs/core/ColorInput.mdx
- docs/src/docs/core/ColorPicker.mdx
Noticed that I hadn't updated the documentation text when I added support for 'hexa' format in ColorPicker and ColorInput - this PR fixes that.
> [docs] Update available color formats

- docs/src/docs/core/ColorInput.mdx
- docs/src/docs/core/ColorPicker.mdx
- src/mantine-modals/src/Modals.story.tsx
- src/mantine-modals/src/ModalsProvider.tsx
- src/mantine-modals/src/reducer.ts
Fixes #3623.
Reason was that the `onClose()` method got called before the new state has been applied therefore it resulted in an endless loop.
Swapping the method execution order unfortunately isn't enough as it's not clear when React does apply the state update.
So I moved some logic to the reducer because it will be run for each action in sequence.
In earlier versions this usecase didn't crash the whole application because the methods might not use the current modal state. Therefore an endless loop couldn't occur. However it also lead to other issues:
See this sandbox for `v5.10.0`:
https://codesandbox.io/s/modals-state-issue-3623-ppqfjr?file=/src/App.tsx
Open the console, open some modals and then close them.
Despite all modals being closed only one callback will be called.
So despite …
> [@mantine/modals] Fix endless `closeAll()` loop

- docs/src/docs/pages/about.mdx
This patch adds the v5 link to the about page, as suggested on [discord](https://discord.com/channels/854810300876062770/1048155338152624198/1081226402990403686)
> [docs] Add link to v5 docs to About page

- src/mantine-dates/src/components/DateTimePicker/DateTimePicker.tsx
Bug: 
DateTimePicker: time input disappears when dropdown is closed with month level
https://imgur.com/a/0UzuS0f
Fixed:
> [@mantine/core] DateTimePicker: Fix TimeInput not rendering sometimes

- src/mantine-core/src/Floating/FloatingArrow/FloatingArrow.tsx
- src/mantine-core/src/Floating/FloatingArrow/get-arrow-position-styles.ts
- src/mantine-core/src/InlineInput/InlineInput.tsx
- src/mantine-core/src/Popover/PopoverDropdown/PopoverDropdown.tsx
- src/mantine-core/src/Slider/RangeSlider/RangeSlider.tsx
- src/mantine-core/src/Slider/Slider/Slider.tsx
- src/mantine-core/src/Slider/Thumb/Thumb.tsx
- src/mantine-core/src/Tooltip/Tooltip.tsx
- src/mantine-styles/src/theme/functions/fns/darken/darken.test.ts
- src/mantine-styles/src/theme/functions/fns/darken/darken.ts
- src/mantine-styles/src/theme/functions/fns/lighten/lighten.test.ts
- src/mantine-styles/src/theme/functions/fns/lighten/lighten.ts
- src/mantine-styles/src/theme/functions/fns/rgba/rgba.test.ts
- src/mantine-styles/src/theme/functions/fns/rgba/rgba.ts
Hi :) 
As discussed on Discord, here are some quick fixes for some regressions I found while updating my app from v5 to v6. I
I implemented each of them in individual commits; if you prefer I split those in individual PRs, I can too.
Here is a list of what's fixed:
- Arrow function positioning was using the raw pixel value, while the size of the arrow was using the new rem() helper. So arrow was not positioned correctly if the rem value was anything other than 16. Fixed by using rem() on positioning too.
- Still arrow function : removed the extra offset when there is a border, see comment below. I think a display might have changed from content box to border box somewhere.
- fn.rgba is used in more places, preventing CSS variables to be passed to some `color` props, instead it used a …
> Fix a couple regressions found on V6 + Improve Slider hover UX

- docs/src/docs/changelog/6-0-0.mdx
- docs/src/docs/pages/changelog.mdx
Fixed typos as noted in:
https://discord.com/channels/854810300876062770/861521000985264138/1081796340029337713
> [docs] Fix verison 5 link typo

- src/mantine-core/src/Alert/Alert.styles.ts
- src/mantine-core/src/Alert/Alert.tsx
Fix Alert content overlap with close button when no title present and `withCloseButton={true}`
https://discord.com/channels/854810300876062770/1081152194591592598/1081152194591592598
> [@mantine/core] Alert: Fix content overlap 

- src/mantine-core/src/Anchor/Anchor.styles.ts
After updating to v6.0.0, the "dimmed" color prop of the Anchor component was not reflected.
Reproduction: https://codesandbox.io/s/icy-star-25zg89?file=/src/App.tsx
Therefore, I added a check if the color prop is "dimmed" or not.
After this PR:
I'm enjoying the update to version 6! Thank you!
> [@mantine/core] Anchor: Fix dimmed color not working

- src/mantine-core/src/Transition/use-transition.ts
Solves #3626
Stores the `transitionDuration` in `useTransition`'s state so that upon changing its value, the element's `transition-duration` style property gets updated as well.
Below you'll find a short video of the `duration` (200ms) and `exitDuration` (2000ms) after applying this fix.
https://user-images.githubusercontent.com/20128985/222743880-095fb575-18f5-4783-b639-b28fe0bf2f18.mov
> [@mantine/core] Transition: Update transition duration when unmounting

- src/mantine-dates/src/components/CalendarHeader/CalendarHeader.tsx
The button for changing level is `disabled` but it's still kept in tab order when `maxLevel` should remove it. You can try it out here: https://mantine.dev/dates/date-picker/#max-level
The DatePicker at the right has `maxLevel="month"`, so the level change button is disabled, but it still has `tabIndex={0}` and is therefore kept in tab order.
This worked correctly in v5.x: https://v5.mantine.dev/dates/calendar/#level-change
Let me know if I should create an issue for this instead of opening a PR!
Repro here: https://codesandbox.io/s/silly-forest-fcvs01?file=/src/App.tsx
> [@mantine/dates]: CalendarHeader: Remove disabled level change button from tab order

- src/mantine-core/src/SegmentedControl/SegmentedControl.styles.ts
Fixes https://github.com/mantinedev/mantine/issues/3669!
`SegmentedControl` only sets the left border color of the `ref-control` class to transparent if horizontal, or only the top border color if vertical.
> [@mantine/core] SegmentedControl: fixed transparent border color

- src/mantine-core/src/Drawer/DrawerRoot/DrawerRoot.tsx
Drawer default styles props not working correctly.
I found that it was not retrieving the default styles props of Drawer, but instead retrieving the default styles of Modal.
After fixing the typo, it worked correctly.
> [@mantine/core] Drawer: Fix typo from Modal to Drawer

- src/mantine-core/src/ScrollArea/ScrollArea.tsx
`viewportProps` was missing for ScrollArea.Autosize so I added it. Never tested it but obviously will.
> [@mantine/core] ScrollArea.Autosize: A missing viewportProps property

- src/mantine-core/src/Floating/use-floating-auto-update.ts
- src/mantine-core/src/Popover/PopoverDropdown/PopoverDropdown.tsx
- src/mantine-core/src/Popover/use-popover.ts
- src/mantine-core/src/Tooltip/use-tooltip.ts
This PR fixes #3643, by removing the need of a `key` prop on the Popover floating element, instead relying on Floating UI `autoUpdate` call with an added dependency on `position`.
> [@mantine/core] Popover: fix dropdown position without key prop

- src/mantine-core/src/Switch/Switch.styles.ts
- src/mantine-core/src/Switch/Switch.tsx
Fixes #3736.
Please keep the following things in mind:
- This can be seen as a breaking change because it applies `position: relative` to the whole component and therefore also to the user-definable label. This would be relevant if e. g. a user uses some label element with `position: absolute`
- Avoiding the breaking change would mean wrapping the `input` element. However this breaks other internal styles that rely on this structure
- I haven't used the styles apis quite much so I don't know if my solution is good. Feel free to point me to a better solution or adjust it yourself.
> [@mantine/core] Switch: fix jumping of viewport on click

- src/mantine-core/src/Popover/Popover.story.tsx
- src/mantine-core/src/Popover/use-popover.ts
When changing a component from uncontrolled to controlled.  It no longer fires the (onOpen and onClose) events based on the open state.
This PR resolves that.  
I have also updated the storybook to showcase this.
One thing to be aware about:
Line 60 of use-popover.ts:
```
const onClose = () => {
options.onClose?.();
setOpened(false);
};
```
Since my change depends on useDidUpdate.  I am worried that options.onClose will fire twice.  But it seems that is not the case.  Maintainer, please confirm.  
Thanks!
> Mirror uncontrolled events to controlled component

- src/mantine-core/src/PinInput/PinInput.story.tsx
- src/mantine-core/src/PinInput/PinInput.test.tsx
- src/mantine-core/src/PinInput/PinInput.tsx
PinInput now uses useEffect when _value changes so that onComplete if present is called on last input instead of needing an additional key stroke. Corrosponding test and storybook component have been added too.
> [@mantine/core] PinInput: onComplete fires correclty - issue 3714

- src/mantine-hooks/src/use-hash/use-hash.ts
setHashValue is being set to `hash` again instead of the `newHash` value. Sometimes it worked, but this fixes an issue where when hashchange is triggered the hash is reset to the old hash.
> Fix use-hash: wrong value being set on hashchange

- docs/src/docs/core/Pagination.mdx
The `Pagination` component does not have a value prop as the docs show. I updated the `Pagination` component example in the docs to use the correct `page` prop.
> Update Pagination.mdx to use correct prop name.

- src/mantine-demos/src/demos/core/Avatar/Avatar.demo.usage.tsx
Currently the sample code says that the fourth avatar component has radius="sm", but it looks the same as the other three avatars. This should fix that
> [docs] Update actual code to match displayed code

- src/mantine-core/src/Drawer/DrawerRoot/DrawerRoot.styles.ts
- src/mantine-core/src/ModalBase/ModalBaseHeader/ModalBaseHeader.styles.ts
This ensures that content does not visibly scroll over the header of the Modal and Drawer components.
> [@mantine/core] Modal & Drawer Header: fix content scrolling over the header 

- docs/src/components/Layout/LayoutInner.tsx
For any page in docs site: 
- `?search` will open spotlight search.
- `?search=button` will open spotlight search, prefilled with `button`.
E.g. on local site:
Should work on all pages in docs site.
> [docs] Auto open spotlight

- src/mantine-styles/src/theme/MantineCssVariables.tsx
Adds `--mantine-breakpoints-xs` (and the rest of the sizes) to the list of exported CSS variables.
> [@mantine/styles] Expose theme breakpoints as css variables

- src/mantine-core/src/ModalBase/ModalBase.tsx
This fixes the leaks mentioned in #3702 #3731 by acknowleding that `ModalBase` can receive `Modal` props.
> [@mantine/core] Modal: Fix prop to DOM leak #3731 #3702

- src/mantine-hooks/src/use-timeout/use-timeout.test.ts
- src/mantine-hooks/src/use-timeout/use-timeout.ts
Solves #3789
1. Wrap both `clear()` and `start()` functions with the `useCallback()` hook so that they won't change across re-renders (unless they have to, e.g. `start()` depends on `delay`).
2. Add missing test case for `autoInvoke` effect when `delay` changes.
3. Correct `autoInvoke` effect dependencies to include `clear()` and `start()` as well as `options.autoInvoke`.
As far as I could check, the above changes shouldn't affect anyone using this hook. However, there's a separate commit (see point 3) that changes `autoInvoke` effect dependencies and I'm not 100% sure of relying on `options.autoInvoke`. People shouldn't really change that setting after the first render, so I'd think it's safe, but I'm open to suggestions.
> [@mantine/hooks] use-timeout: Memoize `clear` and `start` functions

- src/mantine-core/src/NumberInput/NumberInput.story.tsx
- src/mantine-core/src/NumberInput/NumberInput.test.tsx
- src/mantine-core/src/NumberInput/NumberInput.tsx
This fixes #3663 and #3729.
It's been quite a rework of the internal data handling so please have a closer look at it.
The key changes are:
- Only propagate new values via `onChange()` when bluring the component or using the increment/decrement functionality.
- Therefore while inputting some values nothing will be done to them.
- When using it in controlled mode the value won't change at all and the displayed text will reset as soon as `onChange()` gets called
- The `value` emitted in `onChange()` now already respects precision and min/max.
- When setting a `value` that doesn't match the configuration (either because it's precision is higher than configured or it isn't within the min/max bounds) it will be displayed as is (so not rounded or clamped). However as soon as it has been changed …
> Issue 3663 fix number input

- docs/src/docs/guides/remix.mdx
The React team released new `renderToPipeableStream` documentation in their large docs release recently
> Update renderToPipeableStream docs link

- src/mantine-core/src/Autocomplete/Autocomplete.tsx
Proposed fix for #3866
Moved aria attributes and role attribute from wrapper div to input so that JAWS and other screen readers will pick up on the Autocomplete's label correctly. I'm not at all an expert on aria stuff, so please make sure what I've done is correct.
> [@mantine/core] Autocomplete: Fix for input has no accessible name a11y error

- docs/src/docs/core/MultiSelect.mdx
- src/mantine-core/src/MultiSelect/filter-data/filter-data.test.ts
- src/mantine-core/src/MultiSelect/filter-data/filter-data.ts
- src/mantine-demos/src/demos/core/MultiSelect/MultiSelect.demo.disableSelectedItemFiltering.tsx
- src/mantine-demos/src/demos/core/MultiSelect/index.ts
Solves #3877 
It enables the `disableSelectedItemFiltering` feature for `searchable` inputs by always setting the `filter` function's `selected` parameter to `false`.
This works for the internal `defaultFilter` and should work for any custom `filter` function that relies on the `selected` parameter to remove from the list.
Lastly, I added some tests to assert:
- `disableSelectedItemFiltering` when input is `not searchable`
- `disableSelectedItemFiltering` when input is `searchable` (uses `defaultFilter`)
- `filter` function's `selected` paramater is always`false` when `disableSelectedItemFiltering` and `searchable` are enabled (generic test for any custom `filter` function)
> [@mantine/core] MultiSelect: Fix `disableSelectedItemFiltering` prop not working for `searchable` input

- src/mantine-core/src/Floating/index.ts
- src/mantine-core/src/Floating/types.ts
- src/mantine-core/src/Popover/Popover.story.tsx
- src/mantine-core/src/Popover/Popover.tsx
- src/mantine-core/src/Popover/use-popover.ts
This PR adds the full axis ability to popover.
See the docs here: https://floating-ui.com/docs/offset
Instead of the default Y axis, now the dev can specify both X and Y axis.  This is beneficial in case there needs to be more precise adjustments for UI.
An additional story has been added to reflect this change.
This should not be a breaking change because it retains the default number param.
If this PR is accepted, then I will also update the docs to mirror the change.
> Improve Popover offset to include all Axis

- src/mantine-dates/src/components/Month/Month.tsx
- src/mantine-dates/src/components/Month/get-date-in-tab-order/get-date-in-tab-order.test.ts
- src/mantine-dates/src/components/Month/get-date-in-tab-order/get-date-in-tab-order.ts
I noticed no date is added to tab order when:
- No date in month is selected
- Current date is not in month
- First non-disabled date in month is hidden because of `hideOutsideDates={true}`
Can be tested here in February 2023 for example: https://mantine.dev/dates/date-picker/#hide-outside-dates. This fixes it.
As a side-note, I was expecting be to be able to use `!getDateControlProps?.(date)?.outside` instead of `isSameMonth(date, month)`, but turns out `outside` is never set here: https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/hooks/use-dates-state/use-dates-state.ts#L158 Maybe that could be something to look into in the future?
> [@mantine/dates]: Consider hideOutsideDates when determining tab order

- src/mantine-dates/src/components/DecadeLevelGroup/DecadeLevelGroup.tsx
- src/mantine-dates/src/components/MonthLevelGroup/MonthLevelGroup.tsx
- src/mantine-dates/src/components/YearLevelGroup/YearLevelGroup.tsx
- src/mantine-dates/src/tests/it-handles-controls-keyboard-events.tsx
- src/mantine-dates/src/tests/it-handles-month-keyboard-events.tsx
- src/mantine-dates/src/utils/handle-control-key-down.ts
Fixes https://github.com/mantinedev/mantine/issues/3662.
This changes keyboard navigation behavior pretty drastically.
- ArrowRight moves focus to the closest succeeding non-disabled cell. If current focus is on last non-disabled cell in row, focus is moved to first non-disabled cell in next row.
- ArrowLeft moves focus to the closest preceding non-disabled cell. If current focus is on first non-disabled cell in row, focus is moved to last non-disabled cell in previous row.
- ArrowDown moves focus to closest succeeding non-disabled cell in the same column.
- ArrowUp moves focus to closest preceding non-disabled cell in the same column.
The other major change is behavior when multiple pickers are rendered side-by-side. Take this one as an example: …
> [@mantine/dates]: Change tab order behavior to match native date pickers

- src/mantine-dates/src/hooks/use-uncontrolled-dates/use-uncontrolled-dates.test.ts
- src/mantine-dates/src/hooks/use-uncontrolled-dates/use-uncontrolled-dates.ts
Fixes #3919.
- For uncontrolled components it resets the internal value to `defaultValue`
- For controlled components it expects the `value` to be compatible to `type`. However it also outputs an error it that's not the case
> Issue 3919 fix datepicker type changing

- src/mantine-core/src/NumberInput/NumberInput.story.tsx
- src/mantine-core/src/NumberInput/NumberInput.test.tsx
- src/mantine-core/src/NumberInput/NumberInput.tsx
Fixes #3979 and #3982.
Based on #3756 I reworked the data flow handling to be more in line with other components again.
This means `onChange()` will be triggered on input again but still outputs validated and clamped data.
I've also added a test for the expectation that `onChange()` and `onBlur()` won't get called in the same run which might lead to the `onBlur()` handler working with old data in case it's using data stored via `useState()` hook.
Maybe that's something that should be added to all input components.
I also removed the `higherPrecision` handling introduced in #3756. For controlled components it allowed display values with higher precision than allowed. Like:
```tsx
<NumberInput precision={0} value={1.23} />
```
would output `1.23`. However when changing the value manually …
> Issue 3979 fix numberinput form validation

- src/mantine-core/src/MultiSelect/MultiSelect.styles.ts
The issue seemed to be that effective lineHeight calculation resulted in `34px` for `sm` size - which was bigger than input itself (22px) which caused cursor and text to be pushed down.
Removing this style fixed the issue - as would lowering down lineHeight to 22px or below - but this seemed to not have any visual effect even when I played with lower values like 10px or 1px.
Removal did not affect `Size XS Line Height` story and looks correct on `Multiple Rows`. Tested on both Safari and Chrome.
Fixes https://github.com/mantinedev/mantine/issues/3968
It's my first PR here, hopefully adhered to all standards - let me know if I could improve anything, cheers!
> [@mantine/core] MultiSelect: Fix lineHeight styles affecting input on Safari

- src/mantine-dates/src/components/DateInput/DateInput.tsx
> [@mantine/dates] DateInput: Add missing props from DatePicker

- src/mantine-dates/src/utils/handle-control-key-down.ts
When switching focus between dates with ArrowUp/ArrowDown, page is scrolling. Test it here: https://mantine.dev/dates/date-picker/#usage
This prevents that page scrolling.
> [@mantine/dates]: Prevent page scrolling on ArrowUp/ArrowDown keyboard navigation

- docs/src/docs/core/Accordion.mdx
in the section of [Default opened items](https://mantine.dev/core/accordion/#default-opened-items), second code example was wrong. 
when set `defaultValue` as an array of strings, should be add `multiple` prop as `true`.
> [docs] Fix missing `multiple` prop on example code at Accordion

- src/mantine-core/src/Slider/Marks/Marks.styles.ts
- src/mantine-core/src/Slider/RangeSlider/RangeSlider.tsx
- src/mantine-core/src/Slider/Slider/Slider.tsx
- src/mantine-core/src/Slider/SliderRoot/SliderRoot.styles.ts
- src/mantine-core/src/Slider/SliderRoot/SliderRoot.tsx
- src/mantine-core/src/Slider/Thumb/Thumb.tsx
- src/mantine-core/src/Slider/Track/Track.styles.ts
- src/mantine-core/src/Slider/Track/Track.tsx
- src/mantine-demos/src/demos/core/Slider/Slider.demo.marks.tsx
- src/mantine-styles-api/src/styles-api/Slider.styles-api.ts
Fix some Slider behavior:
- Remove unneeded stopPropagation on mouseDownCapture on the thumb, making it buggy in Preact
- Fix marks label behavior: now you can only click on them to set the value, but they do not trigger hover effect or drag
- Fix area in which drag and hover effect detection is active, to include the whole root without the marks label, by introducing a secondary level container "trackContainer" handling the events
> [@mantine/core] fix slider drag and hover behavior

- docs/src/docs/others/modals.mdx
@rtivital 
Thanks for this awesome library :)
While modifying some multi step modals I was caught out by the non-obvious fact that dynamic content is not supported in content modals via the modals manager API.
see #751 and [this discussion](https://github.com/mantinedev/mantine/discussions/2527#discussioncomment-3703202)
It would be fantastic to be able to have dynamic content - but perhaps it is too difficult.
My use case would be using modals for small, multi step configuration interfaces that make sense to be in modals.
Anyway - here is a note so that others do not get caught out.
Cheers
B
> [docs] note re dynamic content in Modals Manager

- src/mantine-core/src/ColorInput/ColorInput.tsx
This pull request adds the `onChangeEnd` event to the `ColorInput` component when the user selects a colour using the eyedropper.
> [@mantine/core] ColorInput: Trigger `onChangeEnd` event with eyedropper

- src/mantine-core/src/ColorInput/ColorInput.test.tsx
- src/mantine-core/src/ColorInput/ColorInput.tsx
Fixes #3280.
`ColorInput` currently triggers an additional `onChange()` after `onBlur()`. This conflicts with form validations that have a disabled `onChange()` validation because in this case the error will be resetted immediately.
@rtivital Can you describe the reason behind this additional `onChange()` trigger and `fixOnBlur`? Maybe it can be removed completely.
> [@mantine/core] ColorInput: execute `onChange()` before `onBlur()` #3280

- src/mantine-dropzone/src/index.ts
I'm currently needing to add `react-dropzone` as a dependency to my project in order to import the `FileRejection` type. I'd love to be able to import it directly from `@mantine/dropzone`, just like I'm able to import `FileWithPath`.
Cheers!
> [@mantine/dropzone]: Export FileRejection type

- src/mantine-styles/src/theme/utils/merge-theme/merge-theme.test.ts
- src/mantine-styles/src/theme/utils/merge-theme/merge-theme.ts
Related issues:
#4050 
Instead of merge breakpoints, use breakpoints from override if provided (with an additional check for required keys).
> [@mantine/core] Separate handle breakpoints override in mergeTheme

- src/mantine-core/src/Menu/Menu.story.tsx
- src/mantine-core/src/Menu/Menu.tsx
**I have already raised the issue and hope it can be helpful~**
The following is a description of the problem：
When Menu uses the toggle method provided internally by useDisclosure to control unfolding and collapsing, it can lead to dependency rendering exceeding the maximum update depth and falling into a dead loop. The following is the error message from the console: "Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either does not have a dependency array, or one of the dependency changes on every render.
> [@mantine/core]Menu: Removing code that may cause dead loops 

- src/mantine-dates/src/components/Calendar/pick-calendar-levels-props/pick-calendar-levels-props.ts
- src/mantine-dates/src/components/DatePickerInput/DatePickerInput.test.tsx
You can see that `data-with-spacing="true"` remains when setting `withCellSpacing={false}` here: https://codesandbox.io/s/compassionate-stonebraker-zq7n52?file=/src/App.tsx
I included a test that failed before the change and passes after.
> [@mantine/dates] DatePickerInput: Support withCellSpacing prop

- src/mantine-core/src/MultiSelect/MultiSelect.tsx
inject   index to ValueComponent
> [@mantine/core] MultiSelect:  inject index to ValueCopmonent

- src/mantine-hooks/src/use-local-storage/create-storage.ts
- src/mantine-hooks/src/use-local-storage/use-local-storage.test.tsx
Fixes #3987 
---
- Adds `key` to the dependency array for the `useEffect` responsible for setting the initial local storage value to support a dynamic `key`. Tested with both client-side and server-side(Remix) rendering. 
- Adds general tests for `useLocalStorage`, including the above use case
> [@mantine/hooks] Support dynamic key for `useLocalStorage`

- src/mantine-dates/src/components/Calendar/Calendar.tsx
These properties must not be included in `...others` and should be passed to MonthLevelGroup.
> [@mantine/dates] Fixed passing nextIcon and previousIcon props

- src/mantine-hooks/src/use-focus-trap/create-aria-hider.ts
- src/mantine-hooks/src/use-focus-trap/use-focus-trap.test.tsx
- src/mantine-hooks/tsconfig.json
Fixes #4079 
---
This addresses an edge case with `useFocusTrap` that can cause the [cleanup function](https://github.com/mantinedev/mantine/blob/42df57f888be86f1fa9adb5b1ca64546c3991dfe/src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts#L82-L89) returned by `createAriaHider` to run after another `useFocusTrap` instance has operated on the same set of root nodes. This is due to the `createAriaHider` function being called when the [callback ref](https://github.com/mantinedev/mantine/blob/42df57f888be86f1fa9adb5b1ca64546c3991dfe/src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts#L30-L66) returned by `useFocusTrap` is invoked, which will run before the cleanup function if two elements that utilize `useFocusRoot` are toggled simultaneously. An example of this behavior can be found in …
> [@mantine/hooks] Focus trap identity

- src/mantine-core/src/Slider/Marks/Marks.styles.ts
- src/mantine-core/src/Slider/Marks/Marks.tsx
- src/mantine-core/src/Slider/RangeSlider/RangeSlider.tsx
- src/mantine-core/src/Slider/Slider/Slider.tsx
- src/mantine-core/src/Slider/SliderRoot/SliderRoot.styles.ts
- src/mantine-core/src/Slider/Track/Track.styles.ts
- src/mantine-core/src/Slider/Track/Track.tsx
As discussed in #4112 and Discord, here are the relevant fixes to Slider:
- Remove fixed height from the `root` container to allow style props such as padding to have correct effect on the document flow
- Add fixed height to the `trackContainer` instead
- Change offsets linked to thumb size to actually use `thumbSize` instead of only `size`
> [@mantine/core] fix slider styles linked to thumb size

- src/mantine-core/src/Menu/Menu.story.tsx
- src/mantine-core/src/Menu/Menu.test.tsx
- src/mantine-core/src/Popover/Popover.test.tsx
- src/mantine-core/src/Popover/Popover.tsx
When clicking anywhere on the screen that is not a target, the Menu also performs opening and closing.
​https://codesandbox.io/s/nifty-curran-fy1nlu?file=/src/App.tsx
Based on my humble opinion, it may be caused by two reasons:
- The `dropdown`  is only hidden and has not been completely uninstalled, resulting in its lifecycle methods and other methods still existing.
- `clickOutside` is not controlled based on the `opened` state, so both the open and closed states will trigger `onClose`.
In version 6.0.8, in order for `Menu` to be properly controlled and simultaneously call `onClose` and `onOpen`, I made `clickOutside` call the `toggleDropdown` method of `Menu`, resulting in a situation where clicking on an external button can also control the switch state.
Here are the fixes I made: …
> Fix the issue where the Menu will open when clicking anywhere on the screen other than the target

- src/mantine-core/src/Select/SelectItems/SelectItems.styles.ts
When there are multiple spaces in the middle of a character, the space will be swallowed up
> fix(Select): add whiteSpace:pre  to SelectItem

- src/mantine-core/src/MultiSelect/MultiSelect.tsx
When `disableSelectedItemFiltering` is set to true, selecting the last item will move the focus to the second-to-last instead of keeping it on the last.
This is due to a workaround for selected-item detection needed in normal mode.
This PR changes the workaround: instead of handling it as an edge-case in `handleItemSelect`, I converted it into a rule in the render: `hovered` should never be greater than the last item's index.
This way if the item number does not change on select, the hovered value is not impacted.
> [@mantine/core] fix multi-select hovered item on last item select

- src/mantine-dates/src/components/Month/Month.tsx
- src/mantine-dates/src/components/WeekdaysRow/WeekdaysRow.tsx
- src/mantine-dates/src/components/WeekdaysRow/get-weekdays-names/get-weekdays-names.test.ts
- src/mantine-dates/src/components/WeekdaysRow/get-weekdays-names/get-weekdays-names.ts
- src/mantine-dates/src/tests/it-supports-weekdays-props.tsx
Extended `weekdayFormat` property to support function, similar to `yeaLabelFormat`. It allows us to either render a custom node or implement a format that does not support by dayJS library, like in our case, where the labels should be just the first letter of the weekday name.
> [@mantine/dates]: Support function as weekdayFormat prop

- docs/src/docs/core/Progress.mdx
- src/mantine-ds/src/Demo/types.ts
Closes https://github.com/mantinedev/mantine/issues/4101
Before this PR:
After this PR:
> [docs] Ensure `PasswordInputDemos.strengthMeter` example is correctly positioned

- docs/src/docs/core/SegmentedControl.mdx
- src/mantine-core/src/SegmentedControl/SegmentedControl.tsx
Since you can control the orientation of `<SegmentedControl>` with the `orientation` prop, it doesn't make sense to say to describe it as horizontal in the description.
Also improve some other documentation.
> [docs] Clarify docs for SegmentedControl

- src/mantine-dates/src/components/DatePicker/DatePicker.tsx
Fixed DatePicker props types by adding missing `CalendarSettings` which includes `CalendarHeaderProps`.
The component supports those props (such as `next/previousIcon`) and works correctly though. Just TS errors
> [@mantine/dates] Fixed DatePicker types

- src/mantine-core/src/Rating/StarSymbol/StarSymbol.styles.ts
I see the props color desc: Key of theme.colors or any CSS color value, yellow by default
so to fix to get the custom color #4245
> [@mantine/core] Rating: fix add custom color

- docs/src/docs/core/SimpleGrid.mdx
This pr aims to fix the SimpleGrid component docs page issue, which creates confusion about CSS grid and flexbox. 
A detailed explanation can be found in the issue #4203
> [docs] Update SimpleGrid component docs usage section

- src/mantine-core/src/ColorPicker/converters/parsers.test.ts
- src/mantine-core/src/ColorPicker/converters/parsers.ts
> [@mantine/core] ColorPicker: Fix rounding in rgba and hex parsing (#4154)

- src/mantine-demos/src/demos/dates/TimeInput/TimeInput.demo.picker.tsx
The `TimeInput` demo had "Click" twice in the text. This PR removes the extra "click" text.
> Remove extra 'click' text

- docs/src/docs/styles/style-props.mdx
I removed an extra closing brace `}` that was present.
> [docs] Fix typo in Style props page

- src/mantine-core/src/AppShell/AppShell.styles.ts
When the `navbarOffsetBreakpoint` and `asideOffsetBreakpoint` values in the `AppShell` component are set to the same value, only the aside padding is correctly overridden with `padding-right: 1rem`.
Therefore, I have made adjustments to ensure that `padding-left: 1rem;` is correctly applied as well. With this change, both the aside and navbar will have the intended padding.
Fixes #4269
> [@mantine/core] AppShell: Fix wrong padding when `navbarOffsetBreakpoint` and `asideOffsetBreakpoint` have the same value

- src/mantine-core/src/Image/Image.test.tsx
- src/mantine-core/src/Image/Image.tsx
> [@mantine/core] Image: Fix image alt overflow

- src/mantine-core/src/Table/Table.styles.ts
Ensure table stylings apply to immediate children only. This avoids things like the calendar pop-up nested inside of a `<Table/>` inheriting the styles of the parent.
> [@mantine/core] Table: Avoid style bleed

- src/mantine-core/src/MultiSelect/MultiSelect.tsx
- src/mantine-demos/src/demos/core/MultiSelect/MultiSelect.demo.hoverOnSearchChange.tsx
> [@mantine/core] MultiSelect: fix hoverOnSearchChange when creatable

- src/mantine-core/src/PinInput/PinInput.test.tsx
- src/mantine-core/src/PinInput/PinInput.tsx
This fixes https://github.com/mantinedev/mantine/issues/4432
- If the focus is on the last element and there is a value, hitting the backspace will remove the value and stay focused on that element.
- If the focus is on the last element and there is no value, hitting the backspace will shift the focus to the previous element.
- If the focus is on any input element except the last element, hitting the backspace will remove the value and shift the focus to the previous element. 
https://github.com/mantinedev/mantine/assets/45745778/eb125f31-00f0-40e8-ae09-d4861ced90d2
> [@mantine/core] PinInput: shift focus to prev element on backspace

- src/mantine-core/src/Slider/Slider/Slider.tsx
When updating the "onChange" property of a slider, the change was ignored and the old property was still used. This was caused by not adding the "setValue" to the dependency array.
> [@mantine/core] Slider: Fix onChange prop updates being ignored

- src/mantine-dates/src/components/DateInput/DateInput.tsx
This fixes https://github.com/mantinedev/mantine/issues/4481.
When `Calendar Dropdown` is open then the user clicks on the `clear` button, the following code won't run causing the input value to not be cleared. 
```
useDidUpdate(() => {
value !== undefined && !dropdownOpened && setInputValue(formatValue(value));
}, [value]);
```
So when user clicks on the `clear` button we also closes the `Calendar Dropdown` which fixes the issue. 
As other `Date` components, clicking the `clear` button closes the `Calendar Dropdown`, this should also make the behavior consistent across components.
> [@mantine/dates] DateInput: clear input value on clearButton click

- src/mantine-dates/src/components/PickerInputBase/PickerInputBase.tsx
This fixes #4467 by passing `inputProps.error` to `Input.Placeholder` to match the placeholder color.
> [@mantine/dates] PickerInputBase: Pass input error/invalid state to Input.Placeholder

- src/mantine-prism/src/Prism/Prism.styles.ts
- src/mantine-prism/src/Prism/Prism.test.tsx
This fixes https://github.com/mantinedev/mantine/issues/4429
Wrapping Prism within a `TypographyStylesProvider` that has a selector with the margin values:
```
<class> pre: {
marginTop: theme.spacing.md,
marginBottom: theme.spacing.md
}
```
has a higher specificity than Prism's selector with the margin set to 0
```
code: {
.......
marginTop: 0,
marginBottom: 0
}
```
this causes the margin styles from `TypographyStylesProvider` to be utilized by Prism's `pre` element and causes the copy button to move higher than it's normal position.
> [@mantine/prism] Prism: use higher specificity for pre element margin

- docs/src/docs/dates/DateInput.mdx
- src/mantine-dates/src/components/DateInput/DateInput.test.tsx
- src/mantine-dates/src/components/DateInput/DateInput.tsx
- src/mantine-demos/src/demos/dates/DateInput/DateInput.demo.clearable.tsx
Fixes #4524.
The change is a bit larger than I intended but I believe it makes the `clearable` and `allowDeselect` props more understandable:
* `clearable` controls whether the DateInput can be cleared (via the text field or the date picker)
* `allowDeselect` controls whether clicking on the existing date in the date picker clears the field (only applicable if clearable is set), defaults to true if `clearable` is set
If this is too much of a change, left me know and I'll revert it back to my original idea of just allowing `allowDeselect` to be manually set. The downside with this approach is that it can result in some weirdly inconsistent behaviour where the value can be cleared by clicking the date when `allowDeselect` is set and `clearable` isn't set.
> [@mantine/dates] DateInput: Separate clearable and allowDeselect logic

- src/mantine-dates/src/components/DatePickerInput/DatePickerInput.tsx
fix https://github.com/mantinedev/mantine/pull/4532
Sorry for submitting a pr with an error. 
props `defaultDate` should have a lower priority than `value`.
> fix: date input `defaultDate` displace `value`

- src/mantine-core/src/Avatar/AvatarPlaceholderIcon.tsx
Removes hardcoded `rem(15)` on width and height of `AvatarPlaceholderIcon` to allow it to scale properly with `Avatar` size and override with custom styles.
Addresses https://github.com/mantinedev/mantine/issues/4576
> [@mantine/core] AvatarPlaceholderIcon: Remove width and height

- src/mantine-core/src/Pagination/PaginationControl/PaginationControl.styles.ts
Fixes issue #4574. As a side note, `cursor: 'not-allowed'` becomes obsolete with the presence of `pointerEvents: 'none'` but I left it in because that seems to be the convention for the package.
> [@mantine/core] Pagination: Add disabled styles

- src/mantine-tiptap/src/controls/ColorPickerControl/ColorPickerControl.tsx
Updated ColorPickerControl.tsx to resolve the issue "Rich Text Editor's color picker now showing black color as default in dark color scheme"
Sorry this is my first pull request on an open source project I don't really know what I'm doing any pointers would be appreciated.
> [@mantine/tiptap] fixed default color of color picker from Rich Text Editor to change based on theme

- src/mantine-core/src/SegmentedControl/SegmentedControl.tsx
- src/mantine-core/src/Spoiler/Spoiler.tsx
- src/mantine-hooks/src/use-resize-observer/use-resize-observer.ts
When the Spoiler component is initially rendered, it doesn't know its content's size, so it doesn't show the "Show more" button. This was causing flickering and layout shifts.
https://github.com/mantinedev/mantine/assets/6034931/f253d153-4559-4a28-b7dc-d4334f9d5621
It is possible to know the initial size by implementing `useResizeObserver` hook slightly different. That is what I did.
Some remarks:
- Removed `useEffect` from the Spoiler component which was used for a computed property
- Having `ref.current` in the dependency array of `useEffect` is quite unreliable.
- `useResizeObserver` now returns a callback ref instead of mutable ref. Normally, this is an implementation detail and should not count as a breaking change.
- I had to modify some code in the `SegmentedControl` because it was …
> [@mantine/core] Spoiler: Fix control button flickering on rerender

- docs/src/components/Footer/data.ts
Fixed typos for the word "GitHub" in the footer of the docs. The spelling used was "Github" (with a lower-case "h") instead of the correct spelling "GitHub" (with an upper-case "H").
> [docs] Fix typos for "GitHub"

- docs/src/docs/theming/emotion-cache.mdx
When implementing Emotion Cache in our project, the `prepend` option caused some confusion and some missed visual bugs. The docs don't mention that you need to set `prepend: true`, if you need the custom cache to behave like the cache automatically generated by Mantine. This behavior only made sense when reading between the lines of the docs, this change aims to make it a little more obvious by adjusting the example code provided.
> [docs] Add prepend option to Emotion Cache example

- src/mantine-tiptap/src/controls/ColorPickerControl/ColorPickerControl.tsx
I added parentheses to fix the incorrect expression for `currentColor`. In the previous code, the expression will always returns `theme.colors.dark[1]` in dark mode and `theme.black` in light mode.
> [@mantine/tiptap] ColorPickerControl: fix incorrect color displayed

- src/mantine-core/src/Grid/Col/Col.tsx
- src/mantine-core/src/Grid/Grid.tsx
This PR will allow users to pass the `id` prop to the `Grid` and `Grid.Col` components, as mantine is already doing for other components.
I couldn't find a good reason why the `id` prop was removed from the props that are passed to the DOM element. If there is, feel free to disregard this PR, although in that case the TS types should probably reflect that.
> [@mantine/core] Grid: Pass `id` prop to dom element

- src/mantine-dates/src/components/PickerInputBase/PickerInputBase.tsx
Fixes https://github.com/mantinedev/mantine/issues/4730.
Sets useful accessible name on all date picker input components.
> [@mantine/core] Set correct accessible name on date picker input components

- src/mantine-core/src/InlineInput/InlineInput.tsx
> [@mantine/core] InlineInput: Fix InlineInput component does not receive padding when a value of 0 is passed into the label prop. 

- README.md
- docs/components/Footer/data.ts
It appears the `href` for many pages on the Mantine docs have changed with Mantine v7. Ex:
- `/pages/contributing` --> `/contribute`
- `/pages/about` --> `/about`
- ...
These haven't been updated in the README or footer in the Mantine documentation, so users clicking on these links would navigate to the 404 page. These are now updated in this PR.
It appears the root `/changelog` page does not exist anymore with Mantine v7, so the Previous Versions page `/changelog/previous-versions` is now used in place of that.
> Fix links in README and Footer in docs

- README.md
The redirect links on the README.md are not workingas intended due to the extra `/` in the links. The current URLs return 404.
Also: 
These pages do not exist in general: 
1. (https://mantine.dev/styles/create-styles/)
2. (https://mantine.dev/others/prism/)
3. (https://mantine.dev/guides/ssr/)
Hence, I did not change the links for the above, however, if you have a link that you would redirect to, I'll be happy to address it in the same PR.
> docs: fix readme redirect links

- src/mantine-demos/src/demos/core/Progress/Progress.demo.usage.tsx
In the [Mantine Documentation](https://mantine.dev/core/progress/), the code block says `animated` which has been changed to `animate`.
> Progress Demo | Changed Animated -> Animate

- src/mantine-core/src/components/Table/Table.module.css
Problem was on specificity, darker rows have styles that override the hover background change. Adding `!important` rule solved the problem by prioritizing hover.
> [@mantine/core] Fix table highlight doesn't work on striped dark rows

- docs/pages/theming/colors.mdx
- src/mantine-core/src/core/MantineProvider/theme.types.ts
This is needed to allow `MantineThemeColorsOverride` to be overwritten
> [@mantine/core] make MantineThemeColorsOverride an interface instead of type

- src/mantine-core/src/components/Select/Select.tsx
The select input isn't watching the `data` prop change after a value is already set, this will cause the underlying input to remain unchanged/blank. A simple case could be seen with something like this:
```ts
const value = "Foo";
const [options, setOptions] = useState([]);
useEffect(() => {
const optionsSetter = setTimeout(() => {
setOptions(["Foo", "Bar"]);
}, 1500);
return () => clearTimeout(optionsSetter);
});
return (
<Select data={options} value={value} />
);
```
By watching the optionsLockup in the useEffect dependencies it should catch updates to that data.
> [@mantine/core] Select: Fix search text not updating

- docs/pages/theming/mantine-provider.mdx
- docs/yarn.lock
Fixed typo in the  theming section for the MantineProvider. Added "a" before 'theme object' for better clarity and changed user to used to make it grammatically correct
> fixed typo in the docs

- src/mantine-core/src/core/MantineProvider/theme.types.ts
Similar to the `MantineThemeColorsOverride` issue  #4816, changed `MantineThemeOther` to interface to be overwritten
> [@mantine/core] Fix broken other theme override type

- src/mantine-core/src/components/Button/Button.module.css
I referred to the implementation in v6.
https://github.com/mantinedev/mantine/blob/cdf1179358c6d4591f5de76a2a41935ff4c91ec6/src/mantine-core/src/Button/Button.styles.ts#L138
Current:
This Pull Request:
If this was an intentional change from v6, please close this PR.
And thank you for the hard work on v7!
> [@mantine/core] Button: Fix disabled outline button style

- docs/yarn.lock
- src/mantine-core/src/components/Loader/Loader.module.css
- src/mantine-core/src/components/Loader/loaders/Dots.tsx
Updated Loader component 'dots' variant to match animation and style as close as possible to v6
https://github.com/mantinedev/mantine/assets/5589281/fe0f4bc7-7d13-40f3-9c98-7ab620d5338b
> [@mantine/core] Update dots loader component

- configuration/rollup/create-package-config.ts
- scripts/utils/generate-dts.ts
- src/mantine-carousel/package.json
- src/mantine-code-highlight/package.json
- src/mantine-colors-generator/package.json
- src/mantine-core/package.json
- src/mantine-dates-tests/package.json
- src/mantine-dates/package.json
- src/mantine-demos/package.json
- src/mantine-dropzone/package.json
- src/mantine-ds/package.json
- src/mantine-form/package.json
- src/mantine-hooks/package.json
- src/mantine-modals/package.json
- src/mantine-notifications/package.json
- src/mantine-nprogress/package.json
- src/mantine-spotlight/package.json
- src/mantine-store/package.json
- src/mantine-styles-api/package.json
- src/mantine-tests/package.json
- src/mantine-tiptap/package.json
- src/mantine-vanilla-extract/package.json
I have been experiencing issues with the v2 release of Remix and Mantine v7 (see https://discord.com/channels/854810300876062770/1066443903080869889/1153294961324851220). Since Remix v2 is now ESM-only by default, it apparently changed the interaction with the `@mantine/*` packages:
```
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'ColorSchemeScript' not found. The requested module '@mantine/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from '@mantine/core';
const { ColorSchemeScript, MantineProvider } = pkg;
at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
at …
```
> [core] Fix entrypoints for CJS and ESM modules

- src/mantine-dates/src/utils/get-timezone-offset.ts
When using @mantine/dates the following error throws:
```js
Error: Cannot find module '/Users/user/code/node_modules/.pnpm/@mantine+dates@7.0.1_@mantine+core@7.0.1_@mantine+hooks@7.0.1_dayjs@1.11.10_react-dom@18.2.0_react@18.2.0/node_modules/dayjs/plugin/utc' imported from /Users/user/code/node_modules/.pnpm/@mantine+dates@7.0.1_@mantine+core@7.0.1_@mantine+hooks@7.0.1_dayjs@1.11.10_react-dom@18.2.0_react@18.2.0/node_modules/@mantine/dates/esm/utils/get-timezone-offset.mjs
Did you mean to import dayjs@1.11.10/node_modules/dayjs/plugin/utc.js?
```
This is because of the missing .js when bare importing the plugins.
See https://nodejs.org/api/esm.html#esm_mandatory_file_extensions
and https://github.com/iamkun/dayjs/issues/1167 specifically …
> [@mantine/dates] Fix esm mandatory file extensions bug

- src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
- src/mantine-core/src/components/NumberInput/NumberInput.tsx
`NumberInput` value type will be based on initial value type. 
Fixes: #4912
Fixes: #4901
> [@mantine/core] NumberInput value type fix

- src/mantine-hooks/src/use-timeout/use-timeout.ts
Currently, `start` and `clear` have unstable references, so they change every render. This makes them hard to use in effects, and cause unnecessary rerenders. This PR fixes that with `useCallback`.
> [@mantine/hooks] use-timeout: Memoize returned callbacks

- src/mantine-core/src/components/Select/Select.story.tsx
- src/mantine-core/src/components/Select/Select.tsx
fixes #4909
`optionsLockup` needs to be memorized as they are used in a effect further down. otherwise the effect will be triggered each render - preventing search changes to take effect.
https://github.com/mantinedev/mantine/blob/7dc4a72ece31650761c8aae96756c10e628dc9c7/src/mantine-core/src/components/Select/Select.tsx#L179-L187
> [@mantine/core] Fix searchable select with controlled value

- package.json
- src/mantine-core/package.json
- yarn.lock
Fixes `Textarea` component when using Next.js edge runtime. 
The `Textarea` component was experiencing server-side rendering (SSR) failure when used with Next.js edge runtime. The error message returned was:
```
ReferenceError: document is not defined
at (../../node_modules/react-textarea-autosize/dist/react-textarea-autosize.browser.esm.js:100:0)
at (webpack/bootstrap:21:0)
at (../../node_modules/@mantine/core/cjs/components/Textarea/Textarea.js:6:23)
at (webpack/bootstrap:21:0)
at (../../node_modules/@mantine/core/cjs/components/JsonInput/JsonInput.js:8:15)
at (webpack/bootstrap:21:0)
at (../../node_modules/@mantine/core/cjs/index.js?4f1e:199:16)
at (webpack/bootstrap:21:0)
at (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.product …
```
> Update react-textarea-autosize to 8.5.3

- src/mantine-core/src/components/Button/Button.module.css
Fixes a problem you can see easily in the Mantine docs in dark mode, where the border radius of the overlay doesn't match the button's: https://mantine.dev/core/button/#loading-state
> [@mantine/core] Button: fix loading overlay default border radius

- docs/yarn.lock
- src/mantine-core/src/components/Spoiler/Spoiler.module.css
- src/mantine-core/src/components/Spoiler/Spoiler.tsx
- src/mantine-styles-api/src/data/Spoiler.styles-api.ts
Removed added margin-bottom when the Show more button is hidden
Fixes: #4910
> [@mantine/core] Spoiler: removed extra margin bottom when "Show more" is hidden

- src/mantine-demos/src/demos/core/Progress/Progress.demo.usage.tsx
Update the Progress component's Storybook to use the `animated` prop instead of `animate` from v6 which is [currently broken in the docs](https://mantine.dev/core/progress/).
> [docs] Progress: Fix animated prop in Storybook demo

- docs/yarn.lock
- src/mantine-dates/src/components/DateInput/DateInput.tsx
- src/mantine-hooks/src/use-focus-trap/scope-tab.ts
- yarn.lock
Fixes #4678
```js
import { findTabbableDescendants } from './tabbable';
export function scopeTab(node: HTMLElement, event: KeyboardEvent) {
const tabbable = findTabbableDescendants(node);
if (!tabbable.length) {
event.preventDefault();
return;
}
const finalTabbable = tabbable[event.shiftKey ? 0 : tabbable.length - 1];
const root = node.getRootNode() as unknown as DocumentOrShadowRoot;
let leavingFinalTabbable = finalTabbable === root.activeElement || node === root.activeElement;
// Handle the case of the active element being in a RadioGroup with the finalTabbable element
const activeElement = root.activeElement as Element;
const activeElementIsRadio =
activeElement.tagName === 'INPUT' && activeElement.getAttribute('type') === 'radio';
if (activeElementIsRadio) {
const activeRadioGroup = …
```
> Issue Fix: use-focus-trap doesn't handle Radio Groups well

- src/mantine-core/src/components/Select/Select.tsx
I was tracking down the issue mentioned in #4995 and discovered it was due to multiple renders caused by the useEffect hook.
Often times the `data` prop isn't a stable reference so using the `optionsLockup` which is derived from it in a useEffect was causing unnecessary renders. 
Instead, I have used the `selectedOption` in the dependency array which seems to be more stable even when `data` changes.
> [@mantine/core] Select: More stable useEffect dependency for search

- src/mantine-core/src/components/MultiSelect/MultiSelect.tsx
It looks like the functionality for this prop was missed, I have just copied the behaviour from the Select component.
> [@mantine/core] Implement selectFirstOptionOnChange for MultiSelect

- src/mantine-core/src/components/Rating/Rating.tsx
- src/mantine-core/src/components/Rating/RatingItem/RatingItem.tsx
Fixes #4399 
When using a touch device browsers will dispatch emulated mouse events which, in this case, will cause the `handleMouseLeave` callback to be called as soon as we click elsewhere. One of the ways to fix this is to prevent emulated events by preventing this behaviour in `onTouchStart` and `onTouchEnd`.
Read more about emulated events [here](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Using_Touch_Events).
Issue fixed:
https://github.com/mantinedev/mantine/assets/7091198/0c2b8566-b162-4d60-a09b-c1e291dd7966
I also noticed that when using the keyboard we are changing the rating when using arrow navigation and not waiting for the spacebar which IMO is not right, because we might just be passing by 🤷 ? I added this fix here but I can remove it if it doesn't fit. …
> [@mantine/core] Rating: Prevent emulated mouse events in touch devices

- src/mantine-core/src/components/FocusTrap/FocusTrap.test.tsx
Fixes the tests that blocked #4679, and #4856 was merged without. Ended up being a silly thing that blocked my PR for weeks 🙄 .
Unfortunately, `useFocusTrap` has a `setTimeout` before actually focusing on an element, so we need to add a `wait()` before each of these assertions. These two test cases will add about 60ms to the total run time of the test suite, so I'll leave it up to @rtivital to decide on their worth.
> [@mantine/core] Add tests for <FocusTrap /> using shift + tab

- src/mantine-core/src/components/TagsInput/TagsInput.tsx
Fixes #5016 
Pass `required` prop to `PillInput` component so that an asterisk is displayed when `required` prop is passed to `TagsInput`.
The `value` prop of `PillsInput.Field` is `_searchValue`, which is empty immediately after splitting.
Therefore, setting `required` will enable form validation even if tag (`_value`) is present.
To fix this, the condition of `required` in `PillsInput.Field` is set to `required && _value.length === 0`.
> [@mantine/core] TagsInput: Fix required prop behavior

- src/mantine-core/src/components/Radio/Radio.module.css
- src/mantine-core/src/components/Radio/Radio.tsx
- src/mantine-core/src/components/Radio/RadioIcon.tsx
Fixes #5018 
The problem was with invalid calculating width/height for icon, expect size=xl so i revert old sizes from v6
> [@mantine/core] Radio: fix radio icon size 

- src/mantine-dates/src/components/CalendarHeader/CalendarHeader.tsx
fix: https://github.com/mantinedev/mantine/issues/4971
first element for focus (.focus() method in use-focus-trap) was disabled causing this bug
> [@mantine/dates] Calendar: Fix focusing on disabled element

- src/mantine-core/src/components/Spoiler/Spoiler.tsx
I'd like to use Spoiler _just_ to reveal, not to hide again. However, passing `hideLabel={null}` leaves an unsightly gap below the Spoiler.
https://codesandbox.io/s/epic-waterfall-xkkzmv?file=/src/App.tsx
This PR fixes this issue by checking whether `spoilerMoreContent` is `null`.
> [@mantine/core] Spoiler: Avoid leaving a gap when label is null

- src/mantine-demos/src/demos/theming/Theming.demo.colorsOverride.tsx
In one example, the shown code in the docs did not match the corresponding components displayed in the docs. This commit fixes this problem.
> DOC: align shown code and components

- src/mantine-core/src/components/Text/Text.module.css
Fixes mantinedev#5190.
I compared with other components and it seems var `--_text-line-height` is missed in core text css configuration.
> [@mantine/core]: Text: Fix inline prop in css (mantinedev#5190)

- src/mantine-core/src/components/Popover/Popover.story.tsx
- src/mantine-core/src/components/Popover/Popover.types.ts
- src/mantine-core/src/components/Popover/use-popover.ts
Currently, if the `Popover.Dropdown` content is tall, there is no way to add scrollbars (overflow) properly as the dropdown overflows the page. Reproduction https://codesandbox.io/s/amazing-nobel-s6zqy8
This issue is supposed to be fixed by [size](https://floating-ui.com/docs/size) middleware in `floating-ui`. This PR fixes the issue by adding `size` option in `PopoverMiddlewares` which enables the `size` middleware, which in turn uses `availableWidth` and `availableHeight` per `floating-ui` docs.
I decided not to set `overflow: auto` automatically in `Popover.Dropdown` because in some places there might be a requirement to shrink the content and not to add scrollbars.
How to verify:
- `yarn storybook`
- Open http://localhost:6006/?path=/story/popover--size
- Click on the button and …
> Add "size" popover middleware to fix overflow issues in Popover.Dropdown

- docs/components/Footer/Footer.module.css
This PR updates styles for the docs footer so that the buttons at the bottom are not disappearing because of the reduced height
> Currently I have increased height by 60 pixels, but if that's not enough, it can be increased some more
Mobile breakpoint:
Tablet breakpoint:
> fix(docs): update footer styles

- src/mantine-spotlight/src/SpotlightSearch.tsx
related: https://discord.com/channels/854810300876062770/887408088800448553/1176006456332529714
---
Spotlight is not submitted when the enter key is pressed during IME input.
Tested on macOS 14.0.
> [@mantine/spotlight] Fix input bug with Japanese IME

- docs/pages/form/status.mdx
I fixed a typo in the documentation that referenced the `touched()` function, which has been removed in the latest version. Updated it to `isTouched()` to reflect the current function name.
> [@mantine/docs] fix: replace `form.touched()` by `form.isTouched()`

- docs/pages/overview.mdx
The leading text says:
```mdx
Example of [TextInput](/core/text-input) component selectors:
```
But the example shows button style prop api
```mdx
<SelectorsTable
data={TextInputStylesApi}
component="Button"
withTableBorder={false}
fixedLayout={false}
/>
```
This change the example to `TextInput`.
Result:
> [docs] fix style api overview example

- src/mantine-demos/src/demos/core/Pagination/Pagination.demo.icons.tsx
The docs still contain a reference to the `position` prop on the `Pagination` component (in the [`change-icons`](https://mantine.dev/core/pagination/#change-icons) example), but apparently it's been removed. I updated the text to match the actual code.
> Remove obsolete prop from example in Pagination.demo.icons.tsx

- src/mantine-core/src/components/Alert/Alert.module.css
This PR resolves #5305: The children of an `<Alert>` are offset from the alert's icon when the (optional) title is omitted. 
Fix: The `margin-top` on the `<Alert>` `.message` is replaced with a flex gap.
Before:
After:
> [@mantine/core] Alert: Fix padding without title

- packages/@mantine/core/src/components/Table/Table.module.css
**Description:**
Resolves an issue where the sticky header in the Table component was not behaving correctly due to missing z-index. The change ensures that the sticky header is displayed correctly on top of other elements.
**Issue Details:**
- fixes: #5384 
**Changes:**
- Added `z-index: 1;` to the `.thead` class in `mantine/packages/@mantine/core/src/components/Table/Table.module.css`.
**Checklist:**
**Screen-record:**
https://github.com/mantinedev/mantine/assets/134603758/918dbee4-749d-4dd4-852f-c26ce67aca94
> fix(@mantine/core): Add z-index to sticky header in Table component

- src/mantine-core/src/Popover/Popover.story.tsx
- src/mantine-core/src/Popover/Popover.types.ts
- src/mantine-core/src/Popover/use-popover.ts
Backports https://github.com/mantinedev/mantine/pull/5213
This PR backports the fix above to handle tall content in `Popover.Dropdown`. Reproduction https://codesandbox.io/s/amazing-nobel-s6zqy8
How to verify:
- `yarn storybook`
- Open http://localhost:7520/?path=/story/popover--size
- Click on the button and verify that it's possible to scroll the dropdown content properly
Issue (codesandbox):
Fix (storybook):
> Backport "Add size popover middleware to fix overflow issues in Popover.Dropdown" to v6

- packages/@mantine/core/src/components/Portal/Portal.test.tsx
- packages/@mantine/core/src/components/Portal/Portal.tsx
As discussed on Discord, filter out the tokens passed to `classList.add` in modal to avoid the following DOM exception:
```
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
```
I added two non-regression tests regarding this.
> [@mantine/core] add non-empty check for portal className

- docs/src/pages/form/schema-validation.mdx
[`mantine-form-valibot-resolver`](https://github.com/Songkeys/mantine-form-valibot-resolver) is published to bring [`valibot`](https://github.com/fabian-hiller/valibot) to `@mantine/form`.
related: #4688 #5088
> docs(form): add valibot example to schema-validation

- packages/@docs/demos/src/demos/core/Menu/Menu.demo.navigation.tsx
- packages/@mantine/core/src/components/Menu/Menu.context.ts
- packages/@mantine/core/src/components/Menu/Menu.test.tsx
- packages/@mantine/core/src/components/Menu/Menu.tsx
- packages/@mantine/core/src/components/Menu/MenuTarget/MenuTarget.tsx
This is a further change following on from https://github.com/mantinedev/mantine/pull/5335
A UX review of click-hover showed that if a menu has been clicked then this should override the hover until an item is clicked or a click-outside has happened.
I've also added unit tests to cover this functionality.
> Menu trigger=click-hover updates for UX and accessibility

- packages/@mantine/core/src/components/NumberInput/NumberInput.test.tsx
- packages/@mantine/core/src/components/NumberInput/NumberInput.tsx
I think we should use value instead of floatValue when floatValue is largerThan MAX_SAFE_INTEGER or else its just adding zeros to the end
[react-number-format example](https://codesandbox.io/p/sandbox/example-hyhxf3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqirothb00062v6avoelo7n6%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B …
> [@mantine/core] NumberInput: Fix (#5432)

- packages/@mantine/core/src/components/ScrollArea/ScrollArea.tsx
While using the `ScrollAreaAutosize` component I noticed that when used in conjunction with the `Table` component the data would overflow out of the viewport, particularly on smaller screen widths and mobile devices (screenshot 1 and 2).
**Screenshot 1 (Issue)**
**Screenshot 2 (Issue)**
I was able to fix this by adding `overflow: auto` to the `style` prop of the `ScrollAreaAutosize` component which renders it in the outermost parent `div` of the `ScrollArea` component (screenshot 3 and 4). I don't think this is an issue specific to my project so I'm making this update in hopes that it helps the library as a whole.
**Screenshot 3 (Fix)**
**Screenshot 4 (Fix)**
> [@mantine/core] ScrollAreaAutosize: fix overflow

- packages/@mantine/core/src/components/ColorPicker/AlphaSlider/AlphaSlider.tsx
Fixed because `background-position` calc was not work.
Fixes #5517
> [@mantine/core] AlphaSlider: Fix (#5517)

- packages/@mantine/core/src/components/Combobox/Combobox.tsx
> [@mantine/core] Combobox: Fix #5427

- src/mantine-core/src/Menu/Menu.story.tsx
- src/mantine-core/src/Menu/Menu.tsx
**Please note**, this is a backport of https://github.com/mantinedev/mantine/commit/b2c216fac8d90fb016b30ced553a4fad760d63c7 for `v6`.
This PR is fixing the `Menu`  focus problem described in https://github.com/mantinedev/mantine/issues/4502 for `v6`.
Since `@mantine/core` version 7 requires react 18+, it would be great to backport this fix. It will be helpful for all users who experience the focus problem, but can't upgrade to react 18 yet.
> [@mantine/core] Menu: Fix broken focus logic when `keepMounted` is set (`v6` backport)

- packages/@mantine/core/src/components/NumberInput/NumberInput.tsx
- packages/@mantine/core/src/core/MantineProvider/color-functions/to-rgba/to-rgba.test.ts
- packages/@mantine/core/src/core/MantineProvider/color-functions/to-rgba/to-rgba.ts
When calculating RGBA, errors occur in the following cases:
Success: rgb(255, 0, 255, 1)
Failure: rgb(255, 0, 255 / 1)
Upon executing 'rgb(255, 0, 255/ 1),' the expected result is {r: 255, g: 0, b: 255, a: 1}, but the actual result is {r: 255, g: 0, b: 2551, a: 1}.
commit :  https://github.com/mantinedev/mantine/pull/5544/commits/3caefc4768fb62924ac90d078333a9a7365502b1
Resolved the issue: https://github.com/mantinedev/mantine/issues/5540
commit : https://github.com/mantinedev/mantine/pull/5544/commits/b941c67c3c5f1cde17dd917a280841112d13e90c
> Fix: RGBA calculations && issue 5540

- packages/@docs/demos/src/demos/core/NavLink/NavLink.demo.active.tsx
With mantine version 7, [components that previously had an `icon` prop now use `leftSection` instead of `icon`](https://mantine.dev/changelog/7-0-0/#left-and-right-section).
This PR updates a demo example that still uses `icon`.
Thanks for all your work on Mantine!
> use `leftSection` in NavLink.demo.active.tsx

- docs/src/mdx/data/mdx-core-data.ts
**Description:**
fix: slider View source code link is broken 
**Issue Details:**
fix: slider View source code link is broken 
**Changes:**
- Updated Slider Source link
**Checklist:**
**Screen-record:**
https://github.com/mantinedev/mantine/assets/134603758/c9786d6a-4fdd-43c0-88b4-4abf71ba0e85
> fix: slider View source code link is broken 

- packages/@mantine/core/src/components/MultiSelect/MultiSelect.tsx
Description:
Makes it so that pills in the input field are not removable if its respective option is disabled.
Issues addressed:
#5621 
Video of implementation:
https://github.com/mantinedev/mantine/assets/39493240/295c6c73-e772-44cd-8df5-c1f88f9a4fee
> [@mantine/core] fix: multiselect disabled functionality for pills

- packages/@mantine/core/src/core/MantineProvider/use-mantine-color-scheme/use-computed-color-scheme.ts
If we have getInitialValueInEffect, we might as well be able to set defaultValue to undefined. Preferably I'd like to completely omit the parameter...
> Allow useComputedColorScheme defaultValue to be undefined

- .github/ISSUE_TEMPLATE/bug_report.yml
Fixed a minor grammar issue with the bug report issue template. I added a period instead of the comma to separate the two independent clauses.
> [Docs] Grammar fix in the bug report issue template

- packages/@mantine/core/src/components/InlineInput/InlineInput.tsx
Since https://github.com/mantinedev/mantine/commit/58d10fe87feaf836e3bfc1bf180aff3854f5ee68, the label positioning is broken.
This makes sure that the `mod` prop that `InlineInput` sets on the Box doesn't get overwritten by the `{...others}`.
Fixes: 
https://mantine.dev/core/switch/
https://mantine.dev/core/radio/
https://mantine.dev/core/checkbox/
> [@mantine/core] Spread mod attribute in InlineInput to fix label alignment

- packages/@mantine/form/src/tests/insertListItem.test.ts
- packages/@mantine/form/src/tests/removeListItem.test.ts
- packages/@mantine/form/src/tests/reorderListItem.test.ts
- packages/@mantine/form/src/tests/values.test.ts
- packages/@mantine/form/src/types.ts
- packages/@mantine/form/src/use-form.ts
Hi,
based on #5644, I tried to implement that. 
I think it is convenient to have the previous values in that callback function. You can then check which values changed and how.
> [@mantine/form] call onValuesChange with previous form values

- packages/@mantine/core/src/components/Combobox/Combobox.module.css
- packages/@mantine/core/src/components/Combobox/OptionsDropdown/OptionsDropdown.tsx
> [@mantine/core] OptionsDropdown: Remove redundant styles

- packages/@mantine/hooks/src/use-local-storage/create-storage.ts
Fixes https://github.com/mantinedev/mantine/issues/5230.
This PR resolves the defaultValue not being set on load in session storage.
> [@mantine/hooks] Resolved defaultValue not set in session storage

- packages/@mantine/hooks/src/use-debounced-state/use-debounced-state.test.ts
- packages/@mantine/hooks/src/use-debounced-state/use-debounced-state.ts
doesn't change current behavior - it enables the option to set the state via a SetStateAction that gives you access to its previous state value
> [@mantine/hooks] change useDebouncedState setter to accept set function

- packages/@mantine/core/src/components/Indicator/Indicator.module.css
As reported in isssue #5680, this PR changed the Indicator component's "processing" animation to be smoother on monitors with a 96dpi resolution.
This is done by removing the blurring of the shadow and expanding the radius of the shadow slightly. It looks a little different (larger) than before on high-res monitors (Macbooks etc) but now also works on older screens.
> fixed jittery animation on lower-res monitors

- scripts/build/rollup/create-package-config.ts
Something with regards to this changed in 7.3.0 release, and as a result
commonjs artifacts don't seem to use (or even have) `_interopDefaultLegacy`
when needed.
One way this manifests is that using `<Textarea autosize />` in node
environment (for instance a remix.run app) crashes with
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
This is due to [`react-textarea-autosize`](https://github.com/Andarist/react-textarea-autosize)
that `Textarea` uses under the hood always exports itself as
```
exports['default'] = index;
```
And current commonjs of Textarea looking like
```
'use client';
'use strict';
var React = require('react');
var TextareaAutosize = require('react-textarea-autosize');
.... …
```
> Set interop to 'auto' for cjs build

- packages/@mantine/core/src/core/factory/index.ts
Fixes #5722 by exporting these types so they can be referenced in emitted .d.ts files
> Fix for #5722 by exporting PolymorphicComponentProps, PolymorphicRef

- packages/@mantine/form/src/tests/setFieldValue.test.ts
- packages/@mantine/form/src/types.ts
- packages/@mantine/form/src/use-form.ts
Hey everyone! :wave: 
I would like to set the value of a field `foo` based on the value it currently has. This is currently possible by using 
```ts
form.setValues(prev => ({ foo: prev.foo + 1 }))
```
but (to the best of my knowledge) not by something like
```ts
form.setFieldValue("foo", prev => prev + 1)
```
I thought I'd give it a shot to make this a proper pull request, but I am facing type issues in the test I added:
> Parameter 'prev' implicitly has an 'any' type. ts(7006)
I would really appreciate if someone could take it from here. Thanks! :pray:
> `form.setFieldValue` based on previous value

- packages/@mantine/core/src/components/NumberInput/NumberInput.module.css
> [@mantine/core] NumberInput: Fix double border between controls

- docs/src/pages/changelog/7-5-0.mdx
Fixes 404 error while navigating from releases changelog in the docs.
> [docs] Fix: updated the proper link in changelog

- packages/@mantine/core/src/components/SegmentedControl/SegmentedControl.story.tsx
- packages/@mantine/core/src/components/SegmentedControl/SegmentedControl.tsx
Currently it's not possible to deselect/reset the value of the `SegmentedControl`. You can start out with an empty value, if you take for instance the empty string as value and make sure that in the `data` property it doesn't map to anything. If however you then select a value, and then change the value state back to the empty string, the `SegmentedControl` will still visually show your last selected value to be selected (however `data-selected=true` will no longer be present).
My PR here fixes this behavior and allows you, with a controlled value, to make the component unselected / without anything selected.
> [@mantine/core] Allow value reset in SegmentedControl

- packages/@mantine/core/src/components/Checkbox/Checkbox.module.css
Fixes #5805
Reproduction:
- Go to http://localhost:7545/core/checkbox/#usage
- Change variant from `filled` to `outline`
- Turn on `indeterminate`
- Turn on `disabled`
- **Note that checkbox style is now gray-ish**
Screenshots _(taken from localhost)_:
> [@mantine/core] Checkbox: Fix `indeterminate` styles when `disabled` for `outlined` variant

- scripts/utils/get-path.ts
When running `npm run setup` on windows (without WSL) it fails with the following message:
```
node:internal/validators:162
throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (node:internal/validators:162:11)
at Object.basename (node:path:756:5)
at transformFileName (scripts\build\generate-css.ts:13:15)
at generateCoreCSS (\scripts\build\generate-css.ts:57:56) {
code: 'ERR_INVALID_ARG_TYPE'
}
```
This is because of the glob path containing back slashes but `fast-glob` not supporting these:
https://www.npmjs.com/package/fast-glob#pattern-syntax
> Always use forward-slashes in glob expressions (patterns and [ignore](https://www.npmjs.com/package/fast-glob#ignore) option).
> [build] `npm run setup` didn't run on windows

- src/mantine-core/src/InlineInput/InlineInput.tsx
- src/mantine-core/src/Switch/Switch.test.tsx
- src/mantine-core/src/Switch/Switch.tsx
- src/mantine-core/src/Switch/SwitchGroup/SwitchGroup.test.tsx
- src/mantine-tests/src/index.ts
- src/mantine-tests/src/it-handles-switch-checkbox-state.tsx
Fixes https://github.com/mantinedev/mantine/issues/5699.
Backport of https://github.com/mantinedev/mantine/pull/5746
Things to note:
- Due to the implementation of role="switch", some tests needed to be adjusted.
- Screen readers no longer read out the onLabel and offLabel values, however I consider this to be appropriate as the label or aria-label should be used to provide enough context that these values are not needed.
- Screen reader testing was conducted across ChromeVox and Ubuntu Orca.
- Open to suggestions on types for bodyElement and labelElement.
> [@mantine/core] Switch: fix accessibility V6

- packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.story.tsx
- packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.tsx
- packages/@mantine/dates/src/components/TimeInput/TimeInput.story.tsx
- packages/@mantine/dates/src/components/TimeInput/TimeInput.tsx
> Add minTime and maxTime support to `TimeInput.tsx`

- packages/@mantine/core/src/components/Timeline/Timeline.tsx
> [@mantine/core] Timeline: Fix `autoContrast` being passed to the dom node as attribute (#5846)

- packages/@mantine/dropzone/src/Dropzone.tsx
This is in refernece to this [dicussion](https://github.com/orgs/mantinedev/discussions/5874).
tested the same by passing the inputProps via the storybook.
> [@mantine/dropzone] Fix: added inputProps for dropzone internal input component

- packages/@mantine/core/src/components/Transition/use-transition.ts
- packages/@mantine/modals/src/use-modals/use-modals.test.tsx
(Hopefully) fixes #3126 #5193 #5849.
As I found out [earlier](https://github.com/mantinedev/mantine/issues/3126#issuecomment-1426761731) it's probably related to the automatic batching in React. Therefore this fix uses `flushSync()` to enforce the state update at the right moment.
I hope that this will fix the issue.
> [@mantine/core] next try fixing transition issues

- packages/@mantine/dropzone/src/mime-types.ts
Fixes https://github.com/mantinedev/mantine/issues/5866.
HEIC is used by Apple devices after iOS 11. It can be very useful.
> [@mantine/dropzone] Add image HEIC to IMAGE_MIME_TYPE in @mantine/dropzone

- docs/src/components/CssVariablesList/CssVariableColorSwatch/CssVariableColorSwatch.tsx
- docs/src/components/CssVariablesList/CssVariablesList.tsx
I was going through the documentation to find some CSS variables to use for some default theme colors, and noticed that it was a bit difficult to figure out.
This PR adds a `ColorSwatch` column to the docs with the corresponding color if the CSS variable value matches a regex.
| Before | After |
| -------|------|
|![color-variables-1-before](https://github.com/mantinedev/mantine/assets/531798/701bdded-ecdd-4d40-8b5e-d186d77584c8)|![color-variables-1-after](https://github.com/mantinedev/mantine/assets/531798/028145d5-4b61-44bd-ad2a-b9a3fc847c8e)
|![color-variables-2-before](https://github.com/mantinedev/mantine/assets/531798/c05f8bdb-3ebe-40c7-8366-b0c2563cd2bb)|![color-variables-2-after](https://github.com/mantinedev/mantine/assets/531798/2eb5a13d-7a84-4b37-9fee-9666bf61a4e5)
> [docs] Add CssVariableColorSwatch column to CSS variables list

- packages/@mantine/hooks/src/use-headroom/use-headroom.ts
fixes #4563 
In order to fix the issue, I actually had to change the code logic for checking pin status. The `isPinned` function was previously used every time the `scrollPosition` returned by `useWindowScroll` changed. This is useless as causes the issue as when an address bar hides on scroll in mobile browser, a `resize` event is fired by the browser, but the `scrollPosition` hasn't actually changed.
```js
if (isPinned(scrollPosition, scrollRef.current)) {
return true;
}
```
In the above code, both `scrollRef.current` and `scrollPosition` hold the same value and don't offer a clear comparison.
This line of code is useless because the next condition call after it which calls `isFixed` with `scrollPosition` and the `fixedAt` value is the only true logic for this hook's implementation. …
> [@mantine/hooks]: fix unstable pinning of item by `useHeadroom` on mobile devices

- packages/@mantine/core/src/components/Indicator/Indicator.module.css
Fixes: https://github.com/mantinedev/mantine/issues/5887
The CSS animation with `border-shadow` may not look good on some browsers, so I used `transform` to fix it.
I have tried to make it look almost the same, but not exactly the same, so I would appreciate it if you could compare the following video to see if there are any problems!
[Screencast from 2024年03月12日 21時52分18秒.webm](https://github.com/mantinedev/mantine/assets/79452224/b63ec2b9-da8d-4d34-890e-2fff6cd30b5f)
[Screencast from 2024年03月12日 22時06分16秒.webm](https://github.com/mantinedev/mantine/assets/79452224/f8e52da9-1334-4b54-83b1-faa73f5da67d)
> [@mantine/core] packages: fix animation of indicator

- packages/@mantine/core/src/components/Combobox/OptionsDropdown/OptionsDropdown.tsx
one line change to pass renderOption to the child Options when the data source is grouped.
Fixes #5966
> pass renderOption to grouped Options

- packages/@mantine/core/src/components/Combobox/use-combobox-target-props/use-combobox-target-props.ts
Fixes #5934.
Fixes an issue in the Combobox where confirming an IME conversion incorrectly submits the focused option.
I confirmed to work as expected in Safari.
> [@mantine/core] Fix conbobox keyDown handling during IME input conversion

- packages/@mantine/core/src/components/NumberInput/NumberInput.tsx
Fixes: https://github.com/mantinedev/mantine/issues/5918
[Screencast from 2024年03月14日 23時49分54秒.webm](https://github.com/mantinedev/mantine/assets/79452224/6e7b513a-98f8-4fa7-953e-6a46f4d460ba)
> [@mantine/core] fix NumberInput increment bug

- packages/@mantine/hooks/src/use-local-storage/create-storage.ts
> useLocalStorage and useSessionStorage missing dependencies

- packages/@mantine/dates/src/components/Month/Month.tsx
- packages/@mantine/dates/src/components/Month/get-date-in-tab-order/get-date-in-tab-order.test.ts
- packages/@mantine/dates/src/components/Month/get-month-days/get-month-days.test.ts
- packages/@mantine/dates/src/components/Month/get-month-days/get-month-days.ts
Fixes #5840 
The problem was that variables startOfMonth and endOfMonth shifted by timezone once and then shifted again during clicks.
At version 7.4.2 which works ok, timezone at getMonthDays was always "undefined" there for it worked good as mentioned in the Issue. With new version of Month.tsx in 7.5.0 timezone is not undefined and so there is a double shift of date.
Is this a rigth direction to solve it?
> [@mantine/dates] Fix error with timezones in Month

- packages/@mantine/core/src/components/PinInput/PinInput.story.tsx
- packages/@mantine/core/src/components/PinInput/PinInput.tsx
This PR fixes two issues with the PinInput component I noticed.
1. Pasting on MacOS was not working, as the default paste shortcut is `Command + V` instead of `Ctrl + V`.
2. Default browser tab navigation was prevented, which caused problems when a PinInput component appeared in the middle of a form. Now, if you press `tab` while in the last input segment, focus will move to the next focusable element. If you press `shift + tab` on the first input segment, focus will move to the previous focusable element.
> [@mantine/core] PinInput: Fix paste on Mac, Tab behavior

- apps/mantine.dev/src/components/CssVariablesList/CssVariableColorSwatch/CssVariableColorSwatch.tsx
I noticed the table did not show a color swatch for the `rgba` values.
This PR adjusts the regex so the `rgba` variables are matched.
> [docs] Update CssVariableColorSwatch table regex to match `rgba` variables

- packages/@mantine/core/src/components/Image/Image.tsx
The ref is not set on the Image when there is an error or no src
this PR fixes that issue
> Ensure fallback image has ref

- packages/@mantine/spotlight/src/spotlight.store.ts
Fixes: https://github.com/mantinedev/mantine/issues/5992
before
[https://github.com/mantinedev/mantine/assets/79452224/a28a2920-eee8-45cc-84ea-979e8f0b6ba8](https://github.com/mantinedev/mantine/assets/79452224/a28a2920-eee8-45cc-84ea-979e8f0b6ba8)
after
[https://github.com/mantinedev/mantine/assets/79452224/a28a2920-eee8-45cc-84ea-979e8f0b6ba8](https://github.com/mantinedev/mantine/assets/79452224/74355a87-c5d5-4977-a31f-0dfc4aa6b4b7)
> [@mantine/core] fix: actions store of `Spotlight`

- packages/@mantine/tiptap/src/RichTextEditor.module.css
In mantine v6, by default Toolbar will render into a `<Group>` component and the `align-items` value is `center` by default. V7 breaks this behavior.
> [mantine/tiptap] set align-items to center for toolbar

- packages/@mantine/core/src/components/ScrollArea/ScrollArea.module.css
Fix incorrect inset position of the horizontal scrollbar in the `ScrollArea` component ([Discord discussion](https://discord.com/channels/854810300876062770/1227466423048081438)).
> [@mantine/core] ScrollArea: Fix incorrect inset of the horizontal scrollbar

- packages/@mantine/core/src/components/ScrollArea/ScrollArea.tsx
ScrollArea `viewportProps.onScroll` prop not working
> [@mantine/core] ScrollArea: Fix viewport `onScroll` prop not working

- packages/@mantine/core/src/components/PinInput/PinInput.tsx
addresses #6031
not currently possible to access the ref of the pin input container
> Pin Input: add rootRef prop

- packages/@mantine/core/src/components/TagsInput/TagsInput.tsx
When people use IME to type in CJK words, a `Backspace` key would delete both a char in the CJK words and the previous tag before this fix.
Ref PR: https://github.com/mantinedev/mantine/pull/4947
> [@mantine/core] TagsInput: Fix incorrect IME keyboard input handling for `Backspace` (#6010)

- packages/@mantine/core/src/components/NumberInput/NumberInput.tsx
Fixes: https://github.com/mantinedev/mantine/issues/6003
after
[Screencast](https://github.com/mantinedev/mantine/assets/79452224/202647b8-e51e-428a-a995-0c75f0b994f7)
> [@mantine/core] fix: NumberInput cursor position

- packages/@mantine/core/src/components/TagsInput/TagsInput.tsx
Simple correction to a couple of typos I noticed while in the Mantine documentation for the `TagsInput` component.
> [@mantine/core] fix: corrected typos in TagsInput documentation

- packages/@mantine/core/src/core/Box/style-props/resolvers/spacing-resolver/spacing-resolver.test.ts
- packages/@mantine/core/src/core/utils/units-converters/rem.test.ts
- packages/@mantine/core/src/core/utils/units-converters/rem.ts
closes #6077 
(test that failed in the first commit was always broken)
> Spacing: fix resolver for empty strings, and strings with spaces

- packages/@mantine/core/src/components/NumberInput/NumberInput.tsx
fixes #6056 
See this more or less as a draft.
The solution is a bit ... and I don't really know why the accessibility tests don't accept type="number" :(
Maybe it would be a better issue to solve for react or the browsers.
> [@mantine/core] fix: NumberInput cursor no jump to end when pressing backspace on pos 0

- packages/@mantine/core/src/components/Slider/Slider/Slider.test.tsx
- packages/@mantine/core/src/components/Slider/Slider/Slider.tsx
Resolves #6063 by changing the function call order, and adds a test to verify the timing.
It's unclear to me why `onChangeEnd` is called twice (this behavior was there previously), but importantly the second `onChangeEnd` happens *after* `onChange`.
> [bugfix]: reorder onChange and onChangeEnd events for Slider arrow keys

- packages/@mantine/hooks/src/use-hash/use-hash.ts
`setHashValue` used wrong value and was not updating beyond refresh.
This was actually fixed in #3773, but maybe a bad rebase or something re-introduced this for v7 in https://github.com/mantinedev/mantine/commit/588383b1dfae7a7f4fc3b664837dc5cab12b6ec1.
Please let me know if you'd like me to write some tests for this, any help with that would be appreciated.
> Fix useHash not updating

- packages/@mantine/core/src/components/PasswordInput/PasswordInput.module.css
Fixes mantinedev/mantine#6100
As noted [here](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#visibility-of-the-control), the icon only shows up when you start typing.
> Hide MS Edge visibility icon

- packages/@mantine/core/src/components/ModalBase/use-modal.ts
Fix: Ensure onClose is not triggered by escape key when Modal is not open
---
This PR addresses a specific issue where the `onClose` function of the Modal component was incorrectly triggered by pressing the Escape key, even when the Modal was not actively open.
**Problem:**
When the Escape key was pressed, the `onClose` handler was executed regardless of the Modal's open state. This could unintentionally disrupt the user experience and application state if the `onClose` logic was not meant to be executed at that time.
**Solution:**
The fix involves a simple, yet effective modification in the `useModal` hook. By adding a conditional check that ensures the Modal is open (`opened` state is `true`) before invoking the `onClose` function, we prevent unwanted side effects
fixes #6148 
commit: …
> [@mantine/core] fix: prevent onClose trigger on escape when modal is not open

- packages/@docs/demos/src/demos/code-highlight/CodeHighlight.demo.inline.tsx
- packages/@mantine/code-highlight/src/CodeHighlight.story.tsx
Just fixing something I noticed when viewing the docs on inline code highlighting.
Before:
After:
> Fix inline code highlight examples

- packages/@mantine/core/src/components/NumberInput/NumberInput.test.tsx
- packages/@mantine/core/src/components/NumberInput/NumberInput.tsx
After looking into #6162, I found that commit 081a47a removed the `allowNegative` prop. This PR brings back support for it and fixes the bug where the `NumberInput` could go negative.
> [@mantine/core] NumberInput: Fix ignored allowNegative prop (#6162)

- packages/@docs/demos/src/demos/core/ColorInput/ColorInput.demo.fixOnBlur.tsx
The demo code for the `ColorInput` `fixOnBlur` example currently shows the code for the no eyedropper example, so small fix :)
> [docs] fix ColorInput fixOnBlur demo code

- apps/mantine.dev/src/pages/core/nav-link.mdx
- packages/@mantine/core/src/components/NavLink/NavLink.module.css
Based on the discussion in #5788.
> [@mantine/core] NavLink: Use active styles when aria-current is present

- packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.tsx
After [this](https://github.com/mantinedev/mantine/issues/4596) issue, [this](https://github.com/mantinedev/mantine/pull/5819/files#diff-b9a3ca038d146815161e22ea83320e438f51ac7cb489978a20cd583f2b3b0d6cR258-R271) code was merged which replaces the passed in `minTime` and `maxTime` prop in `timeInputProps` within the `DateTimePicker` component.
This PR alters the prop order such that a consumer can override `minTime` and `maxTime` if they desire.
This could help with certain functionality where a caller wants to prevent any time before e.g. 9AM on any day to be selected.
> [@mantine/dates] Altering prop order of `DateTimePicker`'s `TimeInput`

- packages/@docs/styles-api/src/data/Title.styles-api.ts
Simple fix to formatting typo I noticed while in the Mantine documentation for the `Title` component.
> [mantine.dev] fix formatting typo on title styles api page

- packages/@mantine/hooks/src/use-throttled-callback/use-throttled-callback.test.ts
- packages/@mantine/hooks/src/use-throttled-callback/use-throttled-callback.ts
- packages/@mantine/hooks/src/use-throttled-state/use-throttled-state.test.ts
- packages/@mantine/hooks/src/use-throttled-state/use-throttled-state.ts
- packages/@mantine/hooks/src/use-throttled-value/use-throttled-value.test.ts
- packages/@mantine/hooks/src/use-throttled-value/use-throttled-value.ts
Make sure the throttled value/state/callback always has the last value it was called with after the timeout has expired.
- I refactored the hooks to all depend on a single hook (`useThrottledCallbackWithClearTimeout`) that contains the throttling logic. This hook is not exported.
- Mantine doesn't use the `react-hooks/exhaustive-deps` lint. So there is no warning for the missing `wait` in the old use-throttled-value implementation. This is why I introduced the `waitRef`. I later saw that use-throttled-state and use-throttled-callback did include the `wait` dependency. So maybe it was just a mistake. But anyway I kept the `waitRef` for now.
- I also adjusted the tests to reflect the new behavior and unified the "should clear timeout on unmount" tests.
Fixes: #6220
> [@mantine/hooks] use-throttled-*: Emit updates on trailing edges

- packages/@mantine/hooks/src/use-fetch/use-fetch.ts
Based on the https://github.com/mantinedev/mantine/issues/6215, that use-fetch hook throws error and crash whole application. Proposal is just not re-throwing again the error to component level, since in React catching an error of a hook is not that easy as doing a try-catch.
> fix: avoid re throwing use-fetch error

- apps/mantine.dev/src/pages/charts/bar-chart.mdx
- packages/@docs/demos/src/demos/charts/BarChart/BarChart.demo.waterfall.tsx
- packages/@docs/demos/src/demos/charts/BarChart/BarChart.demos.story.tsx
- packages/@docs/demos/src/demos/charts/BarChart/_data.ts
- packages/@docs/demos/src/demos/charts/BarChart/index.ts
- packages/@mantine/charts/src/AreaChart/AreaChart.tsx
- packages/@mantine/charts/src/BarChart/BarChart.story.tsx
- packages/@mantine/charts/src/BarChart/BarChart.tsx
- packages/@mantine/charts/src/ChartLegend/ChartLegend.module.css
- packages/@mantine/charts/src/ChartLegend/ChartLegend.tsx
- packages/@mantine/charts/src/ChartTooltip/ChartTooltip.tsx
- packages/@mantine/charts/src/types.ts
This is related to #6224 
**Enhancement to ChartTooltip.tsx: Support for number[] in valueFormatter**
This pull request introduces support for an array of numbers (number[]) as input to the valueFormatter property in ChartTooltip.tsx. Previously, valueFormatter was strictly typed as (value: number) => string. However, the Recharts documentation indicates that both bar and area charts may utilize an array of numbers as input (see: [AreaChart API](https://recharts.org/en-US/api/AreaChart#data) and [BarChart API](https://recharts.org/en-US/api/BarChart#data)).
Modifying the valueFormatter type globally would impact other charts adversely. Therefore, I have refrained from altering the type but have extended the functionality in ChartTooltip.tsx to accommodate a tuple of two numbers, which is …
> [@mantine/charts] BarChart: added waterfall type

- packages/@mantine/modals/src/ConfirmModal.tsx
Fixes #6324
Implement a condition within the **Group** inside **ConfirmModal.tsx** that dynamically sets the marginTop style property to 'md' if the component contains children, otherwise set it to '0'.
Before: 
After
> FIX - Small glitch when using a confirm modal without children #6324

- packages/@mantine/hooks/src/use-focus-trap/use-focus-trap.test.tsx
closed #6331
I thought that `fireEvent` in the `use-focus-trap` test should be rewritten to `userEvent`.
> fix: change `fireEvent` to `userEvent` in `use-focus-trap.test.tsx`

- packages/@mantine/core/src/core/Box/style-props/resolvers/border-resolver/border-resolver.ts
This is not a reported issue, I just found what I believe to be a small typo when reading through the code base.
It seems this may have been an auto-complete mistake that also automatically imported the colorsTuple function from MantineProvider. Calling `length` on a function returns the number of arguments in the function definition, in this case colorsTuple takes a parameter, so its length is `> 0`.
It just so happens there's no bug or failing test case, as colorResolver will ultimately return an empty string for an empty string input, so this typo doesn't appear to really matter.
> [@mantine/core] Fix: correct a small typo referencing colorsTuple in border-resolver

- packages/@mantine/charts/src/PieChart/PieChart.tsx
Fixes PieChart using the valueFormatter for the tooltip but not for the label
> [@mantine/charts] fix: PieChart inner label not using valueFormatter 

- packages/@mantine/core/src/components/Tree/Tree.tsx
React 19 RC complains: 
> React does not recognize the `levelOffset` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `leveloffset` instead. If you accidentally passed it from a parent component, remove it from the DOM element.  
`ul`
`_Box<@http://localhost:5173/node_modules/.vite/deps/chunk-MRL2GTIY.js?v=2e806eeb:3767:3`
`Tree<@http://localhost:5173/node_modules/.vite/deps/chunk-MRL2GTIY.js?v=2e806eeb:27494:25`
...
> [@mantine/core] Tree: fix react warning about levelOffset

- src/mantine-modals/src/context.ts
- src/mantine-styles/src/theme/types/MantineColor.ts
TypeScript type augmentation does work with TypeScript 5.5
Fixes https://github.com/mantinedev/mantine/issues/6438 for Mantine v6
Same as https://github.com/mantinedev/mantine/pull/6443 for Mantine v7
> fix: Typescript 5.5 compatibility for Mantine v6

- packages/@mantine/core/src/core/Box/style-props/style-props.types.ts
In re: Discussion #6423 
Adds docs comments for StyleProps for developer convenience.
Before:
After:
> Styleprops docs discussion #6423

- apps/mantine.dev/src/pages/hooks/use-local-storage.mdx
- packages/@mantine/hooks/src/use-local-storage/create-storage.ts
The code is specifying this property as optional.
https://github.com/mantinedev/mantine/blob/29f24e31d9c33316395b317cd152648d55c65ef9/packages/%40mantine/hooks/src/use-local-storage/create-storage.ts#L15C3-L15C37
The document didn't specify it as optional:
https://github.com/mantinedev/mantine/blob/master/apps/mantine.dev/src/pages/hooks/use-local-storage.mdx#definition
The code also assign default value as "true" when not specified.
https://github.com/mantinedev/mantine/blob/29f24e31d9c33316395b317cd152648d55c65ef9/packages/%40mantine/hooks/src/use-local-storage/create-storage.ts#L78
It created a confusing when I was working with this hook at the 1st time and caused unexpected behavior.
> [@mantine/hooks] use-local-storage Update document to specify the getInitialValueInEffect default value

- packages/@mantine/hooks/src/use-eye-dropper/use-eye-dropper.ts
Added additional check for Opera browser, if it is Opera browser then do not show EyeDropper.
Fixes #6306
> [@mantine/hooks] use-eye-dropper.ts Fix: #6306

- packages/@mantine/core/src/components/ModalBase/ModalBase.tsx
When trying to pass a `key` to the `removeScrollProps` on a modal, react logs an error in the console.  
This PR is to resolve that error.
Error Message in console:
```console
app-index.tsx:25 Warning: A props object containing a "key" prop is being spread into JSX:
let props = {key: someKey, enabled: ..., forwardProps: ..., children: ...};
<ForwardRef {...props} />
React keys must be passed directly to JSX without using spread:
let props = {enabled: ..., forwardProps: ..., children: ...};
<ForwardRef key={someKey} {...props} />
at http://localhost:3000/_next/static/chunks/node_modules_%40mantine_core_esm_components_e3257d._.js:491:199
at Provider (http://localhost:3000/_next/static/chunks/node_modules_%40mantine_core_esm_core_831b37._.js:3121:25)
at …
```
> Extract "key" from removeScrollProps

- packages/@mantine/spotlight/src/spotlight.store.ts
Following up on [my proposed fix on Discord](https://discord.com/channels/854810300876062770/1198385031287156826/1207000915345809498), here's finally the PR.
The added method tries to find the Spotlight's action element in the document and in any potential ShadowDOM.
> [@mantine/spotlight] Search for the action item in the document or in ShadowDOMs

- packages/@mantine/core/src/components/Tooltip/Tooltip.story.tsx
- packages/@mantine/core/src/components/Tooltip/Tooltip.test.tsx
- packages/@mantine/core/src/components/Tooltip/Tooltip.tsx
- packages/@mantine/core/src/components/Tooltip/TooltipFloating/TooltipFloating.tsx
- packages/@mantine/core/src/components/Tooltip/TooltipFloating/use-floating-tooltip.ts
- packages/@mantine/core/src/components/Tooltip/use-tooltip.ts
A defaultOpened (false by default ) prop for tooltip component, which will show tooltip by default.
Added story and test for it.
> Added defaultOpened prop on tooltip

- apps/mantine.dev/src/pages/core/multi-select.mdx
- apps/mantine.dev/src/pages/core/select.mdx
- packages/@mantine/core/src/components/MultiSelect/MultiSelect.test.tsx
- packages/@mantine/core/src/components/MultiSelect/MultiSelect.tsx
- packages/@mantine/core/src/components/MultiSelect/MutliSelect.story.tsx
- packages/@mantine/core/src/components/Select/Select.story.tsx
- packages/@mantine/core/src/components/Select/Select.test.tsx
- packages/@mantine/core/src/components/Select/Select.tsx
This PR ensures the `notFoundMessage` shows up even when no data is available. It can be confusing for users to click on the select and see nothing happen. The search functionality for both select and multi-select remains unchanged. The docs have also been updated to reflect this change.
References: #6474
> [@mantine/core] Select & MultiSelect: Show not found message even when not searchable

- packages/@mantine/core/src/components/Tooltip/Tooltip.module.css
- packages/@mantine/core/src/components/Tooltip/Tooltip.story.tsx
- packages/@mantine/core/src/components/Tooltip/Tooltip.tsx
Fixes issue raised here: https://github.com/mantinedev/mantine/issues/6497 
I followed what was done in https://github.com/mantinedev/mantine/issues/6419, which fixes the same issue for the Popover component.
> [@mantine/core] Tooltip floatingStrategy=fixed updates position to fixed

- packages/@mantine/dates/src/components/DateInput/DateInput.tsx
Fixes #6336 
Reviewed code and discovered that the useDidUpdate hook was not setting the state value with timezone when applicable. 
Before: It was running and setting the inputValue to the initial onChange Value without applying the updates from the useUncontrolledDates Hook. 
After: _value is the source of truth to display in input and will display with updates applied by useUncontrolledDates Hook.
> MANTINE-6336: Fix DateInput to setInputValue to _value which has time zone applied

- packages/@mantine/core/src/components/Menu/MenuDropdown/MenuDropdown.tsx
- packages/@mantine/core/src/components/Menu/MenuItem/MenuItem.tsx
- packages/@mantine/core/src/components/Modal/Modal.story.tsx
Fixes https://github.com/mantinedev/mantine/issues/6528
Things to note:
- Added storybook page with Menu in Modal
- Adds data-mantine-stop-propagation to interactive menu items to stop keyboard events from bubbling up
- Code Formatting changes provided by prettier
> [@mantine/core] Menu: fix keboard Esc from closing menu and modal when in a modal

- packages/@mantine/dates/src/components/PickerInputBase/PickerInputBase.tsx
according to [accessibility part](https://mantine.dev/dates/date-picker-input/#accessibility) of `DatePickerInput` docs it is said that if `label` prop is set, input will be accessible it is not required to set `aria-label`.
But since there was assignment of `aria-label` inside `PickerInputBase` on `Input` it essentially overrode the label from `InputWrapper` connected with `htmlFor` attribute.
It made component harder to use inside e2e tests that rely on labels for element locators, since component locator should be dynamic or `aria-label` attribute must be set alongside with `label` attribute
if this behavior of dynamically changing label based on value or placeholder is intended I'll be glad to adjust `DatePickerInput` docs instead of code change
> [@mantine/dates] fix proper label assignment on DatePickerInput

- packages/@mantine/hooks/src/use-os/use-os.ts
fixes: https://github.com/mantinedev/mantine/issues/6508
added `ontouchend` to determine ipad air and pro.
> [@mantine/hook]: fix use-os returns `macos` when ipad

- apps/mantine.dev/src/pages/styles/vanilla-extract.mdx
Mantine `theme` and Vanilla extract `themeToVars` should be in separate files to avoid vite build errors.
See: https://github.com/mantinedev/mantine/issues/5219
> Docs: fix Vanilla extract theming example

- src/mantine-styles/src/theme/types/MantineTheme.ts
Mantine 6.0.22 introduced some fixes to support module augmentation. This is documented on the [Mantine.dev](https://v6.mantine.dev/theming/theme-object/#other) website as a way to support typing the `MantineThemeOther` object. This PR specifically address `MantineThemeOther`, which was missed.
The issue was a result of Typescript fixing a bug, see https://github.com/microsoft/TypeScript/issues/58961
See https://github.com/mantinedev/mantine/pull/6445 for previous fixes.
> fix: Mantine 6.x MantineThemeOther support for module augmentation for TypeScript 5.5

- packages/@mantine/core/src/components/Chip/Chip.module.css
Fixes the incorrect padding for checked Chip at XL size.
Formula: 32-(18+(22/1.5))/2
> Fix checked chip padding at XL size

- apps/help.mantine.dev/src/pages/q/data-grid-i-need.mdx
I think there is typo, maybe you meant `near` not `nearest`
> chore: fix a typo

- packages/@mantine/core/src/components/Slider/Slider.module.css
This PR removes unnecessary parentheses in the `Slider.module.css` that can lead to an error when imported.
> [@mantine/core]: Remove invalid and redundant parentheses in Slider

- packages/@mantine/charts/src/PieChart/PieChart.story.tsx
- packages/@mantine/charts/src/PieChart/PieChart.tsx
> [@mantine/charts] Add valueFormatter support on outside labels

- packages/@mantine/core/src/components/TagsInput/TagsInput.tsx
Fixes #6568
Allow disabling of default key down behaviour by stopping the event propagation.
> Allow overwrite of default onKeyDown behaviour of the TagsInput component

- packages/@mantine/core/src/components/FloatingIndicator/use-floating-indicator.ts
Fixes #6527 
The problem was that the transitionend event listener was added to the entire document, so it was picking up transitions from any element. 
When the user clicked the burger, it opened the Navbar which changed the offsetLeft of the FloatingIndicator parent. This triggered the useEffect and called isParent with the transition event from the Navbar burger. This made isParent return true and then call updatePositionWithoutAnimation() which caused the bug.
By attaching the event listener directly to the parent element, the handler only responds to transitions within the parent and its children, resulting in correct behavior.
Please let me know if this good. Happy to revise based on your feedback.
Thanks,
Michael
> Fix SegmentedControl FloatingIndicator Bug

- packages/@docs/styles-api/src/data/SegmentedControl.styles-api.ts
- packages/@mantine/core/src/components/SegmentedControl/SegmentedControl.tsx
Hello. I want to customize the `root` styles of segmented control in `disabled` state, but it's not possible without `data-disabled` attribute on `root`, because the only thing you can use in CSS in that case is `:disabled` pseudo-class on nested inputs, but there are no parent selectors implemented in CSS right now, so basically it's just not possible to change `root` styles without JS when it's child inputs are disabled. But JS logic doesn't allow to customize this behavior once and for all (I mean in theme), and I have to create my own wrapper-component.
I suggest adding this attribute to make customization easier
> [@mantine/core] SegmentedControl: Add missing disabled data-attribute

- packages/@mantine/core/src/components/Badge/Badge.module.css
I encountered an issue with text overflow in badges inside tables at my company. The dot variant was particularly problematic, with the dot's width shrinking when the overflow was too extensive. I have fixed this issue and will post before and after images to illustrate the changes.
Note: The new styles added to the badge root caused a problem with rounded badges. I also addressed this issue and ensured all tests passed. I checked all badge formats, and everything is now working correctly.
> FIX: badge dot width fix without breaking rounded badge styles

- packages/@mantine/charts/src/ChartTooltip/ChartTooltip.test.tsx
- packages/@mantine/charts/src/ChartTooltip/ChartTooltip.tsx
- packages/@mantine/charts/src/LineChart/LineChart.test.tsx
- packages/@mantine/charts/src/utils/get-series-labels/get-series-labels.ts
Fixes #6529 
Relates to #5886 
Update tooltip payload by unpacking item's not related to the nested name. Then unpack nested details into same object. 
Updates getSeriesLabels to account for nested name. 
Adds Unit Tests for displaying legend and tooltip label and data.
> [@mantine/charts]: Fix LineChart Legend and Tooltip to support nested names

- packages/@mantine/form/src/tests/use-form/watch.test.tsx
- packages/@mantine/form/src/use-form.ts
Fixes #6638
This PR adds tests covering the problem of `form.watch` subscribers not being called when the value changes because of `form.initialize()` as described in #6638 and fixes it.
The way it fixes it is by notifying the subscribers the same way `setValues` does it.
Let me know if this is not the right way to fix this.
> [@mantine/form] Call `form.watch` subscribers on `form.initialize`

- packages/@mantine/dates/src/components/Calendar/Calendar.tsx
Fixes #5695 
If you need any adjustments, please let me know. Happy to revise based on your feedback.
Thanks
> Fix: DateInput does not default to minDate month

- packages/@mantine/dates/src/hooks/use-dates-state/use-dates-state.ts
Fixes https://github.com/mantinedev/mantine/issues/6692 
**Notes:**
- Added `setHoveredDate` to fix the direction of the selected `Day` box when updating
- Updated the `UseEffect` dependencies to use the uncontrolled/controlled `_value` to better match the effect
> [@mantine/dates] Fix: unselect date-range hover when value is changed

- packages/@mantine/dropzone/src/mime-types.ts
Added 7z & rar mime types for simpler usage in Dropzone and more aesthetically pleasing usage.
Note: rar can supposedly also be represented as [application/vnd.rar](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), [application/x-rar-compressed](https://en.wikipedia.org/wiki/RAR_(file_format)) and [application/octet-stream](https://simple.wikipedia.org/wiki/RAR_(file_format))
*Source: Mozilla & Wikipedia
> [@mantine/dropzone] Added 7z & rar mime types

- apps/mantine.dev/src/pages/core/tree.mdx
- packages/@mantine/core/src/components/Tree/use-tree.ts
Motivation: This PR aims to add an optional `initialCheckedState` prop to `useTree,` akin to `initialExpandedState` and `initialSelectedState`, which addresses #6641.
- Adds `initialCheckedState` property to `useTree` hook;
- Adds default property to `checkedState` hook;
- Renames internal `getInitialState` function to `getInitialExpandedState`;
- Adds internal `getInitialCheckedState` function: This takes the current tree checkedState and ensures only leaf nodes are present, which allows users to input parent nodes in the `initialCheckedState` property as it outputs their leaf nodes;
- Adds `setCheckedState` instruction and dependency to `initialize` callback to update `checkedState` with behaviour indicated in previous point.
> [@mantine/core] Tree: Add optional initialCheckedState property

- packages/@mantine/core/src/components/Tabs/TabsPanel/TabsPanel.tsx
fixes: https://github.com/mantinedev/mantine/issues/6695
removed waring by not passing `keepMounted` to Box component:)
> [@mantine/core] fix: remove keepMounted warnings

- packages/@mantine/hooks/src/use-idle/use-idle.test.tsx
- packages/@mantine/hooks/src/use-idle/use-idle.ts
This came up when I was implementing automatic logout in our application. If a given event _never_ fires, the current implementation of `useIdle` will never return `true`.
This PR starts the timer immediately after setting up the event listeners.
Fixes #6682
> [@mantine/hooks] use-idle: Start timer immediately instead of waiting for an event (#6682)

- apps/mantine.dev/src/pages/form/actions.mdx
Add missing comma in code example.
> [@mantine/form]: fix a typo

- packages/@mantine/core/src/components/Breadcrumbs/Breadcrumbs.module.css
Fixes #6862 
This fix addresses the issue of the Breadcrumbs component breaking on mobile and similar devices. By adding `flex-wrap: wrap;` to the **root** style, the layout will now adjust correctly on smaller screens, preventing UI breakage.
Before: 
After:
> [@mantine/core] fix: apply flex-wrap in breadcrumbs

- packages/@mantine/core/src/core/utils/is-number-like/is-number-like.test.ts
- packages/@mantine/core/src/core/utils/is-number-like/is-number-like.ts
fixes: https://github.com/mantinedev/mantine/issues/6853
updated `isNumberLike` func so that it'll return true when it's valid css props. otherwise false. 
eg) 2xl
I've checked all test passes, and added test for custom sizes
> [@mantine/core] fix: `isNumberLike` should only check for valid css

- apps/mantine.dev/src/components/MdxProvider/MdxPackagesInstallation/data.ts
modified to specify v7 since the latest version of embla-carousel-react is now v8
> [mantine.dev] make sure to install embla-carousel@7

- packages/@mantine/dates/src/components/Calendar/Calendar.tsx
fixes: https://github.com/mantinedev/mantine/issues/6835
Added `nextLabel` and `previousLabel` which was written on docs
> [@mantine/date] fix: add missing aria-label props to `Calender`

- packages/@docs/demos/src/demos/core/Title/Title.demo.size.tsx
- packages/@mantine/core/src/components/Title/Title.tsx
- packages/@mantine/core/src/components/Title/get-title-size.ts
Fixes https://github.com/mantinedev/mantine/issues/6827
when MantineSize is used for `size` Props, --tile-fz will be like `xl` which is invalid. this PR will fix it.
> [@mantine/core] chore: add sizes to `Title`

- apps/mantine.dev/src/components/MdxProvider/MdxPackagesInstallation/data.ts
SEE: https://mantine.dev/getting-started/#get-started-without-framework
when you check `@mantine/tiptap` , tabler-icons will be imported instead of `@tiptap/pm`
> [mantine.dev] fix: dependency of `@mantine/tiptap` was wrong

- packages/@docs/demos/src/demos/dates/TimeInput/TimeInput.demo.configurator.tsx
- packages/@mantine/dates/src/components/TimeInput/TimeInput.tsx
fixes: https://github.com/mantinedev/mantine/issues/6758
> [@mantine/date] remove placeholder from TimeInput props

- packages/@mantine/core/src/components/ScrollArea/ScrollArea.tsx
`onBottomReached` has been fixed in 7.12.2, but `onTopReached` has not been fixed until now.
> fix: Unknown event handler property `onTopReached`. It will be ignored.

- apps/mantine.dev/package.json
- package.json
- packages/@mantine/colors-generator/package.json
- packages/@mantine/colors-generator/tsconfig.json
- yarn.lock
Upgrade `chroma-js` to a newer version, related functions are tested and work fine.
Tip: There seem to be some issues with v2.6.0 that are not working as expected.
> [@mantine/colors-generator] Dependency: upgrade `chroma-js`

- packages/@mantine/core/src/components/TagsInput/TagsInput.tsx
fixes https://github.com/mantinedev/mantine/issues/6873
> Fix TagsInput duplicate deletion behavior

- packages/@mantine/core/src/components/Menu/MenuItem/MenuItem.tsx
Noticed that typo when I wanted to create an advanced interaction.
> fix: typo for onKeyDown method in MenuItem

- apps/mantine.dev/src/pages/contribute.mdx
fixes: https://discord.com/channels/854810300876062770/861521000985264138/1289156043066310757
> [mantine.dev] fix wrong wording at contributing.mdx

- packages/@mantine/charts/src/PieChart/PieChart.module.css
Removed unused css from PieChart. Probably copied and pasted from DonutChart was left in place.
> [@mantine/chart] remove unused css from `PieChart`

- packages/@mantine/core/src/components/AppShell/use-resizing/use-resizing.tsx
Fixes [#6883](https://github.com/mantinedev/mantine/issues/6883) and https://github.com/mantinedev/mantine/issues/5979
Here's a screen recording before and after the fix:
https://github.com/user-attachments/assets/ae9a799d-e586-4a27-80f7-a7368e0b68f3
> fix(hooks): resolve hydration issues by deferring state updates with startTransition in useResizing

- packages/@mantine/core/src/components/ScrollArea/ScrollAreaScrollbar/Scrollbar.tsx
`ClientRect` is deprecated in TypeScript 4.4.
Then I refactored `ClientRect` to `DOMRect`.
> [@mantine/core] refactor: type ClientRect to DOMRect

- packages/@mantine/core/src/components/PasswordInput/PasswordInput.tsx
Fixes https://github.com/mantinedev/mantine/issues/6652 by handling `touchend` event for password visibility toggle to avoid caret jump.
> [@mantine/core] Handle touchend event on password visibility toggle

- packages/@mantine/dropzone/src/mime-types.ts
Fixes https://github.com/mantinedev/mantine/issues/5866.
In addition to HEIC, we also need to add HEIF as a MIME type, otherwise some files may not function properly.
> [@mantine/dropzone] Add image HEIF to IMAGE_MIME_TYPE in @mantine/dropzone

- packages/@mantine/core/src/components/NumberInput/NumberInput.tsx
Previously values that only contain a minus would have been considered valid which triggers things like min/max clamping even though it should not.
According to the types `value` should always be a string and never undefined which made it easier to collapse the conditions into one. This fixed my reproduction script that was posted in the issue.
Fixes #6969
> Fix condition for isValidNumber in NumberInput

- packages/@mantine/core/src/components/Tabs/TabsTab/TabsTab.tsx
fixes: https://github.com/mantinedev/mantine/issues/7055
> [@mantine/core] fix: enable overrriding `tabIndex`

- packages/@mantine/charts/src/RadarChart/RadarChart.tsx
add new properties in RadarChartSeries
> [@mantine/charts] fix: Object literal may only specify known properties, and label does not exist in type RadarChartSeries

- packages/@mantine/core/src/components/Combobox/use-combobox-target-props/use-combobox-target-props.ts
fix #6978 
description:
due to call of combobox.updateSelectedOptionIndex('active', { scrollIntoView: true }); (async) in onDropdownOpen in Select.tsx the reference to the current selected option was set to -1 overwriting 0 from selectActiveOption call. Which then caused the behaviour described in the issue.
Fix provides propper setting reference to the current selected option after opening dropdown with arrows.
> Combobox: fix selecting elements after opening dropdown with arrow keys

- packages/@mantine/form/src/hooks/use-form-status/use-form-status.ts
I am using `useForm` and had the result in a dependency array. I noticed that it caused needless executions. I ended up destructuring the result of `useForm` and adding those items to the dependency array. I noticed it worked except for `resetDirty`. It appears it's the only action not wrapped in a `useCallback`. I don't see any reason why it couldn't be so I cut  a quick PR.
Semi-related issue: https://github.com/mantinedev/mantine/issues/5338
> Wrap resetDirty in a useCallback

- packages/@mantine/charts/src/CompositeChart/CompositeChart.tsx
Fixes #7010
The unique key property has been added to the area type of the composite chart to resolve the console error.
> Issue #7010 key prop added to area chart

- packages/@mantine/core/src/components/Combobox/use-combobox-target-props/use-combobox-target-props.ts
Resolves #7085
- Checks if the dropdown is open, if it's true, add "aria-controls" attribute, else, set as undefined.
> [@mantine/core] Fix combobox aria-controls attribute

- packages/@mantine/core/src/components/TagsInput/TagsInput.tsx
Alright so my last commit introduced a new bug where controlled `TagsInput`s would not have any callbacks triggered when clicking the `x` button in a pill.
This commit fixes that issue. I tested it in dash-mantine-components as well, and the behavior is now correct.
> Change TagsInput onRemove to copy correctly

- packages/@mantine/notifications/src/notifications.store.ts
e78a9bb9d23654349cf9413674dce08051322762 fixed #5640, but made the `NotificationData` type [overly broad](https://github.com/mantinedev/mantine/issues/5640#issuecomment-1936799846).
This change limits the additional keys to those that start with `data-`. This allows passing `data-` attributes _and_ narrowing the type.
> Narrow type of `NotificationData`

- packages/@mantine/charts/src/DonutChart/DonutChart.tsx
Use a similar label render function as the Pie Chart for Donut Chart in order to apply the _valueformatter_ to the label.
Also adds the _labelsType_: value or percent, similar to Pie Chart.
Omitted the inside label option since it doesn't make sense on the Donut Chart in my opinion.
> [DonutChart] Add render label function

- packages/@mantine-tests/core/src/shared/it-throws-context-error.tsx
- packages/@mantine/core/src/components/FileInput/FileInput.tsx
- packages/@mantine/core/src/components/Transition/Transition.tsx
- packages/@mantine/core/src/core/factory/create-polymorphic-component.ts
- packages/@mantine/dates/src/components/DatePicker/DatePicker.tsx
- packages/@mantine/dates/src/components/DatePickerInput/DatePickerInput.tsx
- packages/@mantine/dates/src/components/MonthPicker/MonthPicker.tsx
- packages/@mantine/dates/src/components/MonthPickerInput/MonthPickerInput.tsx
- packages/@mantine/dates/src/components/YearPicker/YearPicker.tsx
- packages/@mantine/dates/src/components/YearPickerInput/YearPickerInput.tsx
- packages/@mantine/dropzone/src/DropzoneStatus.tsx
- packages/@mantine/form/src/Form/Form.tsx
- packages/@mantinex/demo/src/ConfiguratorDemo/ConfiguratorDemo.tsx
- packages/@mantinex/demo/src/StylesApiDemo/StylesApiDemo.tsx
The global JSX namespace has been removed in react 19. 
See https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript
> [refactor] Replace global JSX with React.JSX

- packages/@mantine/core/src/components/Autocomplete/Autocomplete.tsx
- packages/@mantine/core/src/components/Combobox/Combobox.types.ts
- packages/@mantine/core/src/components/TagsInput/TagsInput.tsx
Since we decided not to change the validation requirement for the options, we should add some docs about this constraint.
See https://github.com/mantinedev/mantine/issues/7176 for previous discussion
> [@mantine/core] Update docs for Select, MultiSelect, Autocomplete to warn about data props consisting of unique values

- packages/@mantine/dates/src/components/Calendar/pick-calendar-levels-props/pick-calendar-levels-props.ts
Fixes https://github.com/mantinedev/mantine/issues/7212
The withWeekNumbers prop is currently passed to the input base in DatePickerInput instead of as part of the calendar props
Add it to pickCalendarProps
> Add withWeekNumbers to pickCalendarProps

- apps/mantine.dev/src/pages/styles/sass.mdx
Not sure this fix also works for PowerShell, but is required for git bash to resolve the path the the _mantine sass file.
Fixes #7237
> Replace backslashes by slashes so it works on Windows with git bash too

- packages/@mantine/modals/src/ModalsProvider.tsx
- packages/@mantine/modals/src/context.ts
I had a use case in my application where I needed to read from the Modals manager props, so I created this PR to allow them to be exposed to the user.
EDIT: I also discovered an error in my implementation of `updateContextModal`, which would throw the following error:
```hook.js:608 Warning: React does not recognize the `modalId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `modalid` instead. If you accidentally passed it from a parent component, remove it from the DOM element. Error Component Stack```
This occurred because the modalId was unintentionally included in the props passed to the modal component. I have resolved this in the PR by ensuring that modalId is excluded from the props spread onto the modal.
> [@mantine/modals] Expose Modals Manager props

- packages/@docs/demos/src/demos/core/Tree/data.ts
I was experimenting with tree examples and found that they don't work as shown in the demo. The values in `dataCode` are not unique.
> Fix typos in Tree code example

- packages/@mantine/dates/src/types/PickerBaseProps.ts
`allowSingleDateInRange` allows for a single day to be selected, by clicking the same value in the date input for both start and end dates.
This was not reflected in the documentation.
> (docs): updated docs, to reflect actual behaviour of allowSingleDateInRange

- packages/@mantine/core/src/components/FloatingIndicator/use-floating-indicator.ts
The `borderTopWidth` & `borderLeftWidth` from `parent` & `target` should added to translate calculation because [`getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) included that on calculation.
**Before**
**After**
It's a little bit difficult to see the difference unless you use wider border width.
- I reuse [`toInt`](https://github.com/lamualfa/mantine/blob/e5faa0d2c4df522ea981787a7da8076e6e024ec4/packages/%40mantine/core/src/components/FloatingIndicator/use-floating-indicator.ts#L4) helper from `ScrollArea` utils to [convert computed style to int](https://github.com/lamualfa/mantine/blob/e5faa0d2c4df522ea981787a7da8076e6e024ec4/packages/%40mantine/core/src/components/FloatingIndicator/use-floating-indicator.ts#L55). That helper …
> [@mantine/core] FloatingIndicator: fix translate calculations

- packages/@docs/demos/src/demos/hooks/use-favicon.demo.usage.tsx
With the current example, when logged in to X, Chrome refuses to fetch the icon. I update the example to use another cookieless domain so that the example works for everyone.
> [mantine.dev] update use-favicon hook example to use cookieless domain

- packages/@mantine/dates/src/components/Day/Day.tsx
- packages/@mantine/dates/src/components/Month/Month.tsx
- packages/@mantine/dates/src/components/Month/get-date-in-tab-order/get-date-in-tab-order.ts
- packages/@mantine/dates/src/components/Month/get-end-of-week/get-end-of-week.ts
- packages/@mantine/dates/src/components/Month/get-month-days/get-month-days.ts
- packages/@mantine/dates/src/components/Month/get-start-of-week/get-start-of-week.ts
- packages/@mantine/dates/src/components/Month/index.ts
- packages/@mantine/dates/src/components/Month/is-same-month/is-same-month.test.ts
- packages/@mantine/dates/src/components/Month/is-same-month/is-same-month.ts
> fixed dayjs another local and calendar

- packages/@mantine/hooks/src/use-debounced-callback/use-debounced-callback.test.ts
- packages/@mantine/hooks/src/use-debounced-callback/use-debounced-callback.ts
As well as give an option to simply flush on unmount, which is desirable when the callback does persisting of values (but not when it's just updating state obviously)
> useDebouncedCallback: add a flush method to returned callback

- packages/@mantine/hooks/src/use-merged-ref/use-merged-ref.test.tsx
- packages/@mantine/hooks/src/use-merged-ref/use-merged-ref.ts
fixes #7269 
useMergedRef now properly handles ref callbacks that return cleanup functions in React 19. 
For backward compatibility with React 18, it maintains the previous behavior of calling refs with null during unmount.
I have verified the functionality through a separate test repository, as direct testing within Mantine is not possible due to its React 18 dependency.
https://github.com/elecdeer/react-19-use-merge-ref/blob/main/react19/src/use-merged.ref.test.tsx
> [@mantine/hooks] Support ref cleanup function in React 19 with useMergedRef

- packages/@mantine/core/src/components/Avatar/get-initials-color/get-initials-color.test.ts
- packages/@mantine/core/src/components/Avatar/get-initials-color/get-initials-color.ts
**Problem:**
In the Avatar component, the `getInitialsColor` function was using only the initials of a name to generate a hash, which determined the color of the avatar. This led to the issue where different names with the same initials would receive the same color, even if the full names were different.
**Solution:**
The function now uses the full name to generate the hash. By removing the use of `getInitials()` inside the `hashCode()` call, each unique name will produce a unique hash, ensuring a unique color for each different name.
**Details:**
- The `hashCode()` call is updated to process the entire name, not just the initials.
- This change maintains the internal implementation without affecting the public API.
- The behavior of the `getInitialsColor` function remains consistent, …
> Fix Avatar initials color hashing to use full name

- packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.tsx
fixes #7305 
Corrected with reference to fix #7229.
> [@mantine/dates] Fix `hasNextLevel` prop type leak to DateTimePicker component

- packages/@mantine/core/src/components/ModalBase/ModalBase.tsx
refer to https://github.com/mantinedev/mantine/issues/6967#issuecomment-2417439117
> [docs] Update ModalBase default transition value from 'pop' to 'fade-down'

- packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.tsx
This change sets the milliseconds of a picked `dateTime` to 0. This ensures consistency and avoids issues when comparing `Date` objects modified by the datetime picker.
When using the datetime picker, the inclusion of milliseconds can lead to unexpected behavior during date comparisons. For example when pick 2025-01-01T16:00+0100 in the DateTimePicker and do this comparison.
```javascript
new Date('2025-01-01T16:00+0100') >= <DatePickedWithDateTimePicker>
```
This comparison will always return false due to the additional milliseconds present in the picked dateTime.
By normalizing milliseconds to 0, the behavior aligns with the existing practice of setting seconds to 0. This ensures:
- More intuitive and predictable behavior.
- Easier comparisons between Date objects.
- The milliseconds of …
> Normalize milliseconds in picked dateTime in DateTimePicker to 0

- apps/mantine.dev/src/pages/hooks/use-interval.mdx
Fix typo with import of `@mantine/hooks` in code example in `use-interval.mdx`
> [docs] Fix typo with import of `@mantine/hooks` in code example in `use-interval.mdx`

- packages/@mantine/core/src/components/Combobox/use-combobox-target-props/use-combobox-target-props.ts
fixes #7337 
The method of judging escape key press events is now the same as for Modal.
https://github.com/mantinedev/mantine/blob/e8f7b01f85149e6f7d9776ef41703bab739f5d4d/packages/%40mantine/core/src/components/ModalBase/use-modal.ts#L37
> [@mantine/core] Fix On Escape KeyDown handling to Combobox component

- apps/mantine.dev/src/pages/hooks/use-isomorphic-effect.mdx
According to implementation notes and meta data it's a replacement for `useLayoutEffect` instead of `useEffect`:
https://github.com/mantinedev/mantine/blob/e8f7b01f85149e6f7d9776ef41703bab739f5d4d/apps/mantine.dev/src/mdx/data/mdx-hooks-data.ts#L93
https://github.com/mantinedev/mantine/blob/e8f7b01f85149e6f7d9776ef41703bab739f5d4d/packages/%40mantine/hooks/src/use-isomorphic-effect/use-isomorphic-effect.ts#L3-L4
> [mantine.dev] Fix description in use-isomorphic-effect

- packages/@mantine/core/src/core/MantineProvider/use-mantine-color-scheme/use-provider-color-scheme.ts
[This PR](https://github.com/mantinedev/mantine/pull/7147) broke my testing setup. In some cases `window.matchMedia("(prefers-color-scheme: dark)")` returns undefined and breaks my tests. Optional chaining solves it.
> [@mantine/core] Handle undefined value in matchMedia

- packages/@mantine/hooks/src/use-in-viewport/use-in-viewport.ts
fixes #7340 
IntersectionObserver's Handler now handles cases where there is more than one Entry.
https://codesandbox.io/p/sandbox/mantine-7340-6w3krx?file=%2Fsrc%2FDndList.tsx%3A89%2C1-92%2C12
> [@mantine/hooks] Fix Handling of multiple Entries to useInViewport

- packages/@mantine/form/src/hooks/use-form-status/use-form-status.ts
- packages/@mantine/form/src/tests/use-form/resetDirty.test.ts
When using `form.resetDirty` and passing an object as argument, it's expected that the object being passed should act as the new baseline for the dirty checking. Currently, because of how the objects are being spread it does not behave like this and in fact basically does the same thing as not having passed any argument at all.
This PR should fix this :)
> fix: changed spreading order in form.resetDirty to make it behave correctly

- apps/help.mantine.dev/src/pages/q/data-grid-i-need.mdx
- changelog/7.6.0.md
Fix broken links
- Updates the broken template submission link in the 7.2.0 changelog to point to the contribution guidelines page (`mantine.dev/contribute`).
- From `https://mantine.dev/code/table/` to `https://mantine.dev/core/table/`
- Verified the new link redirects to the correct contribution guidelines page
- No code changes, only documentation update
This change aligns with Mantine's goal of improving documentation and maintaining clear contribution pathways for the community.
> [docs]: Fix broken table link in data-grid-i-need and template submission link in changelog

- packages/@mantine/hooks/src/use-event-listener/use-event-listener.ts
- packages/@mantine/hooks/src/use-focus-within/use-focus-within.ts
- packages/@mantine/hooks/src/use-hover/use-hover.ts
- packages/@mantine/hooks/src/use-move/use-move.ts
- packages/@mantine/hooks/src/use-radial-move/use-radial-move.ts
Fixes #7406
Directly accessing the value of a ref in a `useEffect` cleanup function can lead to problems, as refs “live” outside of React's rendering cycle and it can therefore happen that the value of the ref changes between the first execution and the cleanup.
See ESLint warning:
This is not just a theoretical problem. I encountered a bug after upgrading to React 19 while running in dev mode. My callback passed to the `onChange` prop of a `Slider` component (which uses `useMove` internally) was not updated and therefore used a stale variable that was captured by the closure. I believe this is related to React calling the useEffect hooks twice in development mode, although I'm not sure why this only happens with React 19 and not React 18, which introduced this behavior.
> Fix potential dangerous access of ref value in useEffect cleanup

- packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.test.tsx
- packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.tsx
`DateTimePicker` uses `useUncontrolledDates` hook which is already using the context from the `DateProvider` to convert the default value into the `DateProvider`s timezone. 
In the `DateTimePicker` we shouldn't do another `.tz()` that will convert the date & time into the `DateProvider`'s timezone, the result will be incorrect if that's the implementation. 
Fix was to pass `true` to the `.tz()`'s second parameter (`keepLocalTime`), which doesn't convert the value again to the `DateProvider`'s timezone.
Closes https://github.com/mantinedev/mantine/issues/7388
> [@mantine/dates] DateTimePicker: prevent converting value to DateProvider twice

- apps/mantine.dev/src/pages/hooks/use-hotkeys.mdx
- packages/@mantine/hooks/src/use-hotkeys/parse-hotkey.ts
- packages/@mantine/hooks/src/use-hotkeys/use-hotkeys.test.tsx
- packages/@mantine/hooks/src/use-hotkeys/use-hotkeys.ts
We have multiple users of our apps using non-QWERTY keyboard layouts. Given the nature of the app, and the need for inputs to be collocated sensibly (thinking camera manipulation), this convenience hook caused issues for our non-QWERTY users. 
This change corrects that. Open to feedback & adjustments, and hoping this is useful.
- [KeyboardEvent: code property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)
- [Code values for keyboard events](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values)
> [@mantine/hooks] use-hotkey: Clarifying use of physical key assignments

- packages/@mantine/dates/src/components/Month/get-month-days/get-month-days.ts
fixes https://github.com/mantinedev/mantine/issues/7441
**Issue:**
The original code encountered an issue when creating a dayjs object using a formatted string (dayjs(day.format('YYYY-M-D'))). This resulted in Safari producing invalid dates, leading to NaN values. This caused the while loop to continuously execute the getEndOfWeek() function, ultimately freezing the component in Safari.
**Root Cause:**
The format() method in dayjs converts the date to a string (ISO format), which Safari does not parse correctly in certain edge cases, especially with extreme years (e.g., 4543 as described in https://github.com/mantinedev/mantine/issues/7441). When re-parsed back into a dayjs object, the resulting date was invalid, causing subsequent calculations and date manipulations to fail.
**Fix:**
- …
> [@mantine/dates]:DateInput component freezes the page on Safari 

- packages/@mantine/core/src/components/ScrollArea/ScrollAreaScrollbar/Scrollbar.tsx
This should be a proper fix for the issue https://github.com/mantinedev/mantine/issues/6681
I think another option would be to also handle `pointercancel` event, but `lostpointercapture` should cover everything. Not sure that handling `pointerup` is even required in this case, but I left it just in case.
Related commit https://github.com/mantinedev/mantine/commit/ccc0f3c42284c6fdbe671732aabee0d9299eb98d
The issue is reproducible on the mantine website
https://github.com/user-attachments/assets/41f041c1-256f-4685-8756-6545987e7ff6
> [@mantine/core] ScrollArea: Fix user-select being left as none after interaction with scrollbar

- packages/@mantine/core/src/core/MantineProvider/color-functions/get-gradient/get-gradient.test.ts
- packages/@mantine/core/src/core/MantineProvider/color-functions/get-gradient/get-gradient.ts
Resolves https://github.com/mantinedev/mantine/issues/7439
The bug reporter identified the solution in the report. Because `0` is a valid value but considered falsy in Javascript, using the logical OR (`||`) was causing a `deg={0}` to default to the defaultTheme's `45` value.
Before:
https://github.com/user-attachments/assets/628daa5e-6a47-488d-a5dc-7172efa118e1
After:
https://github.com/user-attachments/assets/a32d452d-410e-453e-8184-189c26171244
> fix: [@mantine/core] update get-gradient deg to use nullish coalescing operators

- apps/mantine.dev/src/pages/core/anchor.mdx
- packages/@docs/demos/src/demos/core/Anchor/Anchor.demo.decoration.tsx
Saw in the changelog for the latest version that a `not-hover` value was added for the `underline` prop of the `Anchor` component, but the new value has not been added neither in the documentation page nor in the example. 
I added both of these changes.
Hope it's all good!
> [mantine.dev] Add `not-hover` underline option to Anchor documentation and demo

- mise.toml
- packages/@mantine/code-highlight/src/CodeHighlightTabs.tsx
Instead of throwing unsupported code error, it fallback to plaintext.
It's the current behaviour of CodeHighlight component.
> Update CodeHighlightTabs.tsx: Fallback unsupported code to plaintext

- apps/mantine.dev/src/combobox-examples/examples/ActiveOptionsFilter/ActiveOptionsFilter.tsx
- apps/mantine.dev/src/combobox-examples/examples/BasicMultiSelect/BasicMultiSelect.tsx
- apps/mantine.dev/src/combobox-examples/examples/MaxDisplayedItems/MaxDisplayedItems.tsx
- apps/mantine.dev/src/combobox-examples/examples/MaxSelectedItems/MaxSelectedItems.tsx
- apps/mantine.dev/src/combobox-examples/examples/MultiSelectCheckbox/MultiSelectCheckbox.tsx
- apps/mantine.dev/src/combobox-examples/examples/MultiSelectCreatable/MultiSelectCreatable.tsx
- apps/mantine.dev/src/combobox-examples/examples/MultiSelectValueRenderer/MultiSelectValueRenderer.tsx
- apps/mantine.dev/src/combobox-examples/examples/SearchableMultiSelect/SearchableMultiSelect.tsx
- packages/@docs/demos/src/demos/core/Combobox/Combobox.demo.multiselect.tsx
- packages/@docs/demos/src/demos/core/Combobox/Combobox.demo.searchableMultiselect.tsx
This PR addresses a potential runtime error in Combobox multiselect components when pressing Backspace with no selected values, while maintaining contribution guidelines compliance.
**Changes:**
✅ Validation improvements:
- Merged conditional checks in event handlers
- Added explicit array length checks before removal
- Maintained browser default behavior when no values selected
**Compliance:**
- 🔄 Follows project contribution workflow:
1. Identified edge case in existing components
2. Implemented targeted fix without API changes
3. Maintained existing code style and patterns
**Impact:**
- Prevents `value[-1]` access attempts in all multiselect implementations
- Affects documentation examples and component demos
- No breaking changes introduced
> fix: Prevent invalid index access on Backspace with empty selection

- packages/@mantine/core/src/components/Checkbox/Checkbox.test.tsx
- packages/@mantine/core/src/components/Checkbox/Checkbox.tsx
Closes https://github.com/mantinedev/mantine/issues/7608
Set `indeterminate` property in native `input` element when `indeterminate` component prop is true. Prefer `indeterminate` over `aria-checked` per spec (https://www.w3.org/TR/html-aria/#att-checked).
References
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/indeterminate
- https://github.com/testing-library/jest-dom/blob/main/src/to-be-partially-checked.js
- https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox-mixed/
- https://medium.com/indigoag-eng/indeterminate-checkboxes-are-weird-704b246c0f19
> [@mantine/core] Checkbox - Set indeterminate prop (#7608)

- packages/@mantine/modals/src/index.ts
I have a type checking issue in my repository, similar to the one described in https://github.com/mantinedev/mantine/issues/4991#issuecomment-1784254633 with `@mantine/modals/lib/index.d.mts`
Which was then fixed in https://github.com/mantinedev/mantine/pull/5697
I couldn't get the [paths workaround](https://github.com/mantinedev/mantine/issues/4991#issuecomment-1784456011) working, so to solve this locally I can
1. Delete`@mantine/modals/lib/index.d.mts` in `postinstall` script and it will rely on the non-module file `@mantine/modals/lib/index.d.ts`
2. Or, patch the file to add `.js` to exports
This PR makes the change to do `2.`
Tbh I don't really know what I'm doing, I suspect we don't want to do this because I believe it will also add `.js` to the non-module …
> fix: modal exports for node16

- packages/@mantine/core/src/components/AppShell/AppShell.module.css
[AppShell's disabled prop](https://mantine.dev/core/app-shell/#disabled-prop) doesn't disable aside and footer margins, which means that currently AppShell create margins at bottom and right (right margin is 316, bottom margin is 76):
This PR will remove margins.
> fix: `AppShell[disabled]` does not cancel aside and footer margins

- packages/@mantine/core/src/components/ScrollArea/ScrollArea.tsx
When using `offsetScrollbars="present"`, it was possible to hover over and reveal the scrollbar background even when the thumb was hidden. This behavior was incorrect, as the scrollbar should be entirely hidden when the thumb isn't visible.
This is how it looked when hovering over a vertical scrollbar that is hidden using `offsetScrollbars=present`:
With this PR, the scrollbar background no longer appears when the thumb is hidden, as expected.
> fix: Scrollbars remain interactive with offsetScrollbars="present" when thumb is hidden

- packages/@mantine/core/src/components/Slider/Slider/Slider.tsx
- Added `onChangeEndRef` for a consistent reference to `onChangeEnd`.
- Replaced direct calls to `onChangeEnd` with `callOnChangeEnd` utility function for improved reliability and maintainability.
Fixes #7620
> [@mantine.core] fix Slider changeEnd.tsx #7620

- packages/@docs/demos/src/demos/core/Table/Table.demo.stickyHeader.tsx
This pull request includes changes to the `Table` component in the `@mantine/core` package to enhance its functionality and styling. The most important changes include updating the CSS for sticky headers and table borders.
Styling updates for `Table` component:
* [`packages/@mantine/core/src/components/Table/Table.module.css`](diffhunk://#diff-48836b6a87a52fcd25cb522337b4cf12a22517256305afce10d093c4368e361dR102-R113): Updated CSS to handle sticky headers and table borders, including setting the `top` property for `th` elements within sticky headers and adding styles for tables with borders.
Fixes https://github.com/mantinedev/mantine/issues/7593
> When using stickyHeader with withTableBorder and withColumnBorders, border sometimes shows up and sometimes doesn't

- packages/@mantine/core/src/components/Paper/Paper.module.css
Hello, I noticed the `Paper` component didn't have a dedicated CSS variable for controlling its border color just like the `AppShell` or the `Tabs` components do. Having this setup makes it easier to override when building a custom theme.
I followed [what AppShell does as an example](https://github.com/mantinedev/mantine/blob/master/packages/@mantine/core/src/components/AppShell/AppShell.module.css#L13-L19), i.e:
```css
.root {
@mixin light {
--app-shell-border-color: var(--mantine-color-gray-3);
}
@mixin dark {
--app-shell-border-color: var(--mantine-color-dark-4);
}
}
.navbar {
&:where([data-with-border]) {
border-inline-end: 1px solid var(--app-shell-border-color);
}
}
```
> [@mantine/core] Paper: Control border color using dedicated CSS variable

- apps/mantine.dev/src/pages/guides/typescript.mdx
- packages/@mantine/core/src/components/Flex/Flex.tsx
- packages/@mantine/core/src/components/Input/InputDescription/InputDescription.tsx
- packages/@mantine/core/src/components/Input/InputError/InputError.tsx
- packages/@mantine/core/src/components/Input/InputLabel/InputLabel.tsx
- packages/@mantine/core/src/components/Input/InputWrapper/InputWrapper.tsx
- packages/@mantine/core/src/components/NavLink/NavLink.tsx
- packages/@mantine/core/src/components/Pagination/Pagination.tsx
- packages/@mantine/core/src/components/Text/Text.tsx
- packages/@mantine/core/src/components/Title/Title.tsx
- packages/@mantine/core/src/core/MantineProvider/theme.types.ts
This PR is to address issue #7642
Fixes #7642 
What's changed:
- Export `MantineThemeSizesOverride`, which can help to enhance types for size related theme overrides, like `MantineThemeColorsOverride` is to `theme.colors`.
- Updated docs on how to augment sizes override.
- Updated `size` prop types in some components (from referencing `MantineSize` to referencing more dedicated size, like `MantineFontSize`, `MantineSpacing`, etc..)
- only those have clear clues that the prop expects a certain kind of size, were updated (e.g. `Text.size`)
- some components use size prop for multiple purposes, like `Button.size`, and should be kept as they were (referencing `MantineSize`)
All changes should be backward compatible, not breaking anything (to the best of my knowledge).
> [@mantine/core] better type support for size related theme overrides

- packages/@mantine/hooks/src/use-hotkeys/parse-hotkey.test.ts
- packages/@mantine/hooks/src/use-hotkeys/parse-hotkey.ts
Fix issue with `useHotkeys` hook with a French ISO layout. `Q` and `A` as long as `Z` and `W` keys are interverted with a FR keyboard layout. Using both the `key` and the `code` property currently triggers both events (on `Z` and `W` for example). This fix will prevent using the `code` property that lead to this issue.
See more details here https://github.com/mantinedev/mantine/pull/7390
> [@mantine/hook] useHotkeys: Correctly handle key matcher for FR keyboard layout

- packages/@mantine/dates/src/components/Month/Month.tsx
- packages/@mantine/dates/src/components/Month/get-date-in-tab-order/get-date-in-tab-order.ts
- packages/@mantine/dates/src/components/Month/index.ts
- packages/@mantine/dates/src/components/Month/is-same-month/is-same-month.test.ts
- packages/@mantine/dates/src/components/Month/is-same-month/is-same-month.ts
In [pull request #7302](https://github.com/mantinedev/mantine/pull/7302), two main changes were introduced:
We patched parts of the codebase to allow the library to work correctly with alternative calendars (e.g., Jalali). This part of the change was successful — we’ve integrated it into our own project and it's now functioning properly within a non-Gregorian calendar setup.
The assumption was that Day.js’s isSame function would correctly handle month comparisons across all calendar systems. However, we later discovered that isSame does not work reliably for non-Gregorian calendars — it fails to compare months correctly. This PR reverts that change and restores the original internal isSameMonth function to maintain expected behavior.
This fix ensures consistent support for both Gregorian …
> Fix: Revert isSame usage due to Day.js calendar bug

- apps/mantine.dev/src/pages/guides/react-router.mdx
This PR corrects a page title in the `ReactRouter` documentation that was mistakenly labeled as `Remix`.
> [mantine.dev] Fix incorrect page title on ReactRouter docs

- apps/mantine.dev/src/pages/guides/7x-to-8x.mdx
extends() —> extend() of components
> Correction of typos in the migration guide from 7x to 8x

- packages/@mantine/form/src/types.ts
Noticed this was missing from the type
> add defaultChecked to GetInputPropsReturnType

- packages/@mantine/core/src/components/ModalBase/use-modal.ts
When opening a modal with the `closeOnEscape` option enabled, pressing Escape during IME conversion unintentionally closes the modal.
The expected behavior is that pressing Escape should only cancel the IME composition—not close the modal.
To address this, I added a check for the composing status in the keydown event handler.
1. Type "とうきょう"
1. Press space to start text conversion
1. Press Escape → modal closes unexpectedly
https://github.com/user-attachments/assets/029c5e43-af0a-4673-aefe-0b8255936633
1. Type "とうきょう"
1. Press space to start text conversion
1. Press Escape → cancels conversion
1. Press Escape → cancels input
1. Press Escape → closes modal
https://github.com/user-attachments/assets/d74b9540-458f-431e-939c-16cacc1058d6
1. Type "tokyo"
1. Press Escape → closes modal …
> [@mantine/core] Fix unintended modal close during IME composition

- apps/mantine.dev/src/components/MdxProvider/MdxTemplatesList/community-data.ts
- packages/@mantine/hooks/src/use-idle/use-idle.test.tsx
- packages/@mantine/hooks/src/use-idle/use-idle.ts
- Add 'wheel' event to the default events of the use-idle hook.
[Screencast from 2025-04-09 15-35-02.webm](https://github.com/user-attachments/assets/79ebdb08-5f9a-47d3-8538-4d41af11b8af)
fix: #7574
> fix: add 'wheel' event to use-idle hook

- packages/@mantine/form/src/use-field.ts
Fixes #7735
I fixed the bug I discovered in #7735 by adding onValueChange to the dependency array.
> fix UseFieldInput.onValueChange is not being updated #7735

- packages/@docs/demos/src/demos/hooks/Hooks.demos.story.tsx
- packages/@docs/demos/src/demos/hooks/index.ts
- packages/@docs/demos/src/demos/hooks/use-debounced-callback.demo.unmount.tsx
- packages/@mantine/form/src/use-field.ts
- packages/@mantine/hooks/src/use-debounced-callback/use-debounced-callback.ts
Fixes #7684 
Fixed the hook by adding isPendingRef to track pending callbacks. Now it only executes on unmount when truly necessary, passing the failing test. Added a Storybook demo to show the flushOnUnmount functionality in action
Issue
In the previous implementation of useDebouncedCallback, the flushOnUnmount option didn't work correctly in certain cases. When a component unmounted, even with flushOnUnmount: true, the debounced value wasn't properly applied.
The issue was that lastCallback.flush was initially set to noop and dynamically reassigned during each invocation, but the cleanup function in useEffect didn't always have access to the latest version of this function.
Fix
Modified the implementation to
Add isPendingRef to explicitly track whether there's a pending callback …
> [@mantine/hooks] useDebouncedCallback flushOnUnmount does not work #7684

- packages/@docs/demos/src/demos/charts/RadarChart/RadarChart.demo.customTooltip.tsx
- packages/@docs/demos/src/demos/charts/RadarChart/RadarChart.demo.parts.tsx
- packages/@docs/demos/src/demos/charts/RadarChart/RadarChart.demo.tooltip.tsx
- packages/@docs/demos/src/demos/charts/RadarChart/RadarChart.demos.story.tsx
- packages/@docs/demos/src/demos/charts/RadarChart/index.ts
- packages/@docs/styles-api/src/data/RadarChart.styles-api.ts
- packages/@mantine/charts/src/RadarChart/RadarChart.tsx
In the latest Mantine version `7.17.5` RadarChart does not have any tooltips. This PR implements them with a Storybook demo of custom tooltip.
Tooltip example:
Custom tooltip demo:
> [@mantine/charts] RadarChart: Add Tooltips and Dots

- packages/@mantine/hooks/src/use-resize-observer/UseResizeObserver.story.tsx
- packages/@mantine/hooks/src/use-resize-observer/use-resize-observer.test.tsx
- packages/@mantine/hooks/src/use-resize-observer/use-resize-observer.ts
fix: #7582 
- Use `borderBoxSize` or `contentBoxSize` from `ResizeObserverEntry` instead of `contentRect`
- Fallback to `contentRect` for backward compatibility
- add use-resize-observer.test.tsx
- add UseResizeObserver.story.tsx
> [@mantine.hook] feat handle writing-mode in useResizeObserver for accurate box size calculation

- packages/@mantine/core/src/components/NumberInput/NumberInput.test.tsx
- packages/@mantine/core/src/components/NumberInput/NumberInput.tsx
fix: #7765
test(NumberInput): add onBlur min/max clamping and large value edge case tests
- Add tests to verify value is clamped to min or max on blur when input is out of bounds
- Ensure clamping works with both regular and very large min/max values
> [@mantine.core] fix NumberInput big number issue

- packages/@mantine/core/src/components/Stepper/Stepper.module.css
Hello 👋 I noticed that the Stepper separator had a different color between horizontal and vertical orientations. For instance you can see this on the docs website:
| Vertical | Horizontal |
| --- | --- |
|![image](https://github.com/user-attachments/assets/d8c8467e-641b-4006-9eec-db59332aed99)|![image](https://github.com/user-attachments/assets/c1328c63-d8ef-421b-8559-25ef890e6577)|
| `mantine-color-gray-1` | `mantine-color-gray-2` |
While looking at the code I saw some dead code so I figured I would open a PR with a small cleanup. Here's a summary of what I did:
- `getStyles('separator')` is only every applied when `orientation === 'horizontal'` so the whole rule for `.separator &:where([data-orientation='vertical'])` can be deleted.
- defined `--stepper-outline-color` variable to make …
> [@mantine/core] Stepper: fix separator color

- packages/@mantine/dates/src/components/TimePicker/TimeControlsList/TimeControlsList.tsx
> [@mantine/dates] TimePicker: 00 in dropdown is reachable with arrow keys when it was outside of scroll

- packages/@mantine/core/src/components/Collapse/Collapse.story.tsx
- packages/@mantine/core/src/components/Collapse/use-collapse.ts
I am considering removing `display: none` from the hidden styles in the Collapse component, and relying only on `height: 0` and `overflow: hidden` to hide content when collapsed.
- Using `display: none` causes issues with nested Collapses and prevents child animations from triggering correctly when the parent is reopened.
- Removing `display: none` allows for smoother transitions, better support for nested Collapses, and more consistent state updates for children.
- With `display: none`, content is removed from the accessibility tree, which is sometimes desirable, but it also prevents focus management and dynamic content updates.
- Using `height: 0` and `overflow: hidden` keeps the content in the DOM and accessibility tree. To address focus issues, we can blur any focused element inside a …
> [@mantine/core] fix useCollapse remove  collapsedStyles  display: 'none'

- packages/@docs/demos/src/demos/core/MultiSelect/MultiSelect.demo.renderOption.tsx
I noticed that the code attached as a demo on this page ( https://github.com/mantinedev/mantine/blob/39360296221bced9adaf098135ff676f214c5022/packages/%40docs/demos/src/demos/core/MultiSelect/MultiSelect.demo.renderOption.tsx ) differs from the actual working implementation. To avoid confusion, the demo should reflect the exact same code as the one that is actually being executed.
> [mantine.dev] Make the demo and actual code consistent

- packages/@mantine/form/src/hooks/use-form-values/use-form-values.ts
- packages/@mantine/form/src/tests/use-form/resetField.test.ts
- packages/@mantine/form/src/types.ts
- packages/@mantine/form/src/use-form.ts
This pull request introduces the `resetField` method to the Mantine form utilities. This method allows resetting individual fields to their initial values. 
- Added `resetField` method to form utilities.
- Updated types, hooks, and relevant tests to integrate the new functionality.
- Ensured consistent behavior in both controlled and uncontrolled modes.
> [@mantine/form] Add `resetField` method to form utilities

- packages/@mantine/core/src/core/types.ts
Allows data-* attributes to be boolean type.
For us, it's common to write data attributes like:
```tsx
<Button
data-disabled
...
/>
```
which just serializes like `data-disabled="true"`. I think there is no need to prevent that.
> [@mantine/core] Fix: add boolean to data attribute types

- packages/@mantine/core/src/components/Select/Select.tsx
If the value is not controlled, and you mutate the data prop, the onSearchChange will call causing problems.
From what I can tell the issue was introduced with https://github.com/mantinedev/mantine/commit/b22de41c6dfe68720ef031e3cd98b3efa2de0ab9 
Relates to https://github.com/mantinedev/mantine/issues/7801
> Select checking for searchControlled

- packages/@mantine/core/src/components/Slider/Track/Track.tsx
My goal is to make a RangedSlider that looks something like this:
So after messing around a bit I ended up with the following props: 
```tsx
<RangeSlider thumbSize="6" styles={{ thumb: { borderWidth: 0 }}} />
```
However, by default, the `bar` component of the slider is not placed at equal distances from both of the thumbs, so it looks horrible:
After playing around in firefox's css inspector for a bit, I was able to figure out that changing the `--slider-bar-width` property of the `mantine-Slider-bar` div as such fixed the issue:
This makes sense in my head; First the bar's offset is set to the correct left side unfilled percentage, but then its subtracted by `--slider-size` for some padding (I assume). Now, after the width of the bar is set to the exact filled percentage, the right side …
> Slider: update `--slider-bar-width` to use `2*var(--slider-size)`

- apps/mantine.dev/src/pages/styles/rem.mdx
- packages/@mantine/core/src/core/Box/style-props/parse-style-props/parse-style-props.test.ts
- packages/@mantine/core/src/core/utils/get-size/get-size.test.ts
- packages/@mantine/core/src/core/utils/units-converters/rem.test.ts
- packages/@mantine/core/src/core/utils/units-converters/rem.ts
As discussed on Discord, this MR changes the logic of the `rem` function to only scale px values, not rem values.
This impacts a few test files, I tried to change things to relevant values for what each test was testing.
> [@mantine/core] stop scaling explicit rem units in rem function

- packages/@mantine/core/src/components/Menu/MenuSub/MenuSub.tsx
Currently, it doesn't work to pass in `offset`, `position`, or `transitionProps` to `Menu.Sub`:
```typescript
<Menu.Sub
position="right"
offset={20}
transitionProps={{ duration: 150, transition: "fade" }}
> // These props have no effect
```
It appears this is because the `props` and `defaultProps` parameters that are passed into `useProps` are the wrong way round which means the props the user is passing in are getting set as the default and then overridden by the props that are intended to be the default.
```typescript
// packages/@mantine/core/src/components/Menu/MenuSub/MenuSub.tsx
const defaultProps: Partial<MenuSubProps> = {
offset: 0,
position: 'right-start',
transitionProps: { duration: 0 },
};
export function MenuSub(_props: MenuSubProps) {
const { children, closeDelay, ...others …
```
> [@mantine/core] Fix: MenuSub prop defaults not being overridden

- packages/@mantine/hooks/src/use-debounced-callback/use-debounced-callback.test.ts
- packages/@mantine/hooks/src/use-debounced-callback/use-debounced-callback.ts
This follows the same pattern as `useDebouncedState` to allow the caller to choose whether the callback should be fired immediately, or whether to wait until the delay duration passes.
> Allow useDebouncedCallback to be fired immediately

- packages/@mantine/charts/src/BarChart/BarChart.story.tsx
Regarding (issue: #7562 )
After investigating, Reference area does work when imported as child components. I have added some examples to the storybook component to demonstrate how to use reference area(from rechart) with mantine. also left comments in the story file that will guide users on how to successfully use reference area in their charts.
> chore: create examples on how to use reference area in charts

- packages/@mantine/core/src/components/Slider/RangeSlider/RangeSlider.tsx
- packages/@mantine/core/src/components/Slider/Slider.story.tsx
- packages/@mantine/core/src/components/Slider/Slider/Slider.tsx
This pull request introduces the `domain` prop to both `Slider` and `RangeSlider` components in the `@mantine/core` library. The `domain` prop allows for defining a complete range of possible values, independent of `min` and `max`, enabling more flexible and customizable value ranges.
- Added `domain` prop to `Slider` and `RangeSlider` for handling custom value ranges.
- Updated internal calculations to use the `domain` prop while clamping values within `min` and `max`.
- Added a story named `DomainSlider` to demonstrate the `domain` prop usage.
> Add `domain` prop to Slider and RangeSlider for custom ranges

- packages/@mantine/hooks/src/utils/shallow-equal/shallow-equal.ts
**Description**
This pull request addresses an issue where `useShallowEffect` would incorrectly re-trigger when a dependency was `NaN` in both the previous and current renders. React's native `useEffect` hook treats `NaN` as equal to `NaN` for dependency comparison (following `Object.is` semantics), meaning the effect does not re-run in such cases. This change brings `useShallowEffect`'s behavior in line with `useEffect` for `NaN` values.
The root cause was the `shallowEqual` utility function, which previously treated `NaN` as not equal to itself (`NaN !== NaN` is `true` under strict equality).
**Changes Made**
The primary modifications were made to the `shallowEqual` function to ensure `NaN` values are considered equal:
1.  **Top-Level NaN Argument Handling:**
* Added a check at the …
> [@mantine/core] Fix NaN handling in shallowEqual and useShallowEffect

- apps/mantine.dev/src/pages/form/get-input-props.mdx
When form mode is `"uncontrolled"` no `value` is present. Instead, `defaultValue` is being used.
> Add `defaultValue` to `form.getInputProps()` docs

- packages/@mantine/core/src/components/Menu/MenuSub/MenuSub.tsx
`Menu.Sub` has the following default props:
```tsx
// packages/@mantine/core/src/components/Menu/MenuSub/MenuSub.tsx
const defaultProps: Partial<MenuSubProps> = {
offset: 0,
position: 'right-start',
transitionProps: { duration: 0 },
};
```
But the documentation(for props) currently looks like(see *Menu.Sub component props* https://mantine.dev/core/menu/?t=props):
While implementing the Menu.Sub component with Popover, it seemed that the documentation had not been updated, so we updated it.
After:
> [@mantine/core] Fix: MenuSub defaultProps docs

- packages/@mantine/dates/src/components/Day/Day.test.tsx
- packages/@mantine/dates/src/components/Month/get-date-in-tab-order/get-date-in-tab-order.test.ts
Two test files were failing due to timezone-related issues:
1. `packages/@mantine/dates/src/components/Month/get-date-in-tab-order/get-date-in-tab-order.test.ts`
- Test case: `returns current day`
- Expected: `"2025-05-22"` (UTC)
- Received: `"2025-05-23"` (local KST)
2. `packages/@mantine/dates/src/components/Day/Day.test.tsx`
- Test case: `adds data-today attribute if date is the same as today`
- Failed to find expected `data-today` attribute
The tests were using `new Date().toISOString().split('T')[0]` which returns dates in UTC. This caused failures when the local date (e.g., KST, UTC+9) was different from the UTC date. For example, when it's May 23 in KST, it's still May 22 in UTC.
1. **In `get-date-in-tab-order.test.ts`**:
- Updated the `returns current day` test to use …
> Fix: Date-related test failures due to UTC/local timezone mismatch Issue

- apps/mantine.dev/src/pages/core/hover-card.mdx
- packages/@docs/demos/src/demos/core/HoverCard/HoverCard.demo.group.tsx
- packages/@docs/demos/src/demos/core/HoverCard/HoverCard.demos.story.tsx
- packages/@docs/demos/src/demos/core/HoverCard/index.ts
- packages/@mantine/core/src/components/HoverCard/HoverCard.context.ts
- packages/@mantine/core/src/components/HoverCard/HoverCard.story.tsx
- packages/@mantine/core/src/components/HoverCard/HoverCard.tsx
- packages/@mantine/core/src/components/HoverCard/HoverCardDropdown/HoverCardDropdown.tsx
- packages/@mantine/core/src/components/HoverCard/HoverCardGroup/HoverCardGroup.context.ts
- packages/@mantine/core/src/components/HoverCard/HoverCardGroup/HoverCardGroup.tsx
- packages/@mantine/core/src/components/HoverCard/HoverCardTarget/HoverCardTarget.tsx
- packages/@mantine/core/src/components/HoverCard/index.ts
- packages/@mantine/core/src/components/HoverCard/use-hover-card.ts
This pull request introduces improvements to the `HoverCard` component:
- Refactored `HoverCard` to simplify group handling and centralize delay logic using the `use-hover-card` hook.
- Added `HoverCard.Group` to synchronize open/close delays across multiple `HoverCard` components.
- Updated demo examples to showcase the new group functionality and delay timing.
- Performed minor cleanups, including import consistency, removal of unused code, and compliance with formatting standards.
> enhance HoverCard component with group delay logic

- apps/mantine.dev/src/mdx/data/mdx-hooks-data.ts
- apps/mantine.dev/src/mdx/mdx-nav-data.ts
- apps/mantine.dev/src/pages/hooks/use-selection.mdx
- packages/@docs/demos/src/demos/hooks/Hooks.demos.story.tsx
- packages/@docs/demos/src/demos/hooks/index.ts
- packages/@docs/demos/src/demos/hooks/use-selection.demo.usage.tsx
- packages/@mantine/hooks/src/index.ts
- packages/@mantine/hooks/src/use-selection/use-selection.test.ts
- packages/@mantine/hooks/src/use-selection/use-selection.ts
This PR introduces a new **`useSelection`** React hook to the `@mantine/hooks` package. This hook provides a comprehensive and intuitive API for managing selection state in various UI components like lists, tables, or multi-select inputs.
* **Flexible Selection Management:** Includes `select`, `deselect`, and `toggle` functions for granular control over individual item selection.
* **Convenience Flags:** Exposes `isAllSelected` and `isSomeSelected` flags to quickly determine the overall selection status, optimized for a better user experience (e.g., `isAllSelected` is `false` if `data` is empty).
* **Direct State Control:** Allows direct manipulation of the selection array via `setSelection`.
* **Reset Functionality:** Provides a `resetSelection` function to easily clear the current …
> [@mantine/hooks] Add `useSelection` hook for managing item selection

- packages/@mantine/hooks/src/use-idle/use-idle.ts
Idle timer needs cancelling when hook is being unmounted
> Cancel idle timer when hook is being unmounted in use-idle.ts

- packages/@mantine/core/src/core/MantineProvider/color-functions/to-rgba/to-rgba.ts
I encountered a behavior which I believe is unintentional with the `toRgba` function. The behavior was that if you input a rgba string to the function with an alpha value of 0, the alpha value in the RGBA object would be `1`. 
Before fix: 
```
toRgba("rgba(24, 21, 42, 0)") -> { R: 24, G: 21, B: 42, A: 1 }
```
After fix: 
```
toRgba("rgba(24, 21, 42, 0)") -> { R: 24, G: 21, B: 42, A: 0 }
```
The fix is simply to create a check for if alpha is `undefined` rather than falsy.
> Fix toRgba function

- apps/mantine.dev/src/pages/x/extensions.mdx
fixed #7918
fix typo in the link to the page extension code-highlight
> fix typo in the link to the page extension code-highlight

- packages/@mantine/core/src/components/Popover/use-popover.ts
Fixes https://github.com/mantinedev/mantine/issues/7954
This pull request includes a really simple change to the `usePopover` function in the `Popover` component. 
The change improves type inference of the `onToggle` function to be properly inferred as `() => void`.
> [@mantine/core] Improve type inference of onToggle

- packages/@mantine/core/src/components/Tree/TreeNode.tsx
fixed #7677 
A few changes in `TreeNode` nested tree nodes, it worked
as-is : `<ul role="group" ... >`
to-be: `<Box component="ul" role="group">`
https://github.com/user-attachments/assets/78853a04-6c7c-4f51-a8c2-d234dd94a507
But I'm still not sure exactly *why* it works, and what differences between them making these results?
If anyone has any insight on this, I'd love to hear it.
> [@Mantine/core] Fix: detached DOM causing memory leak in Tree component

- packages/@mantine/core/src/components/Popover/Popover.tsx
- packages/@mantine/core/src/components/Popover/use-popover.ts
- Conditionally apply whileElementsMounted based on keepMounted prop
- Use manual autoUpdate control when keepMounted=true to avoid unnecessary updates on CSS-hidden elements
- Add keepMounted prop to usePopover options interface
Fixes performance issue where autoUpdate ran continuously on hidden popover dropdowns
> [@mantine/core] optimize Popover autoUpdate for keepMounted elements

- packages/@mantine/core/src/components/Collapse/Collapse.story.tsx
- packages/@mantine/core/src/components/Collapse/Collapse.tsx
- packages/@mantine/core/src/components/Collapse/use-collapse.ts
Fixes #7951
Problem
The Collapse component had two conflicting requirements that couldn't be satisfied
simultaneously:
1. Stack layout issue: When a Collapse is closed inside a Stack, it should not
contribute to the Stack's gap spacing
2. Nested animation issue: When Collapses are nested, the parent must remain in the
DOM for child animations to work properly
Root Cause
The core issue was the use of display: 'none' in collapsed state:
- ✅ With display: 'none': Stack gap issue is resolved, but nested animations break
- ✅ Without display: 'none': Nested animations work, but Stack gap issue occurs
Solution
Added a keepMounted prop to the Collapse component that allows explicit control over
this behavior:
Default behavior (most common case)
```tsx
<Stack>
<Button>Toggle</Button>
<Collapse …
```
> [@mantine/core] Add keepMounted prop to Collapse component

- apps/mantine.dev/src/pages/form/schema-validation.mdx
In Zod v4, the `message` key has been deprecated in favor of `error`.
Reference: https://zod.dev/v4/changelog?id=deprecates-message
> Update schema-validation.mdx on zod4 validation

- .storybook/main.ts
start Storybook Error
This PR refactors the Storybook configuration to ensure compatibility with ECMAScript Modules (ESM). The changes include:
Changes Made
- Updated imports: Changed path to node:path to use Node.js built-in module prefix
- Added ESM compatibility: Introduced fileURLToPath and createRequire for proper ESM support
- Replaced CommonJS methods: Updated require.resolve() to use ESM-compatible nodeRequire.resolve()
- Enhanced path resolution: Added proper __filename and __dirname alternatives for ESM environment
Technical Details
- Added ESM-compatible directory resolution using import.meta.url
- Implemented CommonJS interoperability with createRequire
- Maintained backward compatibility with fallback handling
- Follows Node.js ESM best practices
Background
- Node.js 20-22: …
> [bug] Refactor Storybook main config for ESM compatibility.

- packages/@mantine/form/src/hooks/use-form-values/use-form-values.ts
- packages/@mantine/form/src/stories/Form.rendering.story.tsx
- packages/@mantine/form/src/use-form.ts
Fixes #8050
This pull request introduces updates to the `resetField` function and provides an example to demonstrate its usage in uncontrolled form scenarios:
- Added a new story, `UncontrolledResetField`, to illustrate the `resetField` functionality with clear interactions like resetting and managing field values.
- Enhanced the `resetField` implementation to include support for an optional `subscribers` parameter, improving integration with value updates and ensuring compatibility across controlled and uncontrolled modes.
> Fix/reset field rerender (#8017)

- packages/@mantine/core/src/components/MultiSelect/MultiSelect.tsx
- packages/@mantine/core/src/components/MultiSelect/MutliSelect.story.tsx
Adding back this prop that used to be part of v6
See https://v6.mantine.dev/core/multi-select/?t=props for reference
> [@mantine/core] Add clearSearchOnChange back on MultiSelect

- apps/mantine.dev/src/pages/core/scroll-area.mdx
- packages/@mantine/core/src/components/ScrollArea/ScrollArea.tsx
This PR adds a new `onOverflowChange?: (overflowing: boolean) => void` prop to ScrollArea.Autosize.
It fires when content starts or stops exceeding max-height, enabling consumers to react when the container becomes scrollable.
https://github.com/user-attachments/assets/e43d5e79-934f-4907-9326-40c816c5bb46
> Add `onOverflowChange` callback to `ScrollArea.Autosize`

- packages/@mantine/core/src/components/HoverCard/use-hover-card.ts
The HoverCard dropdown closes unexpectedly when clicked, disrupting the user experience as it should remain open during interaction.
The issue occurs because `floating-ui`'s `useDismiss` hook incorrectly triggers an outside click event, calling `onChange(false)` to close the dropdown. The `useHoverCard` hook's inner `useFloating` is only intended for `withinGroup` contexts, so `useDismiss` should only be active when `withinGroup` is enabled. However, `useDismiss` is triggered regardless of this state. Additionally,[ `useDismiss` checks if the dropdown is open before registering events internally,](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useDismiss.ts#L363) but the condition `enabled: typeof settings.opened === 'undefined'` maybe incorrect, leading …
> [@mantine/core] HoverCard: Fix dropdown closing when clicked

- packages/@mantine/hooks/src/use-merged-ref/use-merged-ref.test.tsx
- packages/@mantine/hooks/src/use-merged-ref/use-merged-ref.ts
**Dependencies check up**
I have verified that I use latest version of all @mantine/* packages
What version of @mantine/* packages do you have in package.json?
7.17.8 and also tested on 8.1.3
**What package has an issue?**
@mantine/hooks
**What framework do you use?**
Vite
**In which browsers you can reproduce the issue?**
Chrome, Safari, Firefox
**Describe the bug**
It seems that when merging mantine refs to ReactDND refs, on unmount, we get errors about this cleanup function implemented from a prior PR: https://github.com/mantinedev/mantine/pull/7304/files#diff-7aaef3b012f983195f83037e3474a958b02ad5da696aaf2348b36bb529ce3b41
**If possible, include a link to a codesandbox with a minimal reproduction**
[No response
](https://codesandbox.io/p/devbox/mantine-forked-cwq8ss?workspaceId=ws_HT9C …
> fix: improve use-merged-ref hook cleanup implementation

- apps/help.mantine.dev/src/pages/q/postcss-fns-inline.mdx
> Typo in postcss-fns-inline.mdx

- packages/@mantine/core/src/components/Table/Table.module.css
When using `withColumnBorders` along with rowSpan cells, some borders do not appear (#8088).
Table styles define that borders are given at the end pof each cell that is not last child. The issue is that when rowspan is used, even it seems like a cell is not the last one, for the DOM it is.
In order to fix this via CSS I decided to add another rule that places a border at the start of every cell if it is not the first one. This fixes the cases where rowspan is used.
I choose this solution as I did not found any other way to fix this without requiring the developer to provide manually a "lastCell" indicator.
> [@mantine/core] Table: Fix missing border when rowspan is present

- packages/@mantine/core/src/components/Input/Input.module.css
PasswordInput carret was invisivle because of Pull Request #8063.
Tested both Select component and PasswordInput on Chrome, Edge and FireFox as the original pull request said it was broken in FireFox.
> Fix carret no longer displaying on password inputs

- packages/@mantine/hooks/src/use-list-state/use-list-state.ts
`useState` allows you to pass an initializer value. ([Reference](https://react.dev/reference/react/useState#avoiding-recreating-the-initial-state))
It would be convenient if useListState also supported initializers. Technically, we were passing values directly to useState, so we modified the type definitions accordingly.
> Fix use-list-state type

- apps/mantine.dev/src/app-shell-examples/examples/MobileNavbar/code.json
The CSS code on the Mobile Navbar example page for AppShell is missing the first line of the actual CSS present in MobileNavbar.module.css. This change adds the missing line.
> Add missing CSS declaration (".control {")

- packages/@mantine/core/src/components/ScrollArea/ScrollArea.module.css
- packages/@mantine/core/src/components/ScrollArea/ScrollArea.story.tsx
- packages/@mantine/core/src/components/ScrollArea/ScrollArea.tsx
Fixes #8075
The problem is that `display: block` by default lets its content overflow vertically, but only grows to 100% horizontally. This could be fixed in two ways
1. Make the content have `display: inline-block`
2. Make the content have a fixed width
I fixed the issue by giving the content container of `ScrollArea.Autosize` `width: min-content`. I think that's the least intrusive way of handling this issue that hopefully doesn't break anything else. This way the container resizes whenever the content changes its width.
I deliberately only applied the fix to `ScrollArea.Autosize` as applying it to `ScrollArea` messes up other components like `MultiSelect`.
If anyone has a better solution to this problem feel free to let me know. I kinda worry that applying these styles messes up other …
> Fix Horizontal Scrollbars not updating when content  overflows

- apps/help.mantine.dev/src/pages/q/mantine-provider-missing.mdx
This PR fixes a grammatical error in the help documentation. On line 20 of `apps/help.mantine.dev/src/pages/q/mantine-provider-missing.mdx`, the text "You are do not have" has been corrected to "You do not have" for better readability and proper grammar.
> Fix typo in mantine-provider-missing.mdx

- packages/@mantine/core/src/components/Input/Input.tsx
- packages/@mantine/core/src/components/InputBase/InputBase.tsx
- packages/@mantine/core/src/components/JsonInput/JsonInput.tsx
- packages/@mantine/core/src/components/Textarea/Textarea.tsx
Fix the issue where textarea, Combobox and JSON input lose their vertical padding when the size prop is not provided... 🙏 
- resolved #8174 
- relate docs page:
- https://mantine.dev/combobox/?e=SelectOptionComponent
- https://mantine.dev/core/json-input/
- https://mantine.dev/core/textarea/#enable-resize
> fix(inputs): Textarea, Combobox and JsonInput padding missing

- packages/@mantine/hooks/src/use-debounced-value/use-debounced-value.ts
When using useDebouncedValue cancel in useEffect we need to either biome-ignore or eslint-ignore to avoid accidental cancels.
> fix(hooks): make cancel a stable reference

- packages/@mantine/hooks/src/use-media-query/use-media-query.ts
This fixes an issue with Mantine in an iframe context in Safari. Original issue can be found [here](https://github.com/metabase/metabase/issues/62302).
The original bug happens when switching tabs in an interactive embedded Metabase. It actually comes from the way Safari implements MediaQueryList event handling. It seems that events are triggered while an iframe is being removed, leading to an RTE. The crash only happening in Safari and also crashing the dev tools prevents from having a look at the error, but a git bisect shows that the issue was introduced in https://github.com/metabase/metabase/pull/53447.
Unfortunately there's no way of deterministically knowing when the error will be thrown, hence the `try {...} catch()`.
Also removed the unnecessary `useRef` usage.
Temporary patch in …
> fix(hooks): Safari iframe matchMedia crash

- packages/@mantine/dates/src/components/DateTimePicker/DateTimePicker.tsx
Fix DateTimePicker onDropdownClose callback implementation.
- Properly implement the `onDropdownClose` prop that was missing in the component
logic
- The callback is now correctly triggered when the dropdown closes
> 🐛 Fix DateTimePicker onDropdownClose callback

- packages/@mantine/hooks/src/use-document-visibility/use-document-visibility.ts
The initial document visibility state maybe 'hidden', should set it when useEffect runs.
> [@mantine/hooks] use-document-visibility: Set initial document visibility state

- packages/@mantine/core/src/components/Input/Input.module.css
CSS does not allow circular references.
- [demo @ JSFiddle](https://jsfiddle.net/32q04gfe/)
> 🩹 Fix font-size calculation in Input.module.css

- packages/@mantine/core/src/components/ScrollArea/ScrollArea.module.css
- packages/@mantine/dates/src/components/TimePicker/TimePresets/TimePresets.tsx
fixes #8178
Because of [`min-content` in `ScrollArea.AutoSize`](https://github.com/mantinedev/mantine/pull/8160), when using `ScrollArea.AutoSize`, the width becomes too narrow.
So, fix the style of `ScrollArea.AutoSize`. The data coming into presets is likely to be dynamic, so AutoSize should be used.
result
- presets
- presetsGroups
- presetsRange
This fix doesn't harm #8075.
> fix: too narrow dropdown with preset props in TimePicker because of ScrollArea.AutoSize

- apps/mantine.dev/src/pages/hooks/use-scroll-spy.mdx
- packages/@mantine/hooks/src/use-scroll-spy/use-scroll-spy.ts
This PR adds an 'offset' option to the useScrollSpy hook, used when calculating the active heading with respect to the top of the viewport.
- `offset` - offset from the top of the viewport to use when determining the active heading, by default `0` is used
This allows the hook to accommodate pages with floating headers or other elements that obscures the top of the viewport.
Example usage:
```tsx
function Demo() {
return (
<TableOfContents
scrollSpyOptions={{
offset: 70 // Offsets the "top of the viewport" used when calculating the active element
}}
/>
);
}
```
This fixes an issue where the Table of Contents may display an unexpected heading as active when using the AppShell header.
https://codesandbox.io/p/sandbox/mantine-react-template-forked-wlrnk8
("Title 3" is the topmost visible …
> Add 'offset' option to useScrollSpy hook

- .github/workflows/npm_test.yml
Potential fix for [https://github.com/mantinedev/mantine/security/code-scanning/1](https://github.com/mantinedev/mantine/security/code-scanning/1)
To fix this issue, add an explicit `permissions` block at the workflow (root) level, immediately after the `name:` (and before `on:`), specifying the minimal required permissions for this workflow. Since the workflow only checks out code and runs tests (no steps that need to write to repository contents, pull requests, or issues), set `contents: read`. If you later add jobs interacting with PRs/issues, you can scope them as granularly as needed.  
Edit `.github/workflows/npm_test.yml`, insert the following block after `name: Pull request workflow`:
```yaml
permissions:
contents: read
```
No imports or additional code changes are required; just …
> Potential fix for code scanning alert no. 1: Workflow does not contain permissions

- packages/@mantine/spotlight/src/SpotlightActionsGroup.tsx
Potential fix for [https://github.com/mantinedev/mantine/security/code-scanning/2](https://github.com/mantinedev/mantine/security/code-scanning/2)
To fully escape dangerous characters in the CSS variable interpolation, we must escape both single quotes and backslashes within the `label` string. The best approach is to first escape all backslashes (`\`), then escape single quotes (`'`), since newly-added backslashes could interfere with subsequent escaping if done out of order. Both should use the global regex flag to capture all instances in the string.
Edit only line 47, within `packages/@mantine/spotlight/src/SpotlightActionsGroup.tsx`, to ensure `label` is properly escaped. No additional dependencies are required because JavaScript's built-in string replace with regular expressions …
> Potential fix for code scanning alert no. 2: Incomplete string escaping or encoding

- README.md
In the README, all packages had links to their corresponding documentation pages except for core and hooks.
This PR adds the missing links, ensuring consistency across the section and making it easier to jump directly to the relevant documentation.
> [docs] Add missing links for hooks and core in README

- packages/@mantine/core/src/components/List/List.module.css
Hello👋,
As a solution to issue #8165 , I changed `list-style-position: inside` to `list-style-position: outside`.
Issue #2778  also suggested using `outside`, and I believe this change is beneficial for preventing potential future bugs. Should I instead maintain `inside` and make modifications in other areas?
Additionally, after changing to `outside`, there's now a spacing difference between the marker and text, and for the "With Icons" case, padding-inline-start has been applied to secure the marker's position. To maintain the same appearance as before, additional adjustments would be needed.
If you could suggest an alternative approach, I'd be happy to implement it accordingly. Thank you.
> 🐛Fix: nestedList overflow issue

- packages/@mantine/dates/src/components/Month/get-end-of-week/get-end-of-week.ts
Calling `getEndOfWeek` with an invalid date now causes an endless loop (`getEndOfWeek("", "")` for instance).
See https://codesandbox.io/p/sandbox/priceless-flower-8v9mhl?file=%2Fsrc%2FApp.js%3A7%2C5-7%2C17
This function is at least also called from `DateInput`. Simply setting an invalid value there also causes the loop after clicking the input:
```
<DateInput value={'invalid'} />
```
> [@mantine/dates] prevent endless loop in getEndOfWeek
